<?php 
	$categories = $this->getCategoryByIds();
	
	$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
	$settings = $themeHelper->getThemeSettings();
	
	$_catalogHelper = $this->helper('Magento\Catalog\Helper\Output');
	
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	
	$form_key = $block->getBlockHtml('formkey');
	$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
	$showCompare = $settings['catalog']['compare_button'] ? false : true;
	$hoverChange = $settings['catalog']['hover_change'] ? true : false;
	$showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
	$showReview = $settings['catalog']['review_count'] ? false : true;
	$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');

?>

<div class="content-block product-tab new-product-cat-block new-product-cat-tab-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title') && $this->getData('mgs_panel_title') != ""): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note') && $this->getData('mgs_panel_note') != ""): ?>
				<div class="subtitle"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if(count($categories)>0): ?>
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $perRow = $this->getPerrow(); ?>
		<?php $col = $themeHelper->convertPerRowtoCol($perRow); ?>
		<?php $ratio = $this->getRatio(); ?>
		<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW; ?>
		<?php $autoPlay = $this->getAutoplay() ? 'true' : 'false'; ?>
		<?php $stopAuto = $this->getStopAuto() ? 'true' : 'false'; ?>
		<?php $nav = $this->getNavigation() ? 'true' : 'false'; ?>
		<?php $dot = $this->getPagination() ? 'true' : 'false'; ?>
		
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $columnCount = $perRow * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		
		<?php 
			$ratio = $this->getRatio();
			$size = $themeHelper->getImageSize($ratio);
			$padding = $themeHelper->getImagePadding($ratio);
			$baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png');
		?>
		
		<div class="tabbable">
			<ul class="nav nav-tabs menu-product-tabs">
				<?php $i=0; foreach($categories as $category): $i++ ?>
					<li class="nav-item">
						<a class="nav-link<?php if($i==1): ?> active<?php endif ?>" data-toggle="tab" href="#category-tab-<?php echo $category->getId().$blockId ?>" role="tab"><?php echo $category->getName(); ?></a>
					</li>
				<?php endforeach ?>
			</ul>
			<div class="tab-content">
				<?php $i=0; foreach($categories as $category): $i++ ?>
					<div id="category-tab-<?php echo $category->getId().$blockId ?>" class="tab-pane<?php if($i==1): ?>  active<?php endif ?>">
						<div class="new-product-category-tab" id="category<?php echo $category->getId().$blockId; ?>-new-products">
						
							<?php $_productCollection = $this->getProductCollection($category); ?>
							<?php if (count($_productCollection)>0): ?>
								<div class="block widget mgs-products new-products-grid products-grid <?php if($useSlider && !$slideMultiRow): ?> row<?php endif ?> <?php if($useSlider && $slideMultiRow): ?> multiple-row<?php endif ?>">
								
									<div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row row-wrapper row-<?php echo $perRow ?><?php endif ?>" id="new-products<?php echo $category->getId().$blockId; ?>">
										
										<?php $j=0; $k=0; foreach ($_productCollection as $_product): $j++; ?>
										
											<?php 
												$wlDataPost = $block->getAddToWishlistParams($_product);
												$postParams = $block->getAddToCartPostParams($_product);
												$review = $block->getReviewsSummaryHtml($_product, $templateType, $showReview);
												$prdPrice = $block->getProductPrice($_product);
												$swatches = $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTextSwatch($this->getSwatches())->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml();
											?>
											
											<?php if($slideMultiRow): ?>
												<?php if ($k++ % $columnCount == 0): ?>
												<div class="item row row-wrapper row-<?php echo $perRow ?>">
												<?php endif ?>
											<?php endif ?>
											
													<div class="product product-item<?php if($slideMultiRow || !$this->hasData('number_row')): ?> col<?php endif ?>">
														<?php echo $this->getLayout()
																		->createBlock('Magento\Framework\View\Element\Template')
																		->setProduct($_product)
																		->setThemeHelper($themeHelper)
																		->setImageHelper($_imagehelper)
																		->setCatalogHelperOutput($_catalogHelper)
																		->setRatio($ratio)
																		->setSize($size)
																		->setPadding($padding)
																		->setLazyLoadBaseImage($baseImage)
																		->setFk($form_key)
																		->setPostParams($postParams)
																		->setReview($review)
																		->setPrdPrice($prdPrice)
																		->setSwatches($swatches)
																		->setHoverChange($hoverChange)
																		->setQuickViewHelper($quickViewHelper)
																		->setCompare($showCompare)
																		->setWishList($showWishList)
																		->setWishListPost($wlDataPost)
																		->setLazyLoad($lazyLoad)
																		->setTemplate('MGS_Mpanel::products/product_item/grid/default.phtml')
																		->toHtml(); ?>
													</div>
											
											<?php if($slideMultiRow): ?>
												<?php if ($k % $columnCount == 0 || $k == count($_productCollection)): ?>
												</div>
												<?php endif ?>
											<?php endif ?>
										<?php endforeach; ?>
									</div>
									
									<?php if($useSlider): ?>
										<script type="text/javascript">
											require([
												'jquery',
												'mgs/owlcarousel'
											], function ($) {
												var owlnewcattab<?php echo $category->getId().$blockId ?> = $('#new-products<?php echo $category->getId().$blockId ?>').owlCarousel({
													<?php if($slideMultiRow): ?>
														items: 1,
													<?php else: ?>
														items: <?php echo $perRow; ?>,
													<?php endif ?>
													autoplay: <?php echo $autoPlay ?>,
													autoplayHoverPause: <?php echo $stopAuto ?>,
													rtl: true,
													nav: <?php echo $nav ?>,
													dots: <?php echo $dot ?>,
													autoHeight: true,
													navText: ["<i class='ti-angle-left'></i>","<i class='ti-angle-right'></i>"],
													<?php if(!$slideMultiRow):?>
														responsive:{
															0:{
																items:1
															},
															480:{
																items:2
															},
															768:{
																items:<?php echo $perRow; ?>
															}
														}
													<?php endif ?>
												});
											});
										</script>
									<?php endif ?>
									
								</div>
							<?php else: ?>
								<div role="alert" class="alert alert-warning"> <?php echo __('The category "%1" haven\'t top new product.', $category->getName()) ?> </div>
							<?php endif ?>
						</div>
						
						<?php if ((count($_productCollection)>0) && !$useSlider): ?>
							<?php if(($this->hasData('loadmore') && $this->getData('loadmore')=='1') && ((!$this->getData('limit')) || (count($_productCollection) == $this->getData('limit')))): ?>
								<div class="text-center toolbar-loadmore">
									<a class="btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type'=>'new-products-category', 'category'=>$category->getId(), 'perrow'=>$perRow, 'limit'=>$this->getLimit(), 'ratio'=>$this->getRatio(), 'col'=>$col, 'block_id'=>$blockId, 'tabs'=>1, 'p'=>2]) ?>"><span><?php echo __('View More Products') ?></span><span class="load"><?php echo __('Loading') ?></span></a>
								</div>
							<?php endif ?>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no categories matching the selection.') ?></div>
	<?php endif ?>
</div>