<?php
/**
 * @category   Biztech
 * @package    Biztech_DPI
 * @author     developer1.test@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Biztech\DPI\Block;

use Magento\Framework\View\Element\Template\Context;
use Biztech\DPI\Model\DPIFactory;
/**
 * DPI List block
 */
class DPIListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var DPI
     */
    protected $_dpi;
    public function __construct(
        Context $context,
        DPIFactory $dpi
    ) {
        $this->_dpi = $dpi;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Biztech DPI Module List Page'));
        
        if ($this->getDPICollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'biztech.dpi.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getDPICollection()
            );
            $this->setChild('pager', $pager);
            $this->getDPICollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getDPICollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $dpi = $this->_dpi->create();
        $collection = $dpi->getCollection();
        $collection->addFieldToFilter('status','1');
        //$dpi->setOrder('dpi_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}