<?php
/**
 * @category   Biztech
 * @package    Biztech_DPI
 * @author     developer1.test@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Biztech\DPI\Block;

use Magento\Framework\View\Element\Template\Context;
use Biztech\DPI\Model\DPIFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * DPI View block
 */
class DPIView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var DPI
     */
    protected $_dpi;
    public function __construct(
        Context $context,
        DPIFactory $dpi,
        FilterProvider $filterProvider
    ) {
        $this->_dpi = $dpi;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Biztech DPI Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $dpi = $this->_dpi->create();
        $singleData = $dpi->load($id);
        if($singleData->getDPIId() || $singleData['dpi_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}