<?php
$_item = $block->getItem();
$params = $_item->getProduct()->getCustomOptions();
$design_id = '';
$itemId;
$notAllowToEdit = "false";
foreach ($params as $key => $pram) {
    $itemId = base64_encode($pram->getItemId());
    if ($key == 'additional_options') {
        $designData = $pram->getData();
        $designdata1 = $this->helper('Biztech\Productdesigner\Helper\Data')->unserializeData($designData['value']);
        foreach ($designdata1 as $dData) {
            if ($dData['code'] == "printing_method" || $dData['code'] == "name_numbers") {
                $notAllowToEdit = "true";
            }
            if ($dData['code'] == 'product_design') {
                $design_id = base64_encode($dData['design_id']);
            }
        }
    }
}


$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?php echo ($design_id != '') ? $storeManager->getStore()->getBaseUrl() . 'productdesigner/index/index/id/' . $product->getId() . '/design/' . $design_id . '/item/' . $itemId : $block->getProductUrl(); ?>"  title="<?php echo $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
                <?php else: ?>
                    <span class="product-item-photo">
                    <?php endif; ?>
                    <?php
                    if ($design_id != '') {
                        $designImages = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Designimages\Collection')->addFieldToFilter('design_id', Array('eq' => base64_decode($design_id)))->addFieldToFilter('design_image_type', 'base')->getFirstItem()->getData();
                        if (isset($designImages['image_path'])) {
                            $path = $designImages['image_path'];
                            $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
                            $url = $mediaUrl . "productdesigner/designs/" . base64_decode($design_id) . "/base/" . $path;
                            ?>
                            <span class="product-image-container"style="width:165px;">
                                <span class="product-image-wrapper"style="padding-bottom: 100%;">
                                    <img class="product-image-photo" src="<?php echo $url; ?>" width="" height="" class="byi-cart-image"/>
                                </span>
                            </span>
                            <?php
                        } else {
                            echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml();
                        }
                    } else {
                        echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml();
                    }
                    ?>
                    <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php
                if ($design_id != '') {
                    if ($block->hasProductUrl()):
                        ?>
                        <a href="<?php echo $storeManager->getStore()->getBaseUrl() . 'productdesigner/index/index/id/' . $product->getId() . '/design/' . $design_id . '/item/' . $itemId; ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php
                    endif;
                } else {
                    ?>
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php
                    endif;
                }
                ?>
            </strong>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>                                
                                <?= $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <span class="pricing msrp">
                <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                    <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                </a>
            </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                       name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                       data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                       value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                       class="input-text qty"
                       maxlength="12"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty" 
                       <?php
                       if ($notAllowToEdit == "true") {
                           echo "readonly";
                       }
                       ?>/>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
    <?= $block->getRowTotalHtml($_item) ?>
<?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="4">
        <div class="actions-toolbar">
<?= /* @escapeNotVerified */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
