<!doctype html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="<?php echo $this->getPageLogo(); ?>" type="image/x-icon">
    <title><?php echo $this->getPageTitle(); ?></title>
    <meta charset="utf-8">
    <link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/styles.css'); ?>" />
    <base href="<?php echo $this->getViewFileUrl('Biztech_Productdesigner') ?>/dist/">  
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    <style type="text/css">
    .byi-tool-disabled{position:relative;padding:1em;margin:1em;color:#e02b27;font-size:13px;background:#fae5e5;padding-left:3.85em;padding-right:1.2em}.byi-close-icon{position:absolute;left:15px;top:10px;width:24px;height:24px;text-align:center;margin:auto;opacity:1;padding:0;border:0;border-radius:0;display:block;background-color:#e02b27;border-radius:50%}.byi-close-icon span{font-size:0;width:24px;height:24px;display:block;margin:auto;-webkit-transform:rotate(45deg);-moz-transform:rotate(45deg);-o-transform:rotate(45deg);transform:rotate(45deg)}.byi-close-icon span:before,.byi-close-icon span:after{position:absolute;content:"";left:0;right:0;top:0;bottom:0;margin:auto;background:#FFF}.byi-close-icon span:before{width:2px;height:16px}.byi-close-icon span:after{width:16px;height:2px}
</style>
</head>
<body class="byi-body">
    <input type="hidden" name="admin_design" id="admin_design">
    <input type="hidden" id="namenumber_design">
    <?php
    $productParams = $this->getProductParams();
    $isEnable = $productParams['isEnable'];
    $isPdEnable = $productParams['isPdEnable'];
    $message = __('Product Designer not enabled.') . ' Back to <a href="' . base64_decode($productParams['mage_base_url']) . '">' . __('Home page') . '</a>';
    if (isset($isEnable) && $isEnable && isset($isPdEnable) && $isPdEnable) {
        foreach ($productParams as $name => $value) {
            if (is_array($value)) {
                foreach ($value as $key => $val) {
                    ?>
                    <input type="hidden" class="<?php echo $name; ?>" data-attr-id="<?php echo $key; ?>" name="<?php echo $name . '[' . $key . ']'; ?>" value="<?php echo is_array($val) ? implode(",", $val) : $val; ?>"/>
                    <?php
                }
            } else {
                ?>
                <input type="hidden" class="<?php echo $name; ?>" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
                <?php
            }
        }
        ?>
        <app-root>
            <div class="site-loader-box" >

                <img src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner') ?>/dist/assets/img/loader.gif" />
            </div>
        </app-root>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/runtime.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/es2015-polyfills.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/polyfills.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/scripts.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/main.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Biztech_Productdesigner/dist/vendor.js') ?>"></script>
        <?php
    } else {
        echo '<p class="byi-tool-disabled"><span class="byi-close-icon"><span></span></span>' . $message . '</p>';
    }
    ?>
</body>
</html>
