<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$currentURL = $store->getCurrentUrl();

$isSearchPage = strpos($currentURL,"catalogsearch");
if($isSearchPage > 0){
}
else{
    /** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
    /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */
    /** @var \Amasty\Shopby\Block\Navigation\FilterRenderer\Category $block */
    /** @var \Amasty\Shopby\Model\Layer\Filter\CategoryItems $filterItems */

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');

    $parent_category_id = $category->getId(); //Parent category ID
    $categoryObj = $categoryRepository->get($parent_category_id);
    $subcategories = $categoryObj->getChildrenCategories();
    $cat[] = $category->getName();
    foreach($subcategories as $subcategorie) {
       $cat[] = $subcategorie->getName();
   }
}


$filterItems = $block->getFilter()->getItems();
$categoryHelper = $block->getCategoryHelper();
$filterSetting = $block->getFilterSetting();
$filterSubcategoriesView = $block->isFolding();
$filterSubcategoriesType = $filterSubcategoriesView
? "amShopbyFilterCategoryLabelsFolding"
: 'amShopbyFilterCategoryFlyOut';
$filterFoldingClass = $filterSubcategoriesView ? '-folding' : '';
$isParent = $block->isParent($filterItems, $block->getPath());
$filterPathItems = $filterItems->getItems($block->getPath());


?>

<?php if (count($filterPathItems)) : ?>
    <?php foreach ($filterPathItems as $filterItem) : ?>
        <?php $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString(); ?>
        <?php $label = $block->escapeHtml($filterItem->getOptionLabel()); ?>
        <?php// print_r($cat);exit; ?>
        <?php 
        if($isSearchPage > 0){ ?>
            <li class="item" data-label="<?= $block->escapeHtml($filterItem->getOptionLabel()) ?>">
                <?php if ($block->isExpandByClick($currentPath)) : ?>
                    <span class="am-collapse-icon"></span>
                <?php endif; ?>

                <?php if ($filterItem->getCount() > 0) : ?>
                    <input
                    name="amshopby[<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>][]"
                    value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                    type="<?= /* @noEscape */ $block->getInputType(); ?>"
                    <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                    />
                    <a class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid()) ?>
                    <?= /* @noEscape */ ($isParent) ? 'amshopby-filter-parent' : '' ?>"
                    data-am-js='filter-item-category-<?= /* @noEscape */ $filterSubcategoriesType ?>'
                    href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?= /* @noEscape */ $filterItem->getRelNofollow() ? ' rel="nofollow"' : '' ?>
                    >
                <?php endif; ?>

                <?php if ($block->getFilter()->useLabelsOnly()) : ?>
                <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
                <?php else : ?>
                    <img src="<?= /* @noEscape */ $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                    class="am-category-image"
                    title="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                    alt="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                    height="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"
                    width="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"/>
                    <?php if ($block->getFilter()->useLabelsAndImages()) : ?>
                    <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
            <span class="count">(<?=$filterItem->getCount()?>)</span>
            <?php endif; ?>

            <?php if ($filterItem->getCount() > 0) : ?>
            </a>
        <?php endif; ?>

        <?php if ($filterItems->getItemsCount($currentPath)) : ?>
            <?php $level = $block->getLevel();?>
            <ul class="items items-children level-<?= /* @noEscape */ $level . ' ' . $filterFoldingClass; ?>">
                <?= /* @noEscape */ $block->renderChildrenItems($currentPath); ?>

            </ul>
        <?php endif; ?>
    </li>
<?php }
else{ ?>
    <?php  if (in_array($label, $cat)) { ?>       
        <li class="item" data-label="<?= $block->escapeHtml($filterItem->getOptionLabel()) ?>">
            <?php if ($block->isExpandByClick($currentPath)) : ?>
                <span class="am-collapse-icon"></span>
            <?php endif; ?>

            <?php if ($filterItem->getCount() > 0) : ?>
                <input
                name="amshopby[<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>][]"
                value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                type="<?= /* @noEscape */ $block->getInputType(); ?>"
                <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                />
                <a class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid()) ?>
                <?= /* @noEscape */ ($isParent) ? 'amshopby-filter-parent' : '' ?>"
                data-am-js='filter-item-category-<?= /* @noEscape */ $filterSubcategoriesType ?>'
                href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                <?= /* @noEscape */ $filterItem->getRelNofollow() ? ' rel="nofollow"' : '' ?>
                >
            <?php endif; ?>

            <?php if ($block->getFilter()->useLabelsOnly()) : ?>
            <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
            <?php else : ?>
                <img src="<?= /* @noEscape */ $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                class="am-category-image"
                title="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                alt="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                height="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"
                width="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"/>
                <?php if ($block->getFilter()->useLabelsAndImages()) : ?>
                <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
        <span class="count">(<?=$filterItem->getCount()?>)</span>
            <?php endif; ?>

            <?php if ($filterItem->getCount() > 0) : ?>
            </a>
        <?php endif; ?>

        <?php if ($filterItems->getItemsCount($currentPath)) : ?>
            <?php $level = $block->getLevel();?>
            <ul class="items items-children level-<?= /* @noEscape */ $level . ' ' . $filterFoldingClass; ?>">
                <?= /* @noEscape */ $block->renderChildrenItems($currentPath); ?>

            </ul>
        <?php endif; ?>
    </li>
<?php } ?>
<?php  } ?>


<?php endforeach; ?>

<script type="text/x-magento-init">
    {
        "[data-am-js='filter-item-category-<?= /* @noEscape */ $filterSubcategoriesType ?>']": {
        "<?= /* @noEscape */ $filterSubcategoriesType ?>" : {
        "collectFilters": <?= /* @noEscape */ $block->collectFilters(); ?>
    }
}
}
</script>
<?php endif; ?>