<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
<?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
<?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session')->getCustomer()->getId();
    $customerFactory = $objectManager->get('\Magento\Customer\Model\CustomerFactory')->create()->load($customerSession);


    $billingAddressId = $customerFactory->getDefaultBilling();
    $address = $objectManager->get('Magento\Customer\Model\AddressFactory')->create()->load($billingAddressId);
   
    $emailEdit = $websiteEdit = "";
    if($block->getAddress()->getCustomAttribute('contact_email') !== null && $block->getAddress()->getCustomAttribute('contact_email')->getValue() !== null) {
        $emailEdit = $block->getAddress()->getCustomAttribute('contact_email')->getValue();
    }
    if($block->getAddress()->getCustomAttribute('website') !== null && $block->getAddress()->getCustomAttribute('website')->getValue() !== null) {
        $websiteEdit = $block->getAddress()->getCustomAttribute('website')->getValue();
    }
    
?>
<div class="tab-content">
    <div class="tab-pane active text-style" id="tab1">
        <div class="edit-profile">
            <div class="contect-information">
                <div class="contact-text">
                    <h2>CONTACT INFORMATION</h2>
                </div>
                <form class="form-address-edit"
                      action="<?php echo $this->getUrl('sweda/customeraddress/formPost',array("_query" => array("id"=>$address->getData('entity_id')))); ?>"
                      method="post"
                      id="form-validate"
                      enctype="multipart/form-data"
                      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <?= $block->getBlockHtml('formkey') ?>
                        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="per-infomation">
                                  <label for="mobile" class="">Email</label>
                                    <div class="control">
                                        <input type="text" value="<?= $emailEdit ?>" name="contact_email" id="contact_email" title="<?php echo __('Email') ?>" class="input-text">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="per-infomation">
                                  <?php if ($_telephone->isEnabled()): ?>
                                      <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
                                  <?php endif ?>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="per-infomation">
                                  <div class="field street required">
                                        <label for="street_1" class="label">
                                            <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span>
                                        </label>
                                        <div class="control">
                                            <input type="text"
                                                   name="street[]"
                                                   value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                                                   id="street_1"
                                                   class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                                            <div class="nested">
                                                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                                <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                                                    <div class="field additional">
                                                        <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                                            <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                                                        </label>
                                                        <div class="control">
                                                            <input type="text" name="street[]"
                                                                   value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                                                   title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                                                   id="street_<?= /* @noEscape */ $_i + 1 ?>"
                                                                   class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                                        </div>
                                                    </div>
                                                <?php endfor; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                              <?= $block->getNameBlockHtml() ?>
                            </div>
                            
                            <div class="col-md-4">
                                <div class="per-infomation">
                                  <div class="field country required">
                                        <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                                        <div class="control">
                                            <?= $block->getCountryHtmlSelect() ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="per-infomation">
                                  <div class="field city required">
                                    <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                                    <div class="control">
                                        <input type="text"
                                               name="city"
                                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                                               title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                                               class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                                               id="city">
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="per-infomation">
                                  <div class="field region required">
                                    <label for="region_id" class="">State</label>
                                    <div class="control">
                                        <select id="region_id" name="region_id"
                                                title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                                class="validate-select" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                                            <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                        </select>
                                        <input type="text"
                                               id="region"
                                               name="region"
                                               value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                                               title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                                               class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
                                    </div>
                                </div>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="per-infomation">
                                    <div class="field zip required">
                                        <label for="zip" class="">Zip Code</label>
                                        <div class="control">
                                            <input type="text"
                                                   name="postcode"
                                                   value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                                                   title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                                                   id="zip"
                                                   class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit"
                                    class="action save primary custom-address-save-btn"
                                    data-action="save-address"
                                    title="<?= $block->escapeHtmlAttr(__('SAVE PROFILE')) ?>">
                                <span><?= $block->escapeHtml(__('SAVE PROFILE')) ?></span>
                            </button>
                            <div class="secondary">
                                <a class="action cancel" href="<?= $this->getUrl('customer/account/') ?>">
                                    <span><?= $block->escapeHtml(__('CANCEL')) ?></span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="hepl-center-section edit-profile-bottom">
                        <p><strong>Need Help? Go to our </strong>HELP CENTER</p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
