<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<?php if ($customerSession->isLoggedIn()) : ?>
<form class="form form-update-password" action="<?= $block->escapeUrl($block->getUrl('sweda/customer/updatepassword')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Password')) ?></span></legend><br>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text required-entry" name="current_password" id="current-password" data-validate="{required:true}" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text required-entry" name="password" id="password"
                data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                data-input="new-password"
                data-validate="{required:true, 'validate-customer-password':true}"
                autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite"><!-- 
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                 --></div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text required-entry" name="password_confirmation" data-validate="{required:true}" id="password-confirmation"
                data-input="confirm-password"
                autocomplete="off" />
            </div>
            <div class="error custom-password-mismatch"></div>
            <div id="pswd_info">
                <span>Password must meet the following requirements:</span>
                <ul>
                    <li id="length" class="invalid">Minimum 8 Characters in Length</li>
                    <li id="capital" class="invalid">One Capital Letter</li>
                    <li id="number" class="invalid">One Number</li>
                    <li id="specialletter" class="invalid">One Special Character (@,#,$....)</li>
                </ul>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" id="submit_update_pwd" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>
<?php else : ?>
    <?php 
        $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
        $redirect->setRedirect('/customer/account/login');
        return $redirect;
    ?>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        jQuery(document).ready(function(){

            $('input[type=password]').keyup(function(){

                var pswd = $(this).val();
                console.log(pswd)

                if ( pswd.length < 8 ) {
                    $('#length').removeClass('valid').addClass('invalid');
                } else {
                    $('#length').removeClass('invalid').addClass('valid');
                }

                var pattern=/^[a-zA-Z0-9- ]*$/;
                if (pattern.test(pswd) == false) {
                    $('#specialletter').removeClass('invalid').addClass('valid');
                } else {
                    $('#specialletter').removeClass('valid').addClass('invalid');
                }
                if ( pswd.match(/[A-Z]/) ) {
                    $('#capital').removeClass('invalid').addClass('valid');
                } else {
                    $('#capital').removeClass('valid').addClass('invalid');
                }
                if ( pswd.match(/\d/) ) {
                    $('#number').removeClass('invalid').addClass('valid');
                } else {
                    $('#number').removeClass('valid').addClass('invalid');
                }
            });

            $('input[type=password]').focus(function() {
                $('#pswd_info').show();
            });
            $('input[type=password]').blur(function() {
                $('#pswd_info').hide();
                passwordCompare();                
            });
            $('input[name=password_confirmation]').blur(function() {
                $('#pswd_info').hide();
                passwordCompare();                
            });

            function passwordCompare(){
                var errormsg = "Please enter the same password again.";
                var pass = $('input[name=password]').val();
                var repass = $('input[name=password_confirmation]').val();
                if(($('input[name=password]').val().length == 0) || ($('input[name=password_confirmation]').val().length == 0)){
                    $('.custom-password-mismatch').html(errormsg);
                }   
                else if (pass != repass) {
                    $('.custom-password-mismatch').html(errormsg);
                }
                else {
                    $('.custom-password-mismatch').html('');
                }
            }

            jQuery("form.form-update-password").submit(function(){
                if (jQuery('form.form-update-password').valid()) {
                    return confirm('Are you sure you want to update the password?');
                }else{
                    return false;
                }
            });
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#form-validate": {
        "validation": {}
    }
}
</script>