<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product

$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');

$regularPriceCollection = $block->getProductRegularPrices();

$productImprintMethods = $block->getProductImprintMethod();

$productRegularPriceType = $block->getProductRegularPriceTypes();

$imprintMethodWiseData = array();
$counter = 1;
foreach ($productImprintMethods as $productImprintMethod)
{
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['name'] = $productImprintMethod->getImprintMethodName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['matrix'] = $productImprintMethod->getMatrix();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['full_color'] = $productImprintMethod->getFullColor();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['color_included_in_price'] = $productImprintMethod->getColorIncludedInPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['maximum_color'] = $productImprintMethod->getMaximumColor();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['location_included_in_price'] = $productImprintMethod->getLocationIncludedInPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['maximum_location'] = $productImprintMethod->getMaximumLocation();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['productiont_time'] = $productImprintMethod->getProductiontTime();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['production_unit'] = $productImprintMethod->getProductionUnit();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['rule'] = $productImprintMethod->getRule();

  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['name'] = $productImprintMethod->getImprintChargeName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['qty_start'] = $productImprintMethod->getQtyStart();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['qty_end'] = $productImprintMethod->getQtyEnd();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['price'] = $productImprintMethod->getPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['code'] = $productImprintMethod->getCode();

  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['postion']['name'] = $productImprintMethod->getImprintPostionName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['postion']['area'] = $productImprintMethod->getImprintPostionArea();


  $counter++;
}

?>
<?php $priceData = $regularPriceCollection->getData(); ?>
<?php
    $i = -1;
    if(isset($priceData[0]))
    {
        $priceDataFirstItem = $priceData[0]; 
        if (isset($priceDataFirstItem['special_price']) && !empty($priceDataFirstItem['special_price'])) {
            $i = 2;
        } else {
            $i = 1;
        }
    }
?>
<?php if($priceData) : ?>
    <div class class="product-add-form">
        <?php if ($productRegularPriceType->getPriceType() != 'call_for_price') : ?>
            <div class="desktop-only">
                <table class="table data grouped" id="super-product-table">
                    <tbody>
                        <tr>
                            <th>Quantity</th>
                            <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
                                <td>
                                    <?php if (!empty($regularPriceData->getQtyStart())) : ?>
                                        <?php echo $regularPriceData->getQtyStart() ?>
                                    <?php endif; ?>
                                    <?php if (!empty($regularPriceData->getQtyEnd())) : ?>
                                        <?php echo '-'.$regularPriceData->getQtyEnd() ?>
                                    <?php else : ?>
                                        <?php echo '+' ?>
                                    <?php endif; ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                        <?php if($i == 2) : ?>
                                
                                <?php while($i > 0) : ?>
                                <?php if ($i == 2) : ?>
                                    <tr>
                                        <th>Standard</th>
                                        <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
                                            <td>
                                                <strike>
                                                    <?php 
                                                        if ($regularPriceData->getDecorativePrice() && !empty($regularPriceData->getDecorativePrice())) {
                                                            echo $priceHelper->currency($regularPriceData->getDecorativePrice(), true, false); 
                                                        }
                                                    ?>
                                                    <?php 
                                                        if ($regularPriceData->getDecorativePriceCode() && !empty($regularPriceData->getDecorativePriceCode())) {
                                                            echo '('.$regularPriceData->getDecorativePriceCode().')';
                                                        }
                                                    ?>
                                                </strike>
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endif; ?>
                                <?php if ($i == 1) : ?>
                                    <tr>
                                        <th>Special Price</th>
                                        <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
                                            <td>
                                                <?php 
                                                    if ($regularPriceData->getSpecialPrice() && !empty($regularPriceData->getSpecialPrice())) {
                                                        echo $priceHelper->currency($regularPriceData->getSpecialPrice(), true, false); 
                                                    }
                                                ?>
                                                <?php 
                                                    if ($regularPriceData->getSpecialPriceCode() && !empty($regularPriceData->getSpecialPriceCode())) {
                                                        echo '('.$regularPriceData->getSpecialPriceCode().')';
                                                    }
                                                ?>
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endif; ?>
                                <?php $i--; ?>
                            <?php endwhile; ?>
                            
                        <?php else : ?>
                            <tr>
                                <th>Price</th>
                                <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
                                    <td>
                                        <?php 
                                            if ($regularPriceData->getDecorativePrice() && !empty($regularPriceData->getDecorativePrice())) {
                                                echo $priceHelper->currency($regularPriceData->getDecorativePrice(), true, false); 
                                            }
                                        ?>
                                        <?php 
                                            if ($regularPriceData->getDecorativePriceCode() && !empty($regularPriceData->getDecorativePriceCode())) {
                                                echo '('.$regularPriceData->getDecorativePriceCode().')';
                                            }
                                        ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>

<div class="product pricing overview">
    <div class="value" itemprop="description">
        <div class="product-info-specification">
            <?php if(sizeof($imprintMethodWiseData)) : ?>
                <?php $newChargesArray = array() ?>
                <ul class="nav nav-tabs" role="tablist">
                    <?php $counter = 1; ?>
                    <?php foreach($imprintMethodWiseData as $imprintId => $proImprintMethodData) : ?>
                        <?php if(isset($proImprintMethodData['charges'][2])) : ?>
                            <?php $newChargesArray[$proImprintMethodData['name']] = $proImprintMethodData['charges'][2]; ?>
                            <li class="nav-item">
                              <a class="nav-link <?php if ($counter == 1){echo 'active';}else{echo '';} ?>" href="#<?php echo str_replace(" ","-",$proImprintMethodData['name']); ?>" role="tab" data-toggle="tab"><?php echo $proImprintMethodData['name'] ?></a>
                            </li>
                        <?php endif; ?>
                        <?php $counter++; ?>
                    <?php endforeach; ?> 
                </ul>
                <div class="tab-content">
                    <?php $counter = 1; ?>
                    <?php foreach($newChargesArray as $imprintName => $imprintChargesArray) : ?>
                        <div role="tabpane<?php echo trim($counter) ?>" class="tab-pane fade <?php if ($counter == 1){echo 'in active';}else{echo '';} ?>" id="<?php echo str_replace(" ","-",$imprintName); ?>">
                            <table class="table data grouped" id="super-product-table">
                                <tbody>
                                    <?php foreach($imprintChargesArray as $charageName => $charageData) : ?>
                                        <tr>
                                            <th><?php echo "Quantity" ?></th>
                                            <?php foreach($charageData as $key => $charageRecord) : ?>
                                                <td>
                                                    <?php
                                                    if (isset($charageRecord['qty_start']) && !empty($charageRecord['qty_start']))
                                                        echo $charageRecord['qty_start'];
                                                    
                                                    if (isset($charageRecord['qty_end']) && !empty($charageRecord['qty_end']))
                                                        echo '-'.$charageRecord['qty_end'];
                                                    else
                                                        echo "+";
                                                    ?>
                                                </td>
                                            <?php endforeach; ?>
                                        </tr>
                                        <?php break; ?>
                                    <?php endforeach; ?>
                                    <?php foreach($imprintChargesArray as $charageName => $charageData) : ?>
                                        <tr>
                                            <th><?php echo $charageName ?></th>
                                            <?php foreach($charageData as $key => $charageRecord) : ?>
                                                <td>
                                                    <?php
                                                        if(isset($charageRecord['price']) && !empty($charageRecord['price']))
                                                            echo $priceHelper->currency($charageRecord['price'], true, false);
                                                        if(isset($charageRecord['code']) && !empty($charageRecord['code']))
                                                            echo '('.$charageRecord['code'].')';
                                                    ?>
                                                </td>
                                            <?php endforeach; ?>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php $counter++; ?>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="desktop-only">
    <div class="product-download-information">
        <a href="<?php echo $this->getUrl('sweda/printproduct/printproduct',array('_query'=>array('id'=>$product->getId())));?>" class="pro-print-btn download-link">view/download All Product Information</a>
    </div>
</div>
<div class="mobile-only">
    <div class="product-download-information">
        <a class="download-link">View All Product Data</a>
    </div>
</div>