<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');

$regularPriceCollection = $block->getProductRegularPrices();

$productImprintMethods = $block->getProductImprintMethod();

$productRegularPriceType = $block->getProductRegularPriceTypes();

$imprintMethodWiseData = array();
$counter = 1;
foreach ($productImprintMethods as $productImprintMethod)
{
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['name'] = $productImprintMethod->getImprintMethodName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['matrix'] = $productImprintMethod->getMatrix();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['full_color'] = $productImprintMethod->getFullColor();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['color_included_in_price'] = $productImprintMethod->getColorIncludedInPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['maximum_color'] = $productImprintMethod->getMaximumColor();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['location_included_in_price'] = $productImprintMethod->getLocationIncludedInPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['maximum_location'] = $productImprintMethod->getMaximumLocation();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['productiont_time'] = $productImprintMethod->getProductiontTime();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['production_unit'] = $productImprintMethod->getProductionUnit();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['rule'] = $productImprintMethod->getRule();

  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['name'] = $productImprintMethod->getImprintChargeName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['qty_start'] = $productImprintMethod->getQtyStart();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['qty_end'] = $productImprintMethod->getQtyEnd();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['price'] = $productImprintMethod->getPrice();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['charges'][$productImprintMethod->getDisplayType()][$productImprintMethod->getImprintChargeName()][$counter]['code'] = $productImprintMethod->getCode();

  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['postion']['name'] = $productImprintMethod->getImprintPostionName();
  $imprintMethodWiseData[$productImprintMethod->getImprintMethodId()]['postion']['area'] = $productImprintMethod->getImprintPostionArea();


  $counter++;
}

?>      
<?php if(sizeof($regularPriceCollection->getData())) : ?>
  <?php if ($productRegularPriceType->getPriceType() != 'call_for_price') : ?>
    <table style="width: 100%;">
      <tbody>
        <tr>
          <td>
            <p style="color: #606c77; font-family: Verdana,Geneva,sans-serif; font-weight: bold; font-size: 15px; padding-top: 20px; margin:0 0 5px; ">Pricing</p>
          </td>
        </tr>
        <tr>
          <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #606c77; padding-bottom: 10px; font-style: italic; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">Quantity</th>
          <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
            <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: bold; color: #606c77; padding-bottom: 10px; text-align: center; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">
              <?php if (!empty($regularPriceData->getQtyStart())) : ?>
                <?php echo $regularPriceData->getQtyStart() ?>
              <?php endif; ?>
              <?php if (!empty($regularPriceData->getQtyEnd())) : ?>
                <?php echo '-'.$regularPriceData->getQtyEnd() ?>
                <?php else : ?>
                  <?php echo '+' ?>
                <?php endif; ?>
              </th>
            <?php endforeach; ?>
          </tr>
          <tr>
            <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #606c77; padding-bottom: 10px; font-style: italic; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">Price</th>
            <?php foreach ($regularPriceCollection as $regularPriceData) : ?>
              <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #009ad7; padding-bottom: 10px; text-align: center; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">
                <?php echo $priceHelper->currency($regularPriceData->getDecorativePrice(), true, false); ?>
                <?php 
                if ($regularPriceData->getDecorativePriceCode() && !empty($regularPriceData->getDecorativePriceCode())) {
                  echo '('.$regularPriceData->getDecorativePriceCode().')';
                }
                ?>
              </th>
            <?php endforeach; ?>
          </tr>
        </tbody>
      </table>
    <?php endif; ?>
  <?php endif; ?>

  <?php if(sizeof($imprintMethodWiseData)) : ?>
    <?php $newChargesArray = array() ?>
    <?php foreach($imprintMethodWiseData as $imprintId => $proImprintMethodData) : ?>
      <?php if(isset($proImprintMethodData['charges'][2])) : ?>
        <?php $newChargesArray[$proImprintMethodData['name']] = $proImprintMethodData['charges'][2]; ?>
      <?php endif; ?>
    <?php endforeach; ?> 
    <?php $countofcharges = 1 ?>
    <?php foreach($newChargesArray as $imprintName => $imprintChargesArray) : ?>
      <?php if($countofcharges == 1) : ?>
        <table style="width: 100%;">
          <tbody>
            <tr>
              <td>
                <p style="color: #606c77; font-family: Verdana,Geneva,sans-serif; font-weight: bold; font-size: 15px; padding-top: 20px; margin:0 0 5px; ">Pricing</p>
              </td>
            </tr>
          </tbody>
        </table>
      <?php endif; ?>
      <table style="width: 100%;">
        <tbody>
          <tr>
            <td>
              <p style="margin-bottom: 0;"><strong style="color: #606c77; font-family: Verdana,Geneva,sans-serif;"><?php echo $imprintName  ?></strong></p>
            </td>
          </tr>
        </tbody>
      </table>
      <table style="width: 100%;">
        <tbody>
          <?php foreach($imprintChargesArray as $charageName => $charageData) : ?>
            <tr>
              <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #606c77; padding-bottom: 10px; font-style: italic; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">Quantity</th>
              <?php foreach($charageData as $key => $charageRecord) : ?>
                <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #606c77; padding-bottom: 10px; text-align: center; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">
                  <?php
                  if (isset($charageRecord['qty_start']) && !empty($charageRecord['qty_start']))
                    echo $charageRecord['qty_start'];

                  if (isset($charageRecord['qty_end']) && !empty($charageRecord['qty_end']))
                    echo '-'.$charageRecord['qty_end'];
                  else
                    echo "+";
                  ?>
                </th>
              <?php endforeach; ?>
            </tr>
            <?php break; ?>
          <?php endforeach; ?>
          <?php foreach($imprintChargesArray as $charageName => $charageData) : ?>
            <tr>
              <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #606c77; padding-bottom: 10px; font-style: italic; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px;"><?php echo $charageName ?></th>
              <?php foreach($charageData as $key => $charageRecord) : ?>
                <th style="border-top: #e1e1e1 2px solid; font-family: verdana,geneva,sans-serif; border-right: #e1e1e1 2px solid; border-bottom: #e1e1e1 2px solid; font-weight: normal; color: #009ad7; padding-bottom: 10px; text-align: center; padding-top: 10px; padding-left: 15px; border-left: #e1e1e1 2px solid; padding-right: 15px">
                  <?php
                  if(isset($charageRecord['price']) && !empty($charageRecord['price']))
                    echo $priceHelper->currency($charageRecord['price'], true, false);
                  if(isset($charageRecord['code']) && !empty($charageRecord['code']))
                    echo '('.$charageRecord['code'].')';
                  ?>
                </th>
              <?php endforeach; ?>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <?php $countofcharges++; ?>
    <?php endforeach; ?>
    <?php endif; ?>