<?php

/**
 * @category   Biztech
 * @package    Biztech_BackgroundPatterns
 * @author     developer1.test@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Biztech\BackgroundPatterns\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface {

    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context) {
        $installer = $setup;
        $installer->startSetup();

        /**
         * Add column is_pattern in productdesigner_clipart table 
         */
        if ($installer->tableExists($installer->getTable('productdesigner_clipart'))) {
            $clipartTable = $installer->getTable('productdesigner_clipart');
            $installer->getConnection()->addColumn($clipartTable, 'is_pattern', [
                'type' => \Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
                'length' => 6,
                'nullable' => false,
                'default' => 0,
                'comment' => 'Is pattern'
            ]);
        }
        $installer->endSetup();
    }

}
