<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');?>
<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $image_hover = 'product_base_image'; ?>
<?php $lazyLoad = $this->getLazyLoad(); ?>
<?php $lazyImg = $this->getLazyLoadBaseImage(); ?>
<?php $change_img = $themeHelper->getStoreConfig('mpanel/catalog/hover_change'); ?>
<?php $iamges_silder = $themeHelper->getStoreConfig('mpanel/catalog/iamges_silder'); ?>
<?php $hover = $themeHelper->getStoreConfig('mpanel/catalog/hover'); ?>

<?php $padding = "133.33333%"; ?>
<?php $ratio = $themeHelper->getStoreConfig('mpanel/catalog/picture_ratio');?>
<?php if($this->getRatio()) $ratio = $this->getRatio(); ?>
<?php
    if($ratio == 1){ $padding = "100%"; }
    if($ratio == 2){ $padding = "200%"; }
    if($ratio == 3){ $padding = "150%"; }
    if($ratio == 4){ $padding = "133.33333%"; }
    if($ratio == 5){ $padding = "50%"; }
    if($ratio == 6){ $padding = "66.66667%"; }
    if($ratio == 7){ $padding = "75%"; }
?>

<div class="content-block deal-product-cat-block">
    <?php if($this->hasData('mgs_panel_title') || $this->hasData('mgs_panel_note')): ?>
    <div class="content-heading">
        <?php if($this->hasData('mgs_panel_title')): ?>
        <h2 class="title">
            <?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?>
        </h2>
        <?php endif ?>
        <?php if($this->hasData('mgs_panel_note')): ?>
        <div class="block-note">
            <?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?>
        </div>
        <?php endif ?>
    </div>
    <?php endif ?>

    <?php if (count($_productCollection)>0): ?>

    <?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>

    <div class="block widget mgs-products deal-products-grid products-grid<?php if($useSlider): ?> row<?php endif ?>">
        <div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>" id="deal-products<?php echo $blockId; ?>">
            <?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
            <?php $productUrl = $_product->getProductUrl(); ?>
            <?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
            <?php if ($j++ % $columnCount == 0): ?>
            <div class="item">
                <?php endif ?>
                <?php endif ?>
                <div class="<?php if(!$useSlider || $this->getNumberRow()==1): ?>item <?php else: ?><?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?> <?php endif ?>product product-item<?php if(!$useSlider): ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                    <div class="product-item-info <?php if($hover != " ") echo __('effect'); ?> <?php if($hover == "2 ") echo __('effect-2'); ?>" data-container="product-grid">
                        <?php
                                $size = $this->getSize();
                                $productImageFirst = $productImage = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
                                $productImageSmall = $_imagehelper->init($_product, 'product_small_image')->resize($size['width'], $size['height'])->getUrl();
                                $productThumbnail = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
                                $productImageBase = $_imagehelper->init($_product, 'product_base_image')->resize($size['width'], $size['height'])->getUrl();
                                if($change_img){
                                    $productImageHoverFirst = $productThumbnail;
                                }
                                if($lazyLoad){
                                    $productImageFirst = $productImageHoverFirst = $lazyImg;
                                }
                            ?>
                             <div class="product-item-image<?php if($lazyLoad): ?> lazy-img<?php endif ?>">
                                <?php if($iamges_silder): ?>
                                <div class="owl-carousel list_gallery">

                                    <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
                                        <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productImageBase ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy product-image-photo" data-src="<?php echo $productImageBase ?>" /></a>

                                    <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
                                    <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
                                        <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productThumbnail ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy" data-src="<?php echo $productThumbnail ?>" /></a>
                                    <?php endif;?>

                                    <?php if((basename($_product->getData('small_image')) != basename($_product->getData('image'))) && (basename($_product->getData('small_image')) != basename($_product->getData('thumbnail')))): ?>
                                    <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
                                        <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productImageSmall ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy" data-src="<?php echo $productImageSmall ?>" /></a>
                                    <?php endif;?>
                                </div>

                                <?php else:?>

                                <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
                                    <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
                                    <img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy product-image-photo" data-src="<?php echo $productImageBase ?>" />
                                    <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
                                    <img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid img-hover-show lazy" data-src="<?php echo $productThumbnail ?>" />
                                    <?php endif;?>
                                </a>

                                <?php endif;?>
                                <span class="product-image-photo"></span>
                                <?php // Product Label ?>
                                <?php echo $themeHelper->getProductLabel($_product) ?>

                                <?php if ($_product->isSaleable()): ?>
                                <div class="actions-primary">
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                        <button class="action tocart primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>

                                    </form>

                                </div>
                                <?php endif; ?>

                            </div>
                            <div class="product details product-item-details">

                                <ul class="product actions product-item-actions">
                                    <?php if ($_product->isSaleable() && ($hover == "")): ?>
                                    <li class="actions-primary">
                                        <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                            <button class="action tocart primary" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>

                                        </form>
                                        <?php endif; ?>
                                    </li>
                                    <?php endif;?>
                                    <li data-role="add-to-links" class="actions-quickview">
                                        <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                        <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
                                    </li>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                    <li data-role="add-to-links" class="action-wishlist">
                                        <button class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-title="<?php echo __('Add to Wish List') ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
												<span class="icon"></span>
											</button>
                                    </li>
                                    <?php endif; ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <?php if(!$themeSettings['catalog']['compare_button']): ?>
                                    <li data-role="add-to-links" class="actions-compare">
                                        <button class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-title="<?php echo __('Add to Compare') ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
												<i class="ion-ios-shuffle-strong"></i>
											</button>
                                    </li>
                                    <?php endif ?>
                                </ul>
                                <?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
                                <h5 class="product name product-item-name">
                                    <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h5>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                            </div>
                    </div>
                </div>
                <?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
                <?php if ($j % $columnCount == 0 || $j == count($_productCollection)): ?>
            </div>
            <?php endif ?>
            <?php endif ?>
            <?php endforeach; ?>
        </div>

        <?php if($useSlider): ?>
        <?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
        <?php $perRow = 1; ?>
        <?php endif ?>
        <script type="text/javascript">
            require([
                'jquery',
                'mgs/owlcarousel'
            ], function($) {
                $('#deal-products<?php echo $blockId ?>').owlCarousel({
                    items: <?php echo $perRow; ?>,
                    autoplay: <?php echo $autoPlay ?>,
                    autoplayHoverPause: <?php echo $stopAuto ?>,
                    nav: <?php echo $nav ?>,
                    dots: <?php echo $dot ?>,
                    navText: ["<i class='fa fa-arrow-left'></i>", "<i class='fa fa-arrow-right'></i>"],
                    <?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
                    responsive: {
                        0: {
                            items: 1
                        },
                        480: {
                            items: 2
                        },
                        768: {
                            items: <?php echo $perRow; ?>
                        }
                    }
                    <?php endif ?>
                });
            });
        </script>

        <?php endif ?>
    </div>
    <?php else: ?>
    <div role="alert" class="alert alert-warning">
        <?php echo __('There are no deals matching the selection.') ?>
    </div>
    <?php endif ?>
</div>