<?php
/* @var $block \Magento\Framework\View\Element\Template */
?>
<?php
    $cartSummary = $block->getCartSummary();
    $cartSummaryText = $cartSummary == 1 ? __('item') : __('items');
?>
<div class="ajax_cart-popup popup__columns">
	<div class="ajax_header">
		<span><?php echo __('1 Item added to your cart'); ?></span>
		<div class="action-close popup__action-close"><span class="pe-7s-close"></span></div>
	</div>
	<div class="popup__column">
		<div class="popup__table">
			<div class="popup__table-col">
				<div class="popup__column--media">
					<?php echo $block->getChildHtml('product_image') ?>
				</div>
			</div>
		   <div class="popup__table-col">
				<div class="popup__column--result">
					<div class="product-confirm-detail">
						<div class="product-confirm-name"><?php echo $this->getProductName() ?></div>
						<div class="product-confirm-qty"><span class="title"><?php echo __('Quantity') ?></span><span class="value"><?php echo $this->getProductQty() ?></span></div>
						<div class="product-confirm-subtotal"><span class="title"><?php echo $block->escapeHtml(__('Cart Subtotal')) ?></span><span class="value"><?php /* @noEscape */ echo $block->getCartSubtotal() ?></span></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="ajax_footer">
		<div class="actions">
			<a class="btn btn-primary popup__action-close btn-close" href="javascript:void(0);"><?php echo __('Continue Shopping'); ?></a>
			<?php if($block->getIsCart()): ?>
				<button class="btn btn-tocart btn-secondary" type="button" onclick="setLocation('<?php echo $block->getUrl('checkout/cart') ?>');"><?php echo $block->escapeHtml(__('Proceed to Cart')) ?></button>
			<?php endif ?>
		</div>
	</div>
	<script>
		require(["jquery"], function ($) {
			jQuery(document).ready(function() {
				
				jQuery('.mfp-mgs-quickview-frame').addClass('success-ajax--popup');
				jQuery('.success-ajax--popup').removeClass('mfp-mgs-quickview-frame');
				
				jQuery('.popup__action-close').click(function(){
					jQuery('.mfp-close').trigger('click');
				});
				jQuery('.popup__result-view-cart').click(function(){
					var url_cart_update = '<?php echo $this->getUrl('ajaxcart/index/updatecart')?>';
					jQuery.ajax({
						url: url_cart_update,
						method: "POST"
					});
					window.location.href = jQuery(this).attr('data-href');
				})
				jQuery('.popup__action-redirect--checkout').click(function(){
					var url_cart_update = '<?php echo $this->getUrl('ajaxcart/index/updatecart')?>';
					jQuery.ajax({
						url: url_cart_update,
						method: "POST"
					});
					window.location.href = jQuery(this).attr('data-href');
				})
			});

		});
	</script>
</div>