<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();

$ii = 0; 
?>

<div class="panel-group faqs-section" id="accordion">
	<h2>Frequently Asked Questions</h2>
	<?php foreach($this->getTopics() as $topic) { ?>
		<?php foreach($this->getQasByTopicIdLimited($topic['id']) as $qa) {  ?>
			<?php //echo <pre>'; print_r($qa); echo '</pre>'; ?>
			<?php $ii++; ?>
			<?php if($ii<=100){ ?>
				<?php if($qa['showing_service'] == 'yes') { ?>
					<div class="panel panel-default">
				        <div class="panel-heading">
				            <h4 class="panel-title">
				                <a class="accordion-toggle collapsed <?php echo ($ii==1)?'':'collapsed'; ?>" data-toggle="collapse" data-parent="#accordion" href="#collapseOne-<?php echo $ii; ?>" aria-expanded="<?php echo ($ii==1)?'true':'false'; ?>">
				                    <?php echo $qa['question']; ?>
				                </a>
				            </h4>
				        </div>
				        <div id="collapseOne-<?php echo $ii; ?>" class="panel-collapse collapse <?php echo ($ii==1)?'':''; ?>">
				            <div class="panel-body">
				                <?php echo $qa['answer_summary']; ?>
				            </div>
				        </div>
					</div>
				<?php } ?>
			<?php } ?>
		<?php } ?>
	<?php } ?>
	<div class="faq-bottom-section">
	    <div class="see-all-faq">
	       <a href="<?php echo $baurl; ?>faqs">SEE ALL FAQs</a>
	    </div>
	    <div class="faq-contactus">
	        <p>Haven’t Found What You’re Looking For?<a href="<?php echo $baurl; ?>contact">Contact Us</a></p>
	    </div>
	</div>
</div>


<style type="text/css">
	.customer-service .faqs-section{
		padding: 0px;
	}
</style>