<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $onLoad = $themeHelper->getStoreConfig('mpanel/newsletter_popup/enable_newsletter'); ?>
<?php $onHeader = $themeHelper->getStoreConfig('mgstheme/header/newsletter_link'); ?>
<?php if($onLoad || $onHeader): ?>

	<?php 
		$html = $themeHelper->getStoreConfig('mpanel/newsletter_popup/html');
		$title = $themeHelper->getStoreConfig('mpanel/newsletter_popup/title');
		$delayTime = $themeHelper->getStoreConfig('mpanel/newsletter_popup/popup_delay');
        
		$image = "";
		if($themeHelper->getStoreConfig('mpanel/newsletter_popup/background_title')) {
			$image = $themeHelper->getMediaUrl().'bg_newsletter/'.$themeHelper->getStoreConfig('mpanel/newsletter_popup/background');
		}
		
		$widthConfig = $themeHelper->getStoreConfig('mpanel/newsletter_popup/popup_width'); 
		$width = $widthConfig ? $widthConfig : '970';
	?>
    
    <div class="newsletter_popup mfp-with-anim mfp-hide" id="newsletter-popup" style="width: <?php echo $width; ?>px;">
        <div class="block-popup-subscribe">
            <div class="block-popup-top" >
                <img src="<?php if($image) echo $image;?>" alt="" />
                <h6 class="color-primary">Newsletter</h6>
            </div>
            <div class="block-popup-content">
                <?php if($title): ?>
                    <div class="pop-sletter-title">
                        <h2><?php echo $title; ?></h2>
                    </div>
                <?php endif ?>
                
                <?php if($html): ?>
                    <div class="newsletter-popup-content">
                        <?php echo $html; ?>
                    </div>
                <?php endif ?>

                <div class="newsletter-popup-form inline-newsletter">
                    <?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe_popup.phtml")->toHtml(); ?>
                </div>

                <div class="checkbox field choice dont-show">
                    <input id="dont_show" onclick="dontShowPopup('dont_show')" type="checkbox">
                    <label for="dont_show"><?php echo __("Don't show this popup again");  ?></label>
                </div>

            </div>
        </div>
    </div>
        
	<script type="text/javascript">
			require(
			[
				'jquery',
				'magnificPopup'
			],
			function( $, modal ) {
				<?php if($onLoad): ?>
				$(window).load(function () {
					if($(window).width() > 991) {
						if(getCookie('newsletterpopup')!='nevershow'){
                            <?php if($delayTime): ?>
                                setTimeout(function(){ 
                                    $.magnificPopup.open({
                                        items: {
                                            src: '#newsletter-popup' 
                                        },
                                        type: 'inline',
                                        removalDelay: 300,
                                        callbacks: {
                                            beforeOpen: function() {
                                                this.st.mainClass = 'mfp-zoom-out modal_newsletter_popup';
                                            }
                                        }
                                    });
                                }, <?php echo $delayTime ?>);
                            <?php else: ?>
                                $.magnificPopup.open({
                                    items: {
                                        src: '#newsletter-popup' 
                                    },
                                    type: 'inline',
                                    removalDelay: 300,
                                    callbacks: {
                                        beforeOpen: function() {
                                            this.st.mainClass = 'mfp-zoom-out modal_newsletter_popup';
                                        }
                                    }
                                });
                            <?php endif ?>
						}
					}
				});
				<?php endif ?>
				
				$('.newsletter-link .newsletter-action').click(function(){
					$.magnificPopup.open({
						items: {
							src: '#newsletter-popup' 
						},
						type: 'inline',
						removalDelay: 300,
						callbacks: {
							beforeOpen: function() {
								this.st.mainClass = 'mfp-zoom-out modal_newsletter_popup no_checkbox';
							}
						}
					});
				});
			});
			function getCookie(cname) {
				var name = cname + "=";
				var ca = document.cookie.split(';');
				for(var i=0; i<ca.length; i++) {
					var c = ca[i];
					while (c.charAt(0)==' ') c = c.substring(1);
					if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
				}
				return "";
			} 

			function dontShowPopup(el){
				require(
				[
					'jquery'
				],
				function( $ ) {
					if($('#'+el).prop('checked')) {
						var d = new Date();
						d.setTime(d.getTime() + (24*60*60*1000*365));
						var expires = "expires="+d.toUTCString();
						document.cookie = 'newsletterpopup' + "=" + 'nevershow' + "; " + expires;
					} else {
						document.cookie = 'newsletterpopup' + "= ''; -1";
					}
				});
			}
	</script>
<?php endif ?>