<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

<script type="text/javascript">
    requirejs(['jquery', 'mgs_quickview'],
		function ($, quickview) {
			$(document).ready(function () {
				var ratioImage = $('body').attr('data-ratio');
				$('.mgs-quickview').bind('click', function () {
					var prodUrl = $(this).attr('data-quickview-url');
					if (prodUrl.length) {
						quickview.displayContent(prodUrl, ratioImage);
					}
				});
			});
		});
</script>
