<div class="container">
    <div class="feacture-section">
        <h2 class="main-title">FEATURED IMPRINT METHODS</h2>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/sweda/feacture-1.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>CHISEL IT</h3>
                <p>Digital chisel method for drinkware items; Chiseled logo reveals brilliant stainless steel
                    underneath.</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/sweda/feacture-2.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>IT’S A WRAP</h3>
                <p>It’s A Wrap can be matched to your brand! Add your logo to any It’s A Wrap design for a truly custom
                    product </p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/sweda/feacture-3.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>SPECTRUM </h3>
                <p>Full color digital printing directly onto your product. Add your brand to drinkwear, writing
                    instruments and more! </p>
            </div>
        </div>
    </div>
    <div class="feacture-view-all">
        <a href="#">VIEW ALL OUR IMPRINT METHODS</a>
    </div>
</div>