<div class="container">
    <div class="solution-section solution-banner">
        <div class="row">
            <div class="col-sm-8">
                <div class="solution-content">
                    <h3>THE<strong> SHIP SAVER </strong>SOLUTION </h3>
                    <p><strong>Ship and Save with SWEDA!</strong>Experience ground shipping at FOB Memphis <br> rates
                        for orders shipping to FedEx zones 7 & 8</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="solution-btn">
                    <a href="#">Learn More</a>
                </div>
            </div>
        </div>
    </div>
</div>