<div class="container-fluide back-img">
    <div class="container">
        <div class="smart-project-section">
            <div class="row">
                <div class="col-md-12">
                    <div class="project-title">
                        <h2>READY. SET. GO!</h2>
                        <p>Start your project today!</p>
                    </div>
                </div>
            </div>
            <div class="option-section">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>Type Of Product</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                        <!--   <div class="arrow-icon">
                          </div> -->
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>What’s Your Budget?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>How Many Do You Need?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>When Do You Need It?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>


                    <div class="project-btn">
                        <a href="#">Show Me What’s Available!</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>