<div class="container-fluide news-letter-banner">
    <div class="news-letter-text">
        <h3>SIGN UP FOR OUR NEWSLETTER</h3>
        <p>Subscribe to the SWEDA mailing list to recieve <br>the latest news and special offers</p>
        <div class="Subscribe-section">
            <input type="text" class="search-query form-control" placeholder="Enter Your Email Address">
            <span class="news-section-btn">
                  <button type="button" disabled="">
                     <p>subscriber</p>
                  </button>
               </span>
        </div>
    </div>
</div>