<div class="container">
    <div class="usefull-section desktop-only">
        <h2 class="main-title">Useful Tools</h2>
        <div class="row">
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-1.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-2.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-3.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-4.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="bottom-section">
            <div class="row">
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-5.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-6.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-7.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/sweda/usefull-img-8.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>