<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

        <form class=""
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail-footer"
            class="search-query form-control">

            <div class="Subscribe-section">
                    <input class="search-query form-control" name="email" type="email" id="newsletter-footer"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter Your Email Address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                    <span class="news-section-btn">
                        <button title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                            <p><?php echo __('Subscribe') ?></p>
                        </button>
                    </span>
            </div>

        </form>

