<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-popup">
			<div class="form-wrapper">
				<div class="field newsletter">
					<div class="control">
						<input name="email" type="email" id="newsletter_popup"
									placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
					</div>
				</div>
				<div class="actions">
					<button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
						<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
						<i class="ti-arrow-right"></i>
					</button>
				</div>
			</div>
			<?php if($themeHelper->getStoreConfig('gdpr/general/active') && $themeHelper->getStoreConfig('gdpr/newsletter/active')): ?>
				<div class="field choice mgs-gdpr-checkbox">
					<input name="login[accept_gdpr]" value="1" id="accept_gdpr" class="checkbox" type="checkbox" data-validate="{required:true}"/>
					<label for="accept_gdpr" class="label"><span><?php echo $themeHelper->getStoreConfig('gdpr/newsletter/label');  ?></span></label>
				</div>
			<?php endif ?>
        </form>
    </div>
</div>
