<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
    /** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
    /** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
    $filterUniqId = $block->escapeId(uniqid());
    $filterCode = $block->escapeHtml($filterSetting->getFilterCode());
?>
<form data-amshopby-filter="<?= /* @noEscape */ $filterCode; ?>"
      data-amshopby-filter-request-var="<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>"
        <?php if ($filterSetting->getEnableOverflowScroll() > 0) : ?>
            style="max-height:<?= /* @noEscape */ $filterSetting->getEnableOverflowScroll() ?>px;
            overflow-y: auto;
            overflow-x: hidden;"
        <?php endif; ?>>
            <ul class="items am-filter-items-<?= /* @noEscape */ $filterCode; ?> amshopby-fly-out-view">
                <?= /* @noEscape */ $categoryTreeHtml; ?>
            </ul>
</form>
<script>
    require(["jquery", "jquery/ui"], function ($) {
        $(window).load( function(){
            $(document).trigger('baseCategory', <?= /* @noEscape */ $block->getCurrentCategoryId();?>);
            addFlyOut();
        });
        $(document).ajaxComplete( function(){
            addFlyOut();
            $(document).trigger('baseCategory', <?= /* @noEscape */ $block->getCurrentCategoryId();?>);
        });

        function addFlyOut() {
            $(".am-filter-items-<?= /* @noEscape */ $filterCode;?>").menu({
                position: { my: "left top", at: "center top+20" }
            });
        }
    });
</script>
