<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php $_product = $this->getProduct(); ?>
<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $quickViewHelper = $this->getQuickViewHelper(); ?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $image = 'category_page_grid'; ?>
<?php $image_hover = 'product_base_image'; ?>
<?php $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW; ?>
<?php $change_img = $this->getHoverChange(); ?>
<?php $lazyLoad = $this->getLazyLoad(); ?>
<?php $lazyImg = $this->getLazyLoadBaseImage(); ?>
<?php $iamges_silder = $themeHelper->getStoreConfig('mpanel/catalog/iamges_silder'); ?>


<?php 
/* Product Data */
$productUrl = $_product->getProductUrl();
?>
<div class="product-item-info" data-container="product-grid">
    <?php
        $size = $this->getSize();
        $productImageFirst = $productImage = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
        $productImageSmall = $_imagehelper->init($_product, 'product_small_image')->resize($size['width'], $size['height'])->getUrl();
        $productThumbnail = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
        $productImageBase = $_imagehelper->init($_product, 'product_base_image')->resize($size['width'], $size['height'])->getUrl();
        if($change_img){
            $productImageHoverFirst = $productThumbnail;
        }
		if($lazyLoad){
			$productImageFirst = $productImageHoverFirst = $lazyImg;
		}
    ?>
    <?php // Product Image ?>
    
    <?php  
        $images = $_product->getMediaGalleryImages();
        print_r($images);
    ?>
    
    <div class="product-item-image">
		<div class="product-item-image-wrapper<?php if($lazyLoad): ?> lazy-img<?php endif ?>">
            <?php if($iamges_silder): ?>
               <div class="owl-carousel list_gallery">

                   <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $this->getPadding(); ?>;" class="product photo product-item-photo" tabindex="-1">
                   <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productImageBase ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy product-image-photo" data-src="<?php echo $productImageBase ?>"/></a>

                   <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
                       <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $this->getPadding(); ?>;" class="product photo product-item-photo" tabindex="-1">
                       <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productThumbnail ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy" data-src="<?php echo $productThumbnail ?>"/></a>
                   <?php endif;?>

                   <?php if((basename($_product->getData('small_image')) != basename($_product->getData('image'))) && (basename($_product->getData('small_image')) != basename($_product->getData('thumbnail')))): ?>
                       <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $this->getPadding(); ?>;" class="product photo product-item-photo" tabindex="-1">
                       <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?><img src="<?php echo $productImageSmall ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy" data-src="<?php echo $productImageSmall ?>"/></a>
                   <?php endif;?>
                </div>

            <?php else:?>

              <a href="<?php echo $productUrl ?>" style="padding-bottom: <?php echo $this->getPadding(); ?>;" class="product photo product-item-photo" tabindex="-1">
                   <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
                   <img src="<?php echo $productImageFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid lazy product-image-photo" data-src="<?php echo $productImageBase ?>"/>
                   <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
                      <img src="<?php echo $productImageHoverFirst ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid img-hover-show lazy" data-src="<?php echo $productThumbnail ?>"/>
                   <?php endif;?>
               </a>

            <?php endif;?>
            <?php // Product Label ?>
		    <?php echo $themeHelper->getProductLabel($_product) ?>
		    <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
		</div>
    </div>
    <div class="product details product-item-details">
        <h5 class="product name product-item-name">
            <a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $productUrl ?>">
                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
            </a>
        </h5>
		<?php echo $this->getReview(); ?>
		
		<?php echo $this->getPrdPrice() ?>
		
		<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTextSwatch($this->getSwatches())->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml(); ?>
        
		<?php if($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')): ?>
		<div class="product std description product-item-description">
			<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
		</div>
		<?php endif ?>
		
		<div class="product actions product-item-actions">
			<?php if ($_product->isSaleable()): ?>
				<div class="actions-primary<?php if(!$this->getCompare()): ?> no-compare<?php endif ?>">
					<?php $postParams = $this->getPostParams(); ?>
					<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
						<?php echo $this->getFk(); ?>
						<button type="submit"
								title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
								class="action tocart btn-third">
							<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
						</button>
					</form>
				</div>
			<?php endif; ?>
			<?php if ($this->getWishList()): ?>
                <div data-role="add-to-links" class="action-wishlist">
                    <a href="#"
                       class="action towishlist"
                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                       data-post='<?php /* @escapeNotVerified */ echo $this->getWishListPost(); ?>'
                       data-action="add-to-wishlist"
                       role="button">
                        <span class="icon"></span>
                    </a>
                </div>
		    <?php endif; ?>
			<?php if($this->getCompare()): ?>
			<div data-role="add-to-links" class="actions-compare">
				<a href="#"
				   class="action tocompare"
				   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				   role="button">
					<i class="ion-ios-shuffle-strong"></i>
				</a>
			</div>
			<?php endif ?>
		</div>
    </div>
</div>