<?php
$brand = $block->getCurrentBrand();
$img = '';
if ($img = $brand->getImageUrl()) { ?>

<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank6.png'); ?>
	<?php 
		if(!$lazyLoad){
			$baseImage = $img;
		}
	?>
    <div class="brand-image <?php if($lazyLoad): ?> lazy-img <?php endif ?>">
        <img class="img-fluid lazy" src="<?php echo $baseImage; ?>" data-src="<?php echo $img; ?>" alt="<?php echo $brand->getName(); ?>" class="image"/>
    </div>
	
<?php } ?>