<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
?>

<?php $postfix = uniqid();?>
<?php $filterCode = $block->escapeHtml($filterSetting->getFilterCode()); ?>
<?php $max = $block->escapeHtml(ceil($fromToConfig['max']))?>
<?php $min = $block->escapeHtml(floor($fromToConfig['min']))?>

<form class="am-ranges"
      data-am-js="ranges"
      data-amshopby-filter="<?= $block->escapeHtml($filterCode);?>"
      data-amshopby-filter-request-var="<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>"
      autocomplete="off">
    <ol class="items am-filter-items-<?= /* @noEscape */ $filterCode;?>"
        <?php if ($filterSetting->getEnableOverflowScroll() > 0) : ?>
            style="max-height:<?= $block->escapeHtml($filterSetting->getEnableOverflowScroll()) ?>px;"
        <?php endif; ?>>
        <?php /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */?>
        <?php foreach ($filterItems as $filterItem) : ?>
            <?php $optionLabel = $filterItem->getOptionLabel(); ?>
            <?php $inputType = !$filterSetting->isMultiselect() ||
            in_array($filterCode, ['rating', 'stock']) ? 'radio' : 'checkbox'?>
        <li class="item" data-label="<?= $block->escapeHtml($optionLabel)?>">
            <?php if ($filterItem->getCount() >= 0) : ?>

                <?php $style = ($inputType == 'radio' && !$block->getRadioAllowed())
                || in_array($filterCode, ['rating', 'stock'])  ? 'display: none;' : ''; ?>
                <input
                        name="amshopby[<?= /* @noEscape */ $block->getFilter()->getRequestVar();?>][]"
                        value="<?= $block->escapeHtml($filterItem->getValueString());?>"
                        type="<?= /* @noEscape */ $inputType;?>"
                        style="<?= /* @noEscape */ $style ?>"
                    <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                />

                <a
                    class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid())?>"
                    data-am-js="filter-item-default"
                    href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?= /* @noEscape */ $filterSetting->isAddNofollow() ? ' rel="nofollow"' : '' ?>
                >

                    <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                    <?php if ($filterSetting->isShowProductQuantities()) : ?>
                        <?php //Delete spaces around counter ?>
                        <span class="count">(<?= /* @noEscape */ $filterItem->getCount()?>)</span>
                    <?php endif; ?>
                </a>
            <?php else :?>
                <span class="label"><?= /* @noEscape */ $optionLabel;?></span>
                <?php if ($filterSetting->isShowProductQuantities()) : ?>
                    <?php //Delete spaces around counter ?>
                    <span class="count"><?= /* @noEscape */ '('.$filterItem->getCount().')' ?><!--<span class="filter-count-label">
                            <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?><?= $block->escapeHtml($title) ?></span>--></span>
                <?php endif; ?>
            <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
</form>

<div class="items am-filter-items-<?= $block->escapeHtml($filterCode); ?>">
    <form data-amshopby-filter="<?= $block->escapeHtml($filterCode); ?>"
          data-amshopby-filter-request-var="<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>">
        <div id="am-shopby-filter-<?= $block->escapeHtml($filterCode . '_' . $postfix); ?>"
             class="amshopby-slider-container amshopby_currency_rate"
             data-am-js="slider-container"
             data-min="<?= /* @noEscape */ $min; ?>"
             data-max="<?= /* @noEscape */ $max; ?>"
             data-rate="<?= /* @noEscape */ $fromToConfig['curRate']; ?>">
             <div class="custom-prices">
                 <span class="min_price"></span>
                <span class="max_price"></span>
             </div>
            <input data-amshopby-slider-id="value"
                   type=hidden
                   name="amshopby[<?= $block->escapeHtml($block->getFilter()->getRequestVar())?>][]"/>
            <div data-amshopby-slider-id="slider" class="am-slider"></div>
            <div data-amshopby-slider-id="display"
                 class="amshopby-slider-display"
                 data-am-js="slider-display"></div>
        </div>
    </form>
</div>

<?php if ($filterSetting->getAddFromToWidget()) : ?>
    <?= /* @noEscape */ $block->getFromToWidget('slider') ?>
<?php endif; ?>



<script type="text/x-magento-init">
    {
        "#am-shopby-filter-<?= $block->escapeHtml($filterCode . '_' . $postfix); ?>": {
            "amShopbyFilterSlider": {
                    "collectFilters": <?= /* @noEscape */ $block->collectFilters(); ?>,
                    "template":"<?= $block->escapeHtml($fromToConfig['template']) ?>",
                    "step":<?= /* @noEscape */ $block->escapeHtml(floatval($fromToConfig['step'])) ?>,
                    "from": "<?= /* @noEscape */ $fromToConfig['from']; ?>",
                    "to": "<?= /* @noEscape */ $fromToConfig['to']; ?>",
                    "min":<?= /* @noEscape */ $min; ?>,
                    "max":<?= /* @noEscape */ $max; ?>,
                    "url": "<?= /* @noEscape */ $block->getSliderUrlTemplate(); ?>",
                    "code":"<?= $block->escapeHtml($filterSetting->getAttributeModel()->getAttributeCode()); ?>",
                    "hideDisplay": <?= /* @noEscape */ $filterSetting->getAddFromToWidget() ? "1" : '0'; ?>
                }
        }
    }
</script>