<div class="toolbar-sorter sorter desktop-only">
    <div class="form-item-select">
        <select id="vlibrary_sorter" data-role="sorter" class="sorter-options">
            <option value="date-early">Most Popular</option>
            <!-- <option value="date-recent">Most Popular</option> -->
            <option value="name-atoz">Sort by Name A to Z</option>
            <option value="name-ztoa">Sort by Name Z to A</option>
            <!-- <option value="date-early">Sort by Date Earlier</option> -->
        </select>
    </div>
</div> 