<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>

<?php 
/* Get Theme Config */
$size = $themeHelper->getImageSize();
$ratio = $themeHelper->getRatioCate();
$baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png');
$padding = $themeHelper->getImagePadding();
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
$pageType = 'catalog';
if($this->hasData('page_type')){
	$pageType = $this->getData('page_type');
}
if($pageType == 'catalog'){
	$category = $themeHelper->getCurrentCategory();
	if($category->getPerRow()){
		$perrow = $category->getPerRow();
	}
}elseif($pageType == 'catalogsearch') {
	if($settings['catalogsearch']['per_row']){
		$perrow = $settings['catalogsearch']['per_row'];
	}
}elseif($pageType == 'catalog_brand') {
	if($settings['catalog_brand']['per_row']){
		$perrow = $settings['catalog_brand']['per_row'];
	}
}

$showCompare = $settings['catalog']['compare_button'] ? false : true;
$showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
$hoverChange = $settings['catalog']['hover_change'] ? true : false;
$showReview = $settings['catalog']['review_count'] ? false : true;
$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="category-product-actions">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
       
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateFile = 'MGS_Mpanel::products/product_item/grid/default.phtml';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateFile = 'MGS_Mpanel::products/product_item/list/default.phtml';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <ol class="products items row row-wrapper product-items<?php if($viewMode == 'grid'): ?> row-<?php echo $perrow ?><?php else:?> list<?php endif;?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $swatches = $block->getProductDetailsHtml($_product); ?>
                <?php $wlDataPost = $block->getAddToWishlistParams($_product); ?>
                <?php $fk = $block->getBlockHtml('formkey') ?>
                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                <?php 
					$review = "";
					if($showReview){
						$review = $block->getReviewsSummaryHtml($_product, $templateType); 
					}
				?>
                <?php $prdPrice = $block->getProductPrice($_product) ?>
                
                <li class="item product product-item col">
                    <?php echo $this->getLayout()
                                    ->createBlock('Magento\Framework\View\Element\Template')
                                    ->setProduct($_product)
                                    ->setThemeHelper($themeHelper)
                                    ->setImageHelper($_imagehelper)
                                    ->setCatalogHelperOutput($_helper)
                                    ->setQuickViewHelper($quickViewHelper)
                                    ->setRatio($ratio)
                                    ->setSize($size)
                                    ->setPadding($padding)
                                    ->setLazyLoadBaseImage($baseImage)
                                    ->setCompare($showCompare)
                                    ->setFk($fk)
                                    ->setPostParams($postParams)
                                    ->setReview($review)
                                    ->setPrdPrice($prdPrice)
                                    ->setWishList($showWishList)
                                    ->setWishListPost($wlDataPost)
                                    ->setTemplate($templateFile)
                                    ->setSwatches($swatches)
                                    ->setLazyLoad($lazyLoad)
                                    ->setHoverChange($hoverChange)
                                    ->toHtml(); ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-buttom">
    <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
