<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $currentStoreId = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getId();
                $buttonLabel = $this->helper('Biztech\Productdesigner\Helper\Data')->getConfig('productdesigner/dynamic_message/designit_label', $currentStoreId);
                $isPdEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId());
                $isEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isEnable($currentStoreId);
                $id = $_product->getId();
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product = $obj_product->load($id);

                $product_type = $product->getTypeId();
                $defaultAssociatedProduct = $defaultAssociatedProductId = $templateId = $defaultAssociatedProductTemplateId = "";
                if ($product_type == "configurable") {
                    $defaultAssociatedProductId = $product->getDefaultAssociatedProduct();
                    $defaultAssociatedProduct = $obj_product->load($defaultAssociatedProductId);
                    if (!empty($defaultAssociatedProductId) && !empty($defaultAssociatedProduct->getPreLoadedTemplate())) {
                        $defaultAssociatedProductTemplateId = base64_encode($defaultAssociatedProduct->getPreLoadedTemplate());
                    }
                }
                $productTemplateId = base64_encode($product->getPreLoadedTemplate());
                $product = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProduct : $product;
                $templateId = (!empty($defaultAssociatedProductTemplateId)) ? $defaultAssociatedProductTemplateId : $productTemplateId;
                $design_template = $objectManager->create('Biztech\DesignTemplates\Model\Designtemplates')->load(base64_decode($templateId));
                $template_status = $design_template['status'];
                $templateLink = '';
                if(!empty($templateId) && $template_status == 1){
                    $templateLink = 'template/' . $templateId;
                }

                if (isset($isEnable) && $isEnable) {
                    if (isset($isPdEnable) && $isPdEnable) {
                        ?>
                        <div class="product-page-designer">
                            <?php
                            $designerTitle = $buttonLabel;
                            ?>
                            <button type="button"  title="<?php /* @escapeNotVerified */ //echo $designerTitle    ?>" class="action primary tocart product-designer-button" value="<?php /* @escapeNotVerified */ echo $designerTitle ?>"><?php /* @escapeNotVerified */ echo $designerTitle ?></button>
                        </div>
                        <?php
                    }
                }
                ?>  
            <?php endif; ?>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "#product_addtocart_form": {
    "Magento_Catalog/js/validate-product": {}
    }
    }
</script>
<script>
    require([
        'jquery',
    ], function ($) {
        'use strict';
        $('.product-designer-button').click(function () {
            var designerURL = "<?php echo $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure(), 'id' => $_product->getId())) . $templateLink; ?>";

            var productdata = jQuery("#product_addtocart_form").serializeArray();
            var templateId = "<?php echo $templateId; ?>";
            var templateStatus = "<?php echo $template_status; ?>";
            //create a custom form
            var form = document.createElement("form");
            form.setAttribute('method', "post");
            form.setAttribute('action', designerURL);
            // Create field based on add to cart form field and add in custom form
            var form_data = new FormData();
            jQuery(productdata).each(function (i, data) {
                form_data.append(data.name, data.value);
            });
            var url = "<?php echo $this->getUrl('designtemplates/designtemplates/getTemplateLink'); ?>";
            jQuery.ajax({
                url: url,
                cache: false,
                contentType: false,
                processData: false,
                async: false,
                data: form_data,
                type: 'post',
                dataType: 'json',
                success: function (data)
                {                    
                    if (templateId != "" && templateId != undefined && templateStatus == 1) {
                        var templateUrl = "<?php echo $this->getUrl('productdesigner', array('_secure' => $this->getRequest()->isSecure(), 'id' => $_product->getId())) . 'template/'; ?>" + data.templateId;
                        form.setAttribute('action', templateUrl);
                    }
                    jQuery(productdata).each(function (i, data) {
                        var field = document.createElement("input");
                        field.type = "hidden";
                        field.name = data.name;
                        field.value = data.value;
                        form.appendChild(field);
                    });
                    jQuery("body").append(form);
                    jQuery(form).submit();
                }
            });
        });

    });
</script>
