<?php
$helper = $this->helper('MGS\Brand\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="search detail-page-grid-products">
    <h3 class="title"><?php echo __('Search Brand') ?></h3>
	<div class="search_brand_form">
		<form id="search_brand_form" action="" method="get">
			<div class="control form-group">
					<input id="search_brand"
					   type="text"
					   name="keyword"
					   value="<?php if (isset($params['keyword'])) {
						   echo $params['keyword'];
					   } ?>"
					   placeholder="<?php echo __('Search brand here...'); ?>"
					   class="input-text"
					   autocomplete="off"/>

				<?php if (isset($params['char']) && $params['char'] != ''): ?>
					<input id="search_brand_by_char"
						   type="hidden"
						   name="char"
						   value="<?php echo $params['char']; ?>"/>
				<?php endif; ?>
			</div>
			<div class="actions">	
				<button <?php if (!isset($params['keyword'])): ?> disabled="disabled" type="submit" <?php endif; ?>
						title="<?php echo $block->escapeHtml(__('Search')) ?>"
						class="action btn-primary">
						<span><?php echo __('Search'); ?></span>
				</button>
				
				<?php if (isset($params['keyword']) || isset($params['char'])): ?>
					<a href="<?php echo $helper->getBrandUrl(); ?>"
							title="<?php echo $block->escapeHtml(__('Reset')) ?>"
							class="action btn btn-secondary btn-sm search">
						<span><?php echo __('Reset'); ?></span>
					</a>
				<?php endif; ?>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery'
	], function($){
		$(document).ready(function() {
			$("#search_brand").change(function() {
				if ($(this).val()) {
					$('button[type="submit"]').attr('disabled', false);
				} else {
					$('button[type="submit"]').attr('disabled', true);
				}
			});
		});
	});
</script>