<?php $helper = $this->getHelper() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php
$page_data = [];
$jsonData = "";
if ($this->hasData('apparel_terms')) {
    $jsonData = base64_decode($this->getData('apparel_terms'));
    $page_data = json_decode($jsonData);
    $total = (array)$page_data;
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();

?>

<div class="main-top-title pdp-data-download">
    <div class="breadcrumbs width-5">
        <div class="container">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $baurl; ?>" title="Go to Home Page">Home</a>
                </li>
                <li class="item promostandards">
                    <a href="<?php echo $baurl; ?>tools-landing" title="PromoStandards">Tools</a>
                </li>
                <li style="color:#009ad7;" class="item video-library">Apparel Terms</li>
            </ul>
        </div>
    </div>
    <div class="promo-standards-topic">
        <h2 class="customer-name-title"><?php echo html_entity_decode($page_data->title) ?></h2>
    </div>
</div>

<div class="container">
    <div class="row">
    	<div class="apparel-terms-content">
        	<?php echo html_entity_decode($page_data->description) ?>
    	</div>
    </div>
</div>

<style type="text/css">
.pdp-data-download {
    display: flex !important;
    position: relative !important;
    padding: 0 15px;
}
.main-top-title {
    display: none;
    position: relative;
}
</style>