<?php $helper = $this->getHelper() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php
$page_data = [];
// $jsonData = "";

if ($this->hasData('document_library')) {
    $jsonData = base64_decode($this->getData('document_library'));
    $page_data = json_decode($jsonData);
    $total = (array)$page_data;
    $i = 1;
    $usefulTools = json_decode($page_data->toolsJson);

}
$type = 'document_library';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();



?>

<div class="main-top-title pdp-data-download">
    <div class="breadcrumbs width-5">
        <div class="container">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $baurl; ?>" title="Go to Home Page">Home</a>
                </li>
                <li class="item promostandards">
                    <a href="<?php echo $baurl; ?>pattern-gallery" title="PromoStandards">Tools</a>
                </li>
                <li style="color:#009ad7;" class="item video-library">Document Library</li>
            </ul>
        </div>
    </div>
    <div class="promo-standards-topic">
        <h2 class="customer-name-title"><?php echo strtoupper($page_data->title) ?></h2>
    </div>
</div>

<div class="container">
  <div class="pdp-data-details">
    <?php echo html_entity_decode($page_data->button_title) ?>
  </div>
  <div class="pdp-main-data-download">
        <div class="row mockup-list">
          <?php foreach ($usefulTools as $data): ?>
          <?php 
            $drinkImage = $themeHelper->getImageName($data->drinkImage);
            $drinkImageFinal = $themeHelper->getWysiwygMediaUrl($type,$drinkImage);
            ?>
            <div class="product_data_download">
                <a href="<?php echo $themeHelper->getSwedaFormMediaUrl().$data->drinkUrl ?>" download target="_blank">
                    <img class="download-data" src="<?php echo $drinkImageFinal; ?>">
                    <h3><?php echo $data->drinkTitle ?></h3>
                </a>
            </div>
          <?php endforeach; ?>
        </div>
  </div>
</div>



<style type="text/css">
.main-top-title {
    display: none;
}

</style>