<?php $helper = $this->getHelper() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php
$page_data = [];
// $jsonData = "";

if ($this->hasData('pattern_gallery')) {
    $jsonData = base64_decode($this->getData('pattern_gallery'));
    $page_data = json_decode($jsonData);
    $total = (array) $page_data;
    $i = 1;
    $usefulTools = json_decode($page_data->toolsJson);
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();
$type='pattern_gallery';
?>




<div class="main-top-title pdp-data-download">
    <div class="breadcrumbs width-5">
        <div class="container">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $baurl; ?>" title="Go to Home Page">Home</a>
                </li>
                <li class="item promostandards">
                    <a href="<?php echo $baurl; ?>pattern-gallery" title="PromoStandards">Tools</a>
                </li>
                <li style="color:#009ad7;" class="item video-library">Pattern Library</li>
            </ul>
        </div>
    </div>
    <div class="promo-standards-topic">
        <h2 class="customer-name-title"><?php echo strtoupper($page_data->title) ?></h2>
    </div>
</div>



<div class="container">


    <div class="row mockup-list">
        <?php foreach ($usefulTools as $data) : ?>

            <div class="col-sm-6 col-md-6 col-lg-4">
                <div class="imprint-method-boxs pattern-library">
                    <h3>
                        <?php
                        $PatternUrl = !empty($data->drinkUrl) ? ($data->drinkUrl) : 'javascript:;';
                        if (filter_var($PatternUrl, FILTER_VALIDATE_URL)) {
                            echo '<a href="' . $PatternUrl . '">';
                        } else {
                            echo '<a href=' . $themeHelper->getCurrentBaseUrl() . $PatternUrl . '>';
                        }
                        ?>
                        <?php echo $data->drinkTitle ?></a>
                    </h3>
                    <?php
                    $PatternimgUrl = !empty($data->drinkUrl) ? ($data->drinkUrl) : 'javascript:;';
                    if (filter_var($PatternimgUrl, FILTER_VALIDATE_URL)) {
                        echo '<a href="' . $PatternimgUrl . '">';
                    } else {
                        echo '<a href=' . $themeHelper->getCurrentBaseUrl() . $PatternimgUrl . '>';
                    }
                    ?>
                    <?php
                    $drinkImage = $themeHelper->getImageName($data->drinkImage);
                    $drinkImageFinal = $themeHelper->getWysiwygMediaUrl($type, $drinkImage);
                    ?>
                    <img src="<?php echo $drinkImageFinal; ?>">
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>



<style type="text/css">
    .main-top-title {
        display: none;
        position: relative;
    }
</style>