<?php $helper = $this->getHelper() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php
$page_data = [];
// $jsonData = "";

if ($this->hasData('pattern_gallery_landing_page')) {
    $jsonData = base64_decode($this->getData('pattern_gallery_landing_page'));
    $page_data = json_decode($jsonData);
    $total = (array)$page_data;
    $i = 1;
    $usefulTools = json_decode($page_data->toolsJson);
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();
$type='pattern_gallery_landing_page';
?>

<div class="main-top-title pdp-data-download">
    <div class="breadcrumbs width-5">
        <div class="container">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $baurl; ?>" title="Go to Home Page">Home</a>
                </li>
                <li class="item promostandards">
                    <a href="<?php echo $baurl; ?>pattern-gallery" title="PromoStandards">Pattern Library</a>
                </li>
                <li style="color:#009ad7;" class="item video-library"><?php echo strtoupper($page_data->title) ?></li>
            </ul>
        </div>
    </div>
    <div class="promo-standards-topic landing-pages-head">
        <h2 class="customer-name-title"><?php echo strtoupper($page_data->title) ?></h2>
    </div>
</div>

<div class="container">
  <div class="pdp-data-details">
     <p><?php echo html_entity_decode($page_data->button_title) ?></p>
 </div>
 <div class="row">
    <?php foreach ($usefulTools as $data): ?>
        <div class="col-sm-6 col-md-6 col-lg-4">
            <div class="pattern-library-landing">
                <h3>
                    <?php
                    $PatternLandingUrl = !empty($data->drinkUrl) ? ($data->drinkUrl) : 'javascript:;';
                    ?>
                    <a href="<?=$PatternLandingUrl;?>"><?php echo $data->drinkTitle ?></a>
                </h3>
                <?php
                $PatternLandingimgUrl = !empty($data->drinkUrl) ? ($data->drinkUrl) : 'javascript:;';
                ?>
                <a href="<?=$PatternLandingimgUrl;?>">
                <?php 
                $drinkImage = $themeHelper->getImageName($data->drinkImage);
                $drinkImageFinal = $themeHelper->getWysiwygMediaUrl($type, $drinkImage);
                ?>
                    <img src="<?php echo $drinkImageFinal; ?>">
                </a>
            </div>
        </div>
    <?php endforeach; ?>
</div>
</div>



<style type="text/css">
    .pdp-data-download {
        display: flex !important;
        position: relative !important;
        padding: 0 15px;
    }
    .main-top-title {
        display: none;
        position: relative;
    }
</style>