<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $images = $helper->getPanelUploadImages('aboutus') ?>
<?php $i = 0; ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('About Us') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST"
          action="<?php echo $this->getUrl('mpanel/element/save') ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="aboutus">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">

        <?php if (isset($params['id'])): ?>
            <?php
            try {
                $child = $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>


        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]" value="<?php if ($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active show" id="images-tab-nav" data-toggle="tab" href="#images"><?php echo __('Manage Images') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slide-tab-nav" data-toggle="tab" href="#slide"><?php echo __('Settings') ?></a>
                    </li>
                </ul>
                <div class="tab-content">

                    <div id="images" class="tab-pane active">
                        <div id="list-images">
                            <?php if(count($images)>0): ?>
                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                    <?php
                                    $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                    ?>
                                    <?php
                                    if($ext=="mp4"){ ?>
                                        <div class="image-item" style="width: 120px;height: 70px; margin-right: 10px; margin-bottom: 5px;">
                                            <video class="thumb-video img-fluid" src="<?=$this->getPanelUploadSrc('aboutus',$_image)?>" type="video/mp4" controls="false">
                                                <source src="<?=$this->getPanelUploadSrc('aboutus',$_image)?>" type="video/mp4" />
                                            </video>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } else { ?>
                                        <div class="image-item" style="width: 120px;height: 70px; margin-right: 10px; margin-bottom: 5px;">
                                            <img class="img-fluid" src="<?php echo $this->getPanelUploadSrc('aboutus',$_image) ?>" alt=""/>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } ?>

                                <?php endforeach ?>
                            <?php endif ?>
                        </div>

                        <div id="upload-container">
                            <div id="list-upload"></div>
                            <button class="btn btn-default" onclick="newImageUpload()" type="button"><span class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
                        </div>
                    </div>

                    <div id="slide" class="tab-pane">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button" title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span>
                            </button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>">
                                <span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button" title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <input type="hidden" class="form-control" id="slide_status" value="1"/>
                        <input type="hidden" class="form-control" id="slide_random_number" value="0"/>

                        <div class="form-slide">

                        	<!----------- Section 1 ----------->
                        	<div class="form-group">
                                <label for="slide_link">Title Main:</label>
                                <input type="text" class="form-control" id="title" name="setting[title]" <?php if ($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?>/>
                            </div>

	                        <div class="form-group desktop-view-showing">
	                            <label style="font-weight: bold; color: #000;"><?php echo __('Desktop View Showing'); ?></label>
	                            <a class="remove1 btn btn-info" href="javascript:;">Remove Images</a>

                                <div class="slide_images_wrapper">
	                                <ul id="slide_images" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img-fluid" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url" name="setting[backgroundImage]" <?php if ($exist): ?> value="<?php echo $settings['backgroundImage'] ?>"<?php endif ?> />
	                        </div>
	                        <div class="form-group mobile-view-showing">
	                            <label style="font-weight: bold; color: #000;"><?php echo __('Mobile View Showing'); ?></label>
                                <a class="remove2 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_mobile" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img-fluid" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_mobile" name="setting[backgroundImagemobile]" <?php if ($exist): ?> value="<?php echo $settings['backgroundImagemobile'] ?>"<?php endif ?> />
	                        </div>

	                        <?php /* <div class="form-group">
                                <label style="font-weight: bold; color: #000;"><?php echo __('Video'); ?>:</label>
                                <div class="slide_images_wrapper">
                                    <ul id="slide_video" class="slide-images">
                                        <?php if(count($images)>0): ?>
                                            <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php
                                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext=="ogv" || $ext == "wmv" || $ext=="avi" || $ext == "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <video class="thumb-video  videofluid" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('aboutus',$_image) ?>" type="mp4/video">
                                                            <source src="<?php echo $this->getPanelUploadSrc('aboutus',$_image) ?>"  type="video/mp4">
                                                        </video>
                                                    </li>
                                                <?php }
                                                ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </ul>
                                </div>
                                <input type="hidden" class="form-control" id="slide_img_url_video" name="setting[backgroundImagevideo]" <?php if ($exist): ?> value="<?php echo $settings['backgroundImagevideo'] ?>"<?php endif ?> />
                            </div> */ ?>
	                        <!----------- & Section 1 ----------->

	                        <!-----------  Section 2 ----------->
	                        <div class="form-group">
                                <label for="slide_link">Title WHY OUR CUSTOMERS LOVE US:</label>
                                <input type="text" class="form-control" id="title_why_customers" name="setting[title_why_customers]" <?php if ($exist): ?> value="<?php echo $settings['title_why_customers'] ?>"<?php endif ?>/>
                            </div>
	                        <div class="form-group background-images">
	                            <label style="font-weight: bold; color: #000;"><?php echo __('Background Images'); ?></label>
                                <a class="remove3 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_why_customers" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4;width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_why_customers" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_why_customers" name="setting[main_why_customers]" <?php if ($exist): ?> value="<?php echo $settings['main_why_customers'] ?>"<?php endif ?> />
	                        </div>

	                        <div class="form-group background-images-mobile-view">
	                            <label style="font-weight: bold; color: #000;"><?php echo __('Background Images Mobile View'); ?></label>
                                <a class="remove4 btn btn-info" href="javascript:;">Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_why_customersmobile" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_why_customersmobile" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_why_customersmobile" name="setting[main_why_customersmobile]" <?php if ($exist): ?> value="<?php echo $settings['main_why_customersmobile'] ?>"<?php endif ?> />
	                        </div>

	                        <!-- row 1 -->
	                        <div class="form-group">
                                <label style="font-weight: bold; color: #000;">Superior Customer Service</label>
                                <label for="slide_link">Title :</label>
                                <input type="text" class="form-control" id="title_one" name="setting[title_one]" <?php if ($exist): ?> value="<?php echo $settings['title_one'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_one" name="setting[desctiption_one]"><?php if ($exist): ?><?php echo $settings['desctiption_one'] ?><?php endif ?></textarea>

                               <?php /* <input type="text" class="form-control" id="desctiption_one" name="setting[desctiption_one]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_one'] ?>"<?php endif ?>/> */?>
                            </div>


	                        <div class="form-group images-remove5">
	                            <label><?php echo __('Images'); ?></label>
                                <a class="remove5 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_why_one" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_why_one" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_why_one" name="setting[imgwhy_one]" <?php if ($exist): ?> value="<?php echo $settings['imgwhy_one'] ?>"<?php endif ?> />
	                        </div>

	                        <!-- row 2 -->
	                        <div class="form-group">
	                        	<label style="font-weight: bold; color: #000;">Quick Turn Arounds</label>
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title_two" name="setting[title_two]" <?php if ($exist): ?> value="<?php echo $settings['title_two'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_two" name="setting[desctiption_two]"><?php if ($exist): ?><?php echo $settings['desctiption_two'] ?><?php endif ?></textarea>
                               <?php /*  <input type="text" class="form-control" id="desctiption_two" name="setting[desctiption_two]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_two'] ?>"<?php endif ?>/> */ ?>
                            </div>
	                        <div class="form-group images-remove6">
	                            <label><?php echo __('Images'); ?></label>
                                <a class="remove6 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_why_two" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_why_two" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_why_two" name="setting[imgwhy_two]" <?php if ($exist): ?> value="<?php echo $settings['imgwhy_two'] ?>"<?php endif ?> />
	                        </div>

	                        <!-- row 3 -->
	                        <div class="form-group">
	                        	<label style="font-weight: bold; color: #000;">Community Engagement</label>
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title_three" name="setting[title_three]" <?php if ($exist): ?> value="<?php echo $settings['title_three'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_three" name="setting[desctiption_three]"><?php if ($exist): ?><?php echo $settings['desctiption_three'] ?><?php endif ?></textarea>
                                <?php /* <input type="text" class="form-control" id="desctiption_three" name="setting[desctiption_three]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_three'] ?>"<?php endif ?>/> */?>
                            </div>
	                        <div class="form-group images-remove7">
	                            <label><?php echo __('Images'); ?></label>
                                <a class="remove7 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_why_three" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_why_three" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_why_three" name="setting[imgwhy_three]" <?php if ($exist): ?> value="<?php echo $settings['imgwhy_three'] ?>"<?php endif ?> />
	                        </div>
	                        <!----------- & Section 2 ----------->



	                        <!-----------  Section 3 ----------->

	                        <div class="form-group">
	                        	<label style="font-weight: bold; color: #000;">OUR STORY story</label>

                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title_story_1" name="setting[title_story_1]" <?php if ($exist): ?> 
                                value="<?php echo $settings['title_story_1'] ?>" <?php endif ?> />
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_story_1" name="setting[desctiption_story_1]"><?php if ($exist): ?><?php echo $settings['desctiption_story_1'] ?><?php endif ?></textarea>
                                <?php /* <input type="text" class="form-control" id="desctiption_story_1" name="setting[desctiption_story_1]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_story_1'] ?>"<?php endif ?>/> */?>
                            </div>

	                        <div class="form-group images-remove8">
	                            <label><?php echo __('Images'); ?></label>
                                <a class="remove8 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_story_1" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_story_1" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_story_1" name="setting[imgsave_story_1]" <?php if ($exist): ?> value="<?php echo $settings['imgsave_story_1'] ?>"<?php endif ?> />
	                        </div>


	                         <div class="form-group">
	                        	<label style="font-weight: bold; color: #000;">STRONG LEADERSHIP</label>
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title_story_2" name="setting[title_story_2]" <?php if ($exist): ?> 
                                value="<?php echo $settings['title_story_2'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_story_2" name="setting[desctiption_story_2]"><?php if ($exist): ?><?php echo $settings['desctiption_story_2'] ?><?php endif ?></textarea>
                                <?php /* <input type="text" class="form-control" id="desctiption_story_2" name="setting[desctiption_story_2]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_story_2'] ?>"<?php endif ?>/> */?>
                            </div>


	                        <div class="form-group images-remove9">
	                            <label><?php echo __('Images'); ?></label>
                                <a class="remove9 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_story_2" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_story_2" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_story_2" name="setting[imgsave_story_2]" <?php if ($exist): ?> value="<?php echo $settings['imgsave_story_2'] ?>"<?php endif ?> />
	                        </div>
	                        <div class="form-group images-remove10">
	                            <label><?php echo __('Background Images'); ?></label>
                                <a class="remove10 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_storybackground_2" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_storybackground_2" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_storybackground_2" name="setting[imgsave_storybackground_2]" <?php if ($exist): ?> value="<?php echo $settings['imgsave_storybackground_2'] ?>"<?php endif ?> />
	                        </div>

	                        <!----------- & Section 3 ----------->

	                        <!-----------  Section 4  spirit SPIRIT------------->
	                        <div class="form-group">
	                        	<label style="font-weight: bold; color: #000;">SWEDA SPIRIT</label>
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title_spirit_2" name="setting[title_spirit_2]" <?php if ($exist): ?> 
                                value="<?php echo $settings['title_spirit_2'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <textarea id="desctiption_spirit_2" name="setting[desctiption_spirit_2]"><?php if ($exist): ?><?php echo $settings['desctiption_spirit_2'] ?><?php endif ?></textarea>
                                <?php /* <input type="text" class="form-control" id="desctiption_spirit_2" name="setting[desctiption_spirit_2]" <?php if ($exist): ?> value="<?php echo $settings['desctiption_spirit_2'] ?>"<?php endif ?>/> */?>
                            </div>
                           
	                        <div class="form-group images-remove11">
	                            <label><?php echo __('Images Left'); ?></label>
                                <a class="remove11 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_spirit_2" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style="background: #f4f4f4; width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_spirit_2" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_spirit_2" name="setting[imgsave_spirit_2]" <?php if ($exist): ?> value="<?php echo $settings['imgsave_spirit_2'] ?>"<?php endif ?> />
	                        </div>
	                        <div class="form-group images-remove12">
	                            <label><?php echo __('Images Right'); ?></label>
                                <a class="remove12 btn btn-info" href="javascript:;" >Remove Images</a>
	                            <div class="slide_images_wrapper">
	                                <ul id="slide_spirit_3" class="slide-images">
	                                    <?php if (count($images) > 0): ?>
	                                        <?php $i = 0;
	                                        foreach ($images as $_image): $i++ ?>
	                                            <li style=" background: #f4f4f4;width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
	                                                <img class="img_spirit_3" title="<?php echo $_image;?>"
	                                                     src="<?php echo $this->getPanelUploadSrc('aboutus', $_image) ?>"
	                                                     alt=""/></li>
	                                        <?php endforeach ?>
	                                    <?php endif ?>
	                                </ul>
	                            </div>
	                            <input type="hidden" class="form-control" id="slide_img_url_spirit_3" name="setting[imgsave_spirit_3]" <?php if ($exist): ?> value="<?php echo $settings['imgsave_spirit_3'] ?>"<?php endif ?> />
	                        </div>
	                        <!----------- & Section 4 ----------->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back"
                                    onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>"
                               class="bd-action bd-action-success<?php if ($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    var idx = <?php echo $i ?>;

    var selectedImage = <?php  echo($exist ? "'" . $settings['backgroundImage'] . "'" : "''")  ?>;
    var backgroundImagemobile = <?php  echo($exist ? "'" . $settings['backgroundImagemobile'] . "'" : "''")  ?>;
    // var backgroundImagevideo = <?php  //echo($exist ? "'" . $settings['backgroundImagevideo'] . "'" : "''")  ?>;
    var main_why_customers = <?php  echo($exist ? "'" . $settings['main_why_customers'] . "'" : "''")  ?>;
    var main_why_customersmobile = <?php  echo($exist ? "'" . $settings['main_why_customersmobile'] . "'" : "''")  ?>;
    var imgwhy_one = <?php  echo($exist ? "'" . $settings['imgwhy_one'] . "'" : "''")  ?>;
    var imgwhy_two = <?php  echo($exist ? "'" . $settings['imgwhy_two'] . "'" : "''")  ?>;
    var imgwhy_three = <?php  echo($exist ? "'" . $settings['imgwhy_three'] . "'" : "''")  ?>;
    var imgsave_story_1 = <?php  echo($exist ? "'" . $settings['imgsave_story_1'] . "'" : "''")  ?>;
    var imgsave_story_2 = <?php  echo($exist ? "'" . $settings['imgsave_story_2'] . "'" : "''")  ?>;
    var imgsave_storybackground_2 = <?php  echo($exist ? "'" . $settings['imgsave_storybackground_2'] . "'" : "''")  ?>;
    var imgsave_spirit_2 = <?php  echo($exist ? "'" . $settings['imgsave_spirit_2'] . "'" : "''")  ?>;
    var imgsave_spirit_3 = <?php  echo($exist ? "'" . $settings['imgsave_spirit_3'] . "'" : "''")  ?>;
    require([
        'jquery',
        'mustache',
        'lodash',
        "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function ($, Mustache, _) {

        $(document).ready(function () {
            setFullheight();

            $('#configreset').click(function(){
                alert('ddddddddddd');
               $('#slide_img_url input[type="hidden"]').val('');
            });
            
            wysiwygcompany_description = new wysiwygSetup("desctiption_one", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");
            wysiwygcompany_description = new wysiwygSetup("desctiption_two", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");
            wysiwygcompany_description = new wysiwygSetup("desctiption_three", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");
            wysiwygcompany_description = new wysiwygSetup("desctiption_story_1", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");
            wysiwygcompany_description = new wysiwygSetup("desctiption_story_2", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");
            wysiwygcompany_description = new wysiwygSetup("desctiption_spirit_2", {
                "height": "200px",
                "forced_root_block" : "",
                "force_br_newlines" : true,
                "force_p_newlines" : false,
                "forced_root_block" : false,
                "tinymce4": {
                    "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                    "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
                }
            });
            wysiwygcompany_description.setup("exact");


            if (selectedImage != "") {
                $("#slide_images > li > img[src='" + selectedImage + "']").parent().addClass('active');
            }
            if (backgroundImagemobile != "") {
                $("#slide_mobile > li > img[src='" + backgroundImagemobile + "']").parent().addClass('active');
            }
            // if (backgroundImagevideo != "") {
            //     $("#slide_video > li >  .videofluid[src='" + backgroundImagevideo + "']").parent().addClass('active');
            // }
            if (main_why_customers != "") {
                $("#slide_why_customers > li > img[src='" + main_why_customers + "']").parent().addClass('active');
            }
            if (main_why_customersmobile != "") {
                $("#slide_why_customersmobile > li > img[src='" + main_why_customersmobile + "']").parent().addClass('active');
            }
            if (imgwhy_one != "") {
                $("#slide_why_one > li > img[src='" + imgwhy_one + "']").parent().addClass('active');
            }
            if (imgwhy_two != "") {
                $("#slide_why_two > li > img[src='" + imgwhy_two + "']").parent().addClass('active');
            }
            if (imgwhy_three != "") {
                $("#slide_why_three > li > img[src='" + imgwhy_three + "']").parent().addClass('active');
            }
            if (imgsave_story_1 != "") {
                $("#slide_story_1 > li > img[src='" + imgsave_story_1 + "']").parent().addClass('active');
            }
            if (imgsave_story_2 != "") {
                $("#slide_story_2 > li > img[src='" + imgsave_story_2 + "']").parent().addClass('active');
            }
            if (imgsave_storybackground_2 != "") {
                $("#slide_storybackground_2 > li > img[src='" + imgsave_storybackground_2 + "']").parent().addClass('active');
            }
            if (imgsave_spirit_2 != "") {
                $("#slide_spirit_2 > li > img[src='" + imgsave_spirit_2 + "']").parent().addClass('active');
            }
            if (imgsave_spirit_3 != "") {
                $("#slide_spirit_3 > li > img[src='" + imgsave_spirit_3 + "']").parent().addClass('active');
            }
        });

        $(document).on('change', ".setting_img_checkbox", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.setting_imgname').val(imgName);
            } else {
                $(this).parent().find('.setting_imgname').val('');
            }
        });

        $(document).on('change', ".check_remove", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.remove_img').val('remove');
            } else {
                $(this).parent().find('.remove_img').val('');
            }
        });

        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_images li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_mobile li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_video li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_why_customers li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_why_customersmobile li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_why_one li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_why_two li.active').removeClass('active');
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_why_three li.active').removeClass('active');
        });
		$('#slideCancer').click(function () {
			ClearFormValues();
			$('#slide .new-slide-popup').removeClass('active');
			$('#slide_story_1 li.active').removeClass('active');
		});
		$('#slideCancer').click(function () {
			ClearFormValues();
			$('#slide .new-slide-popup').removeClass('active');
			$('#slide_story_2 li.active').removeClass('active');
		});
		$('#slideCancer').click(function () {
			ClearFormValues();
			$('#slide .new-slide-popup').removeClass('active');
			$('#slide_storybackground_2 li.active').removeClass('active');
		});
		$('#slideCancer').click(function () {
			ClearFormValues();
			$('#slide .new-slide-popup').removeClass('active');
			$('#slide_spirit_2 li.active').removeClass('active');
		});
		$('#slideCancer').click(function () {
			ClearFormValues();
			$('#slide .new-slide-popup').removeClass('active');
			$('#slide_spirit_3 li.active').removeClass('active');
		});
        $(document).on("click", "a.item-image", function (event) {
            event.preventDefault();
        });

        $(document).on("click", "#slide_images li", function () {
            $('#slide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url').val($(this).find('img').attr('src'));
        });

        //***********************   Remove Images   ****************************//
        $(document).on("click", ".desktop-view-showing a.remove1", function () {
            $('#slide_images li.active').removeClass('active');
            $('#slide_img_url').val($(this).find('img').attr('src'));
        });
        $(document).on("click", ".mobile-view-showing a.remove2", function () {
            $('#slide_mobile li.active').removeClass('active');
            $('#slide_img_url_mobile').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".background-images a.remove3", function () {
            $('#slide_why_customers li.active').removeClass('active');
            $('#slide_img_url_why_customers').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".background-images-mobile-view a.remove4", function () {
            $('#slide_why_customersmobile li.active').removeClass('active');
            $('#slide_img_url_why_customersmobile').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove5 a.remove5", function () {
            $('#slide_why_one li.active').removeClass('active');
            $('#slide_img_url_why_one').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove6 a.remove6", function () {
            $('#slide_why_two li.active').removeClass('active');
            $('#slide_img_url_why_two').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove7 a.remove7", function () {
            $('#slide_why_three li.active').removeClass('active');
            $('#slide_img_url_why_three').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove8 a.remove8", function () {
            $('#slide_story_1 li.active').removeClass('active');
            $('#slide_img_url_story_1').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove9 a.remove9", function () {
            $('#slide_story_2 li.active').removeClass('active');
            $('#slide_img_url_story_2').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove10 a.remove10", function () {
            $('#slide_storybackground_2 li.active').removeClass('active');
            $('#slide_img_url_storybackground_2').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove11 a.remove11", function () {
            $('#slide_spirit_2 li.active').removeClass('active');
            $('#slide_img_url_spirit_2').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".images-remove12 a.remove12", function () {
            $('#slide_spirit_3 li.active').removeClass('active');
            $('#slide_img_url_spirit_3').val($(this).find('img').attr('src'));
        });
        
        //***********************   End Remove Images   ****************************//



        
        $(document).on("click", "#slide_mobile li", function () {
            $('#slide_mobile li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_mobile').val($(this).find('img').attr('src'));
        });
        //  $(document).on("click", "#slide_video li", function () {
        //     $('#slide_video li.active').removeClass('active');
        //     $(this).addClass('active');
        //     $('#slide_img_url_video').val($(this).find('.videofluid').attr('src'));
        // });
        $(document).on("click", "#slide_why_customers li", function () {
            $('#slide_why_customers li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_why_customers').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_why_customersmobile li", function () {
            $('#slide_why_customersmobile li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_why_customersmobile').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_why_one li", function () {
            $('#slide_why_one li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_why_one').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_why_two li", function () {
            $('#slide_why_two li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_why_two').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_why_three li", function () {
            $('#slide_why_three li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_why_three').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_story_1 li", function () {
            $('#slide_story_1 li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_story_1').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_story_2 li", function () {
            $('#slide_story_2 li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_story_2').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_storybackground_2 li", function () {
            $('#slide_storybackground_2 li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_storybackground_2').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_spirit_2 li", function () {
            $('#slide_spirit_2 li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_spirit_2').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#slide_spirit_3 li", function () {
            $('#slide_spirit_3 li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url_spirit_3').val($(this).find('img').attr('src'));
        });

    });
    function setFullheight() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#fullheight').prop("checked") == true) {
                    $('#offset-input').show();
                } else {
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
    }
    function detectIE() {
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf('MSIE ');
        var trident = ua.indexOf('Trident/');
        var edge = ua.indexOf('Edge/');

        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function newImageUpload() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#file_upload').length) {
                    if ($('#upload_button').length) {
                        alert('<?php echo __('Please upload selected image first.') ?>');
                    } else {
                        alert('<?php echo __('Please choose file to upload.') ?>');
                    }
                } else {
                    html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                    $('#list-upload').html(html);
                }

            })(jQuery);
        });
    }

    function chooseFileAction(elId) {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                fileName = $('#' + elId).val();
                arrName = fileName.split(".");
                extensionName = arrName[arrName.length - 1];
                extensionName = extensionName.toLowerCase();
                if((extensionName=='jpg') || (extensionName=='jpeg') || (extensionName=='png') || (extensionName=='gif') || (extensionName=='mp4') || (extensionName=='ogv') || (extensionName=='wmv') || (extensionName=='avi')){
                    html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                    $('#upload_action').html(html);
                }
            })(jQuery);
        });
    }

    function uploadImage() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                idx++;
                if ($('.alert-image-success').length) {
                    $('.alert-image-success').remove();
                }
                $('#upload-loading').show();
                $('#upload-icon').hide();
                var formData = new FormData();
                formData.append('file', $('#file_upload')[0].files[0]);
                $.ajax({
                    url: "<?php echo $this->getUrl('mpanel/post/upload', ['type' => 'aboutus']) ?>",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {
                        var result = jQuery.parseJSON(data);
                        if (result.result == 'success') {
                            tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('aboutus') ?>' + result.data + '" alt=""></li>';
                            html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                '<img class="img-fluid" src="<?php echo $this->getPanelUploadFolder('aboutus') ?>' + result.data + '" alt=""/>' +
                                '<div class="remove-action">' +
                                '<label for="check-remove-' + idx + '"></label>' +
                                '<input class="check_remove" id="check-remove-' + idx + '" type="checkbox" name="remove[]" value="' + result.data + '"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                            $('#list-images').append(html);
                            $('#slide_images').append(tbhtml);
                            $(".panel-image-list").animate({scrollTop: $('#list-images').height()}, 300);
                        } else {
                            alert(result.data);
                        }

                        $('#list-upload').html('');
                    }
                });
            })(jQuery);
        });
    }
</script>

<style>
    video.thumb-video{
        width: 100px;
        height: auto;
    }
    video.thumb-video::-webkit-media-controls {
        display: none;
    }

    /* Could Use thise as well for Individual Controls */
    video.thumb-video::-webkit-media-controls-play-button {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-volume-slider {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-mute-button {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-timeline {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-current-time-display {
        display: none;
    }
    .mfp-iframe-holder .mfp-content{
        height: 500px;
    }
    .form-group a.btn.btn-info {
    border-radius: 0;
    padding: 9px;
    margin-bottom: 10px;
    background: #28a745;
    }
</style>