<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $images = $helper->getPanelUploadImages('imprint_project') ?>
<?php $i = 0; ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('Imprint Project') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST"
          action="<?php echo $this->getUrl('mpanel/element/save') ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="imprint_project">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">

        <?php if (isset($params['id'])): ?>
            <?php
            try {
                $child = $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>


        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]"
                   value="<?php if ($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active show" id="slide-tab-nav" data-toggle="tab"
                           href="#slide"><?php echo __('Settings') ?></a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div id="slide" class="tab-pane active">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button"
                                    title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span>
                            </button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>">
                                <span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button"
                                    title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <input type="hidden" class="form-control" id="slide_status" value="1"/>
                        <input type="hidden" class="form-control" id="slide_random_number" value="0"/>
                        <div class="form-slide">
                            <div class="form-group">
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="title"
                                       name="setting[title]" <?php if ($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description:</label>
                                <input type="text" class="form-control" id="description"
                                       name="setting[description]" <?php if ($exist): ?> value="<?php echo $settings['description'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Button Text:</label>
                                <input type="text" class="form-control" id="buttonText"
                                       name="setting[buttonText]" <?php if ($exist): ?> value="<?php echo $settings['buttonText'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Button Link:</label>
                                <input type="text" class="form-control" id="buttonLink"
                                       name="setting[buttonLink]" <?php if ($exist): ?> value="<?php echo $settings['buttonLink'] ?>"<?php endif ?>/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back"
                                    onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>"
                               class="bd-action bd-action-success<?php if ($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    var idx = <?php echo $i ?>;

    require([
        'jquery',
        'mustache',
        'lodash'
    ], function ($, Mustache, _) {

        $(document).ready(function () {
            setFullheight();
        });

        $(document).on('change', ".setting_img_checkbox", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.setting_imgname').val(imgName);
            } else {
                $(this).parent().find('.setting_imgname').val('');
            }
        });

        $(document).on('change', ".check_remove", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.remove_img').val('remove');
            } else {
                $(this).parent().find('.remove_img').val('');
            }
        });

        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_images li.active').removeClass('active');
        });

        $(document).on("click", "a.item-image", function (event) {
            event.preventDefault();
        });

        $(document).on("click", "#slide_images li", function () {
            $('#slide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url').val($(this).find('img').attr('src'));
        });
    });


    function setFullheight() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#fullheight').prop("checked") == true) {
                    $('#offset-input').show();
                } else {
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
    }

    function detectIE() {
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf('MSIE ');
        var trident = ua.indexOf('Trident/');
        var edge = ua.indexOf('Edge/');

        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function newImageUpload() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#file_upload').length) {
                    if ($('#upload_button').length) {
                        alert('<?php echo __('Please upload selected image first.') ?>');
                    } else {
                        alert('<?php echo __('Please choose file to upload.') ?>');
                    }
                } else {
                    html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                    $('#list-upload').html(html);
                }

            })(jQuery);
        });
    }

    function chooseFileAction(elId) {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                fileName = $('#' + elId).val();
                arrName = fileName.split(".");
                extensionName = arrName[arrName.length - 1];
                extensionName = extensionName.toLowerCase();
                if ((extensionName == 'jpg') || (extensionName == 'jpeg') || (extensionName == 'png') || (extensionName == 'gif')) {
                    html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                    $('#upload_action').html(html);
                }
            })(jQuery);
        });
    }

    function uploadImage() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                idx++;
                if ($('.alert-image-success').length) {
                    $('.alert-image-success').remove();
                }
                $('#upload-loading').show();
                $('#upload-icon').hide();
                var formData = new FormData();
                formData.append('file', $('#file_upload')[0].files[0]);
                $.ajax({
                    url: "<?php echo $this->getUrl('mpanel/post/upload', ['type' => 'imprint_project']) ?>",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {
                        var result = jQuery.parseJSON(data);
                        if (result.result == 'success') {
                            tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('start-proeject') ?>' + result.data + '" alt=""></li>';
                            html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                '<img class="img-fluid" src="<?php echo $this->getPanelUploadFolder('imprint_project') ?>' + result.data + '" alt=""/>' +
                                '<div class="remove-action">' +
                                '<label for="check-remove-' + idx + '"></label>' +
                                '<input class="check_remove" id="check-remove-' + idx + '" type="checkbox" name="remove[]" value="' + result.data + '"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                            $('#list-images').append(html);
                            $('#slide_images').append(tbhtml);
                            $(".panel-image-list").animate({scrollTop: $('#list-images').height()}, 300);
                        } else {
                            alert(result.data);
                        }

                        $('#list-upload').html('');
                    }
                });
            })(jQuery);
        });
    }
</script>