<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $images = $helper->getPanelUploadImages('imprintview_faqs') ?>
<?php $i = 1; ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('Imprint Methods View Section Faq') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST"
          action="<?php echo $this->getUrl('mpanel/element/save') ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="imprintview_faqs">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">

        <?php if (isset($params['id'])): ?>
            <?php
            try {
                $child = $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>



        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]"
                   value="<?php if ($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <input type="hidden" name="setting[toolsJson]"/>
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link show active" data-toggle="tab"
                           href="#general"><?php echo __('General') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="images-tab-nav" data-toggle="tab"
                           href="#images"><?php echo __('Manage Images') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slide-tab-nav" data-toggle="tab"
                           href="#slide"><?php echo __('Manage') ?></a>
                    </li>
                </ul>
                <div class="tab-content">

                    <div id="general" class="tab-pane active">
                        <div class="row fr-element">
                            
                            <div class="col-sm-12">
                                <label for="title" class="control-label"><?php echo __('Title') ?></label>
                                <input type="text" id="title" class="input-text" name="setting[title]" <?php if ($exist): ?> value="<?php echo $settings['title'] ?>" <?php endif ?> />
                            </div>
                            
                            <div class="col-sm-12">
                                 <label for="title" class="control-label"><?php echo __('SEE ALL FAQs') ?></label>
                                <input type="text" id="impfaq_seeall" class="input-text" name="setting[impfaq_seeall]" <?php if ($exist): ?> value="<?php echo $settings['impfaq_seeall'] ?>" <?php endif ?> />
                            </div>
                            
                            <div class="col-sm-12">
                                <label for="title" class="control-label"><?php echo __('SEE ALL FAQs Link') ?></label>
                                <input type="text" id="impfaq_seealllink" class="input-text" name="setting[impfaq_seealllink]"
                                    <?php if ($exist): ?> value="<?php echo $settings['impfaq_seealllink'] ?>" <?php endif ?> />
                            </div>
                        </div>
                    </div>

                    <div id="images" class="tab-pane">

                        <div id="list-images">
                            <?php if (count($images) > 0): ?>
                                <?php $i = 0;
                                foreach ($images as $_image): $i++ ?>
                                    <div class="image-item">
                                        <img class="img-fluid"
                                             src="<?php echo $this->getPanelUploadSrc('imprintview_faqs', $_image) ?>"
                                             alt=""/>
                                        <div class="remove-action">
                                            <label for="check-remove-<?php echo $i ?>"></label>
                                            <input class="check_remove" id="check-remove-<?php echo $i ?>"
                                                   type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                            <input class="remove_img" type="hidden" name="setting[removeimg][]"
                                                   value="">
                                        </div>
                                    </div>
                                <?php endforeach ?>
                            <?php endif ?>
                        </div>

                        <div id="upload-container">
                            <div id="list-upload"></div>
                            <button class="btn btn-default" onclick="newImageUpload()" type="button"><span
                                        class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
                        </div>
                    </div>

                    <div id="slide" class="tab-pane">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button"
                                    title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span>
                            </button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>">
                                <span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button"
                                    title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <div class="new-slide-popup" id="new_slide_popup">
                            <input type="hidden" class="form-control" id="slide_status" value="1"/>
                            <input type="hidden" class="form-control" id="slide_random_number" value="0"/>
                            <div class="form-slide">
                                <div class="form-group">
                                    <label for="slide_link">Questions</label>
                                    <input type="text" class="form-control" id="impviewfaq_questions"/>
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Answers</label>
                                    <input type="text" class="form-control" id="impviewfaq_answer"/>
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Sort order:</label>
                                    <input type="text" class="form-control" id="tool_order"/>
                                </div>
                            </div>

                            <div class="actions">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-success" style="width: 100%;" type="button"
                                                id="sliderOk">Submit
                                        </button>
                                    </div>
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-secondary" style="width: 100%;" type="button"
                                                id="slideCancer">Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="slide-wrapper">
                            <div class="carousel_slider_wrapper">
                                <div class="row" id="methods_wrapper"></div>
                            </div>
                        </div>
                        <div class="slide-actions">
                            <button type="button"
                                    class="btn btn-primary add-new-item"><?php echo __('Add New Method') ?></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back"
                                    onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>"
                               class="bd-action bd-action-success<?php if ($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    var idx = <?php echo $i ?>;

    window.toolsJson = <?php echo(isset($settings['toolsJson']) ? $settings['toolsJson'] : "[]")?>;

    require([
        'jquery',
        'mustache',
        'lodash'
    ], function ($, Mustache, _) {

        $(document).ready(function () {
            setFullheight();
            window.jQuery = $;
            RenderTools();
        });

        function RenderTools() {
            $('#methods_wrapper').empty();
            for (i = 0; i < toolsJson.length; i++) {

                var methodElement = '<div class="col-sm-12"><div class="card">\n' +
                    '    <div class="card-header">' +
                    '        <div class="btn-group pull-right">\n' +
                    '            <a href="#" class="btn btn-default btn-sm btn-edit-method" data-random_number="{{random_number}}">Edit</a>\n' +
                    '            <a href="#" class="btn btn-default btn-sm btn-delete-method" data-random_number="{{random_number}}">Delete</a>' +
                    '        </div>' +
                    '    </div>' +
                    '    <div class="card-body">' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label"> Title</label></div>' +
                    '            <div class="col-sm-8"><input type="text" class="input-text" name="setting[tools][{{random_number}}][impviewfaqQues]" value="{{impviewfaqQues}}" disabled>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label"> Link</label></div>' +
                    '            <div class="col-sm-8"><input type="text" class="input-text" name="setting[tools][{{random_number}}][impviewfaqAnswe]" value="{{impviewfaqAnswe}}" disabled></input>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label">Sort Order</label></div>' +
                    '            <div class="col-sm-8"><input type="text" class="input-text" name="setting[tools][{{random_number}}][toolOrder]" value="{{toolOrder}}" disabled></input>' +
                    '        </div>' +
                    '    </div>' +
                    '</div></div>';
                var output = Mustache.render(methodElement, toolsJson[i]);
                $('#methods_wrapper').append(output);
            }
            var data = JSON.stringify(toolsJson);
            $("input[name='setting[toolsJson]']").val(data);
        }

        $('.add-new-item').click(function () {
            $('#slide_images li.active').removeClass('active');
            //$('#slide_images_hover li.active').removeClass('active');
            $('#slide_img_url').val('');
            $('#slide_img_url_hover').val('');
            $('#slide_link').val('');
            $('#slide_html').val('');
            $('#slide_status').val('1');
            $('#slide_html_animation').val('');
            $('#slide .new-slide-popup').addClass('active');
        });

        $(document).on('change', ".setting_img_checkbox", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.setting_imgname').val(imgName);
            } else {
                $(this).parent().find('.setting_imgname').val('');
            }
        });

        $(document).on('change', ".check_remove", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.remove_img').val('remove');
            } else {
                $(this).parent().find('.remove_img').val('');
            }
        });

        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_images li.active').removeClass('active');
        });

        // $('#slideCancer').click(function () {
        //     ClearFormValues();
        //     $('#slide .new-slide-popup').removeClass('active');
        //     $('#slide_images_hover li.active').removeClass('active');
        // });

        $(document).on("click", "a.item-image", function (event) {
            event.preventDefault();
        });

        $(document).on("click", "#slide_images li", function () {
            $('#slide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url').val($(this).find('img').attr('src'));
        });

        // $(document).on("click", "#slide_images_hover li", function () {
        //     $('#slide_images_hover li.active').removeClass('active');
        //     $(this).addClass('active');
        //     $('#slide_img_url_hover').val($(this).find('img').attr('src'));
        // });

        $(document).on("click", ".btn-edit-method", function (event) {

            event.preventDefault();

            $('#slide_status').val(0);

            var random_number = parseInt($(this).data('random_number'));
            $('#slide_random_number').val(random_number);

            var selected = {};

            $.each(toolsJson, function (key, value) {
                if (value.random_number === random_number) {
                    selected = value;
                }
            });

           

            $('#impviewfaq_questions').val(selected.impviewfaqQues);
            $('#impviewfaq_answer').val(selected.impviewfaqAnswe);


            $('#slide_img_url').val(selected.toolImage);
            $('#tool_order').val(selected.toolOrder);

            //$('#slide_img_url_hover').val(selected.toolImageHover);

            $('#slide_images li.active').removeClass('active');
            $("#slide_images > li > img[src='" + selected.toolImage + "']").parent().addClass('active');

            //$('#slide_images_hover li.active').removeClass('active');
            //$("#slide_images_hover > li > img[src='" + selected.toolImageHover + "']").parent().addClass('active');

            $('#slide .new-slide-popup').addClass('active');
            var data = JSON.stringify(toolsJson);
            $("input[name='setting[toolsJson]']").val(data);
        });

        $(document).on("click", ".btn-delete-method", function (event) {

            if (confirm('Are you sure to delete?')) {
                $('#slide_status').val(0);

                var random_number = parseInt($(this).data('random_number'));
                $.each(toolsJson, function (key, value) {
                    if (value.random_number === random_number) {
                        selected = value;
                        toolsJson.splice(toolsJson.indexOf(value), 1);
                    }
                });

                RenderTools();
            } else {
                event.preventDefault();
            }
        });

        function ClearFormValues() {

            $('#slide_status').val(0);
            $('#impviewfaq_questions').val("");
            $('#impviewfaq_answer').val("");
            $("#tool_image").val('');
            $("#tool_order").val('');

            $('#slide_random_number').val("");
            $('#slide_images li.active').removeClass('active');
        }

        function CloseForm() {
            $('#slide .new-slide-popup').removeClass('active');
            var data = JSON.stringify(toolsJson);
            $("input[name='setting[toolsJson]']").val(data);
        }

        function AddUpdateTool() {

            var random_number = 0;

            if (parseInt($('#slide_status').val()) === 0) {
                random_number = parseInt($('#slide_random_number').val());
                toolsJson = _.filter(toolsJson, function (n) {
                    return n.random_number != random_number;
                });
            } else {
                random_number = Math.floor((Math.random() * 10000) + 1);
            }

            

            var impviewfaqQues = $('#impviewfaq_questions').val();
            var impviewfaqAnswe = $('#impviewfaq_answer').val();
            var toolOrder = $('#tool_order').val();

            var objMethod = {
                impviewfaqQues: impviewfaqQues,
                impviewfaqAnswe: impviewfaqAnswe,
                toolOrder: toolOrder,
                random_number: random_number

            };

            toolsJson.push(objMethod);
        }

        $(document).on("click", "#sliderOk", function () {

            if ($('#slide_img_url').val() != "") {

                AddUpdateTool();
                RenderTools();
                ClearFormValues();
                CloseForm();
            } else {
                alert('<?php echo __('Please select an image'); ?>');
            }

        });
    });


    function setFullheight() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#fullheight').prop("checked") == true) {
                    $('#offset-input').show();
                } else {
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
    }

    function detectIE() {
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf('MSIE ');
        var trident = ua.indexOf('Trident/');
        var edge = ua.indexOf('Edge/');

        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function newImageUpload() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#file_upload').length) {
                    if ($('#upload_button').length) {
                        alert('<?php echo __('Please upload selected image first.') ?>');
                    } else {
                        alert('<?php echo __('Please choose file to upload.') ?>');
                    }
                } else {
                    html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                    $('#list-upload').html(html);
                }

            })(jQuery);
        });
    }

    function chooseFileAction(elId) {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                fileName = $('#' + elId).val();
                arrName = fileName.split(".");
                extensionName = arrName[arrName.length - 1];
                extensionName = extensionName.toLowerCase();
                if ((extensionName == 'jpg') || (extensionName == 'jpeg') || (extensionName == 'png') || (extensionName == 'gif')) {
                    html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                    $('#upload_action').html(html);
                }
            })(jQuery);
        });
    }

    function uploadImage() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                idx++;
                if ($('.alert-image-success').length) {
                    $('.alert-image-success').remove();
                }
                $('#upload-loading').show();
                $('#upload-icon').hide();
                var formData = new FormData();
                formData.append('file', $('#file_upload')[0].files[0]);
                $.ajax({
                    url: "<?php echo $this->getUrl('mpanel/post/upload', ['type' => 'imprintview_faqs']) ?>",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {
                        var result = jQuery.parseJSON(data);
                        if (result.result == 'success') {
                            tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('imprintview_faqs') ?>' + result.data + '" alt=""></li>';
                            html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                '<img class="img-fluid" src="<?php echo $this->getPanelUploadFolder('imprintview_faqs') ?>' + result.data + '" alt=""/>' +
                                '<img class="img-fluid_hover" src="<?php echo $this->getPanelUploadFolder('imprintview_faqs') ?>' + result.data + '" alt=""/>' +
                                '<div class="remove-action">' +
                                '<label for="check-remove-' + idx + '"></label>' +
                                '<input class="check_remove" id="check-remove-' + idx + '" type="checkbox" name="remove[]" value="' + result.data + '"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                            $('#list-images').append(html);
                            $('#slide_images').append(tbhtml);
                            //$('#slide_images_hover').append(tbhtml);
                            $(".panel-image-list").animate({scrollTop: $('#list-images').height()}, 300);
                        } else {
                            alert(result.data);
                        }

                        $('#list-upload').html('');
                    }
                });
            })(jQuery);
        });
    }
</script>