<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $i = 0; ?>
<?php $images = $helper->getPanelUploadImages('imprint-methods') ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('Imprint Methods') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST"
          action="<?php echo $this->getUrl('mpanel/element/save') ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="imprint-methods">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">

        <?php if (isset($params['id'])): ?>
            <?php
            try {
                $child = $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>


        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]"
                   value="<?php if ($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <input type="hidden" name="setting[methodsJson]"/>
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link show active" data-toggle="tab"
                           href="#general"><?php echo __('General') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="images-tab-nav" data-toggle="tab"
                           href="#images"><?php echo __('Manage Images') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slide-tab-nav" data-toggle="tab"
                           href="#slide"><?php echo __('Manage Methods') ?></a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div id="general" class="tab-pane active">

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="title" class="control-label"><?php echo __('Title Text') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" id="title" class="input-text"
                                       name="setting[title]" <?php if ($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?> />
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="class" class="control-label"><?php echo __('Link Text') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" id="linkText" class="input-text"
                                       name="setting[linkText]"<?php if ($exist): ?> value="<?php echo $settings['linkText'] ?>"<?php endif ?> />
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="class" class="control-label"><?php echo __('Link URL') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" id="linkUrl" class="input-text"
                                       name="setting[linkUrl]"<?php if ($exist): ?> value="<?php echo $settings['linkUrl'] ?>"<?php endif ?> />
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="class" class="control-label"><?php echo __('Background Color On Hover') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <label for="class" class="control-label"><?php echo __('Color: 1') ?>
                                <input type="color" id="background_all" class="input-text" name="setting[background_all]"<?php if ($exist): ?> value="<?php echo $settings['background_all'] ?>"<?php endif ?> style="width: 70px; padding: 0px;" />
                                <label for="class" class="control-label"><?php echo __('Color: 2') ?>
                                <input type="color" id="background_all" class="input-text" name="setting[background_two]"<?php if ($exist): ?> value="<?php echo $settings['background_two'] ?>"<?php endif ?> style="width: 70px; padding: 0px;" />
                            </div>
                        </div>

                    </div>
                    <div id="images" class="tab-pane">

                        <div id="list-images">
                            <?php if (count($images) > 0): ?>
                                <?php $i = 0;
                                foreach ($images as $_image): $i++ ?>
                                    <div class="image-item">
                                        <img class="img-fluid" title="<?php echo $_image; ?>"
                                             src="<?php echo $this->getPanelUploadSrc('imprint-methods', $_image) ?>"
                                             alt=""/>
                                        <div class="remove-action">
                                            <label for="check-remove-<?php echo $i ?>"></label>
                                            <input class="check_remove" id="check-remove-<?php echo $i ?>"
                                                   type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                            <input class="remove_img" type="hidden" name="setting[removeimg][]"
                                                   value="">
                                        </div>
                                    </div>
                                <?php endforeach ?>
                            <?php endif ?>
                        </div>

                        <div id="upload-container">
                            <div id="list-upload"></div>
                            <button class="btn btn-default" onclick="newImageUpload()" type="button"><span
                                        class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
                        </div>
                    </div>
                    <div id="slide" class="tab-pane">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button"
                                    title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span>
                            </button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>">
                                <span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button"
                                    title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <div class="new-slide-popup" id="new_slide_popup">
                            <input type="hidden" class="form-control" id="slide_status" value="1"/>
                            <input type="hidden" class="form-control" id="slide_random_number" value="0"/>
                            <div class="form-slide">
                                <div class="form-group">
                                    <label><?php echo __('Images'); ?>:</label>
                                    <div class="slide_images_wrapper">
                                        <ul id="slide_images" class="slide-images">
                                            <?php if (count($images) > 0): ?>
                                                <?php $i = 0;
                                                foreach ($images as $_image): $i++ ?>
                                                    <li style="height: 75px;margin: 6px 3px;width: 99px;"><img class="img-fluid" title="<?php echo $_image; ?>"
                                                             src="<?php echo $this->getPanelUploadSrc('imprint-methods', $_image) ?>"
                                                             alt=""/></li>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </ul>
                                    </div>
                                    <input type="hidden" class="form-control" id="slide_img_url" value=""/>
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Title:</label>
                                    <input type="text" class="form-control" id="slide_link"/>
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Description:</label>
                                    <textarea class="form-control" id="slide_html" value="" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                     <label for="slide_link">Url Link</label>
                                     <input type="text" class="form-control" id="background_item" />
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Sort Order:</label>
                                    <input type="text" class="form-control" id="order"/>
                                </div>
                                <!-- <div class="form-group"> -->
                                    <?php /* <label for="slide_link">Background Color On Hover:</label>
                                    <label for="slide_link">Color:1</label>
                                     <input type="color" class="form-control" id="background_item" style="width: 70px;padding: 0px;height: 42px;" />
                                     <label for="slide_link">Color:2</label>
                                     <input type="color" class="form-control" id="background_item_two" style="width: 70px;padding: 0px;height: 42px;" />
                                     */ ?>
                                <!-- </div> -->
                            </div>
                            <div class="actions">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-success" style="width: 100%;" type="button"
                                                id="sliderOk">Submit
                                        </button>
                                    </div>
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-secondary" style="width: 100%;" type="button"
                                                id="slideCancer">Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="slide-wrapper">
                            <div class="carousel_slider_wrapper">
                                <div class="row" id="methods_wrapper"></div>
                            </div>
                        </div>
                        <div class="slide-actions">
                            <button type="button"
                                    class="btn btn-primary add-new-item"><?php echo __('Add New Method') ?></button>
                        </div>
                    </div>
                    <div id="slider" class="tab-pane">

                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back"
                                    onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>"
                               class="bd-action bd-action-success<?php if ($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    var idx = <?php echo $i ?>;

    window.methodsJson = <?php echo(isset($settings['methodsJson']) ? $settings['methodsJson'] : "[]")?>;

    require([
        'jquery',
        'mustache',
        'lodash'
    ], function ($, Mustache, _) {

        $(document).ready(function () {
            setFullheight();
            RenderMethods();
        });

        function RenderMethods() {
            $('#methods_wrapper').empty();
            for (i = 0; i < methodsJson.length; i++) {

                var methodElement = '<div class="col-sm-12"><div class="card">\n' +
                    '    <div class="card-header"><h3 class="card-title">{{imprintTitle}}</h3>' +
                    '        <div class="btn-group pull-right">\n' +
                    '            <a href="#" class="btn btn-default btn-sm btn-edit-method" data-random_number="{{random_number}}">Edit</a>\n' +
                    '            <a href="#" class="btn btn-default btn-sm btn-delete-method" data-random_number="{{random_number}}">Delete</a>' +
                    '        </div>' +
                    '    </div>' +
                    '    <div class="card-body">' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label">Imprint Title</label></div>' +
                    '            <div class="col-sm-8"><input type="text" class="input-text" name="setting[methods][{{random_number}}][title]" value="{{imprintTitle}}" disabled>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label">Imprint Description</label></div>' +
                    '            <div class="col-sm-8"><textarea class="input-text" name="setting[methods][{{random_number}}][description]" row="3" disabled>{{imprintDescription}}</textarea>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '          <div class="col-sm-4"><label class="control-label">Background Color on Hover</label></div>' +
                    '            <div class="col-sm-8"><label class="control-label">Color: 1</label><input style="width: 70px; padding: 0px;" type="color" class="input-text" name="setting[methods][{{random_number}}][background_item]" value="{{backgroundItem}}" disabled><label class="control-label">Color: 2</label><input style="width: 70px; padding: 0px;" type="color" class="input-text" name="setting[methods][{{random_number}}][background_item_two]" value="{{backgroundItemTwo}}" disabled>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label">Sort Order</label></div>' +
                    '            <div class="col-sm-8"><input type="text" class="input-text" name="setting[methods][{{random_number}}][order]" value="{{imprintOrder}}" disabled>' +
                    '            </div>' +
                    '        </div>' +
                    '        <div class="row fr-element">' +
                    '            <div class="col-sm-4"><label class="control-label">Imprint Image</label></div>' +
                    '            <div class="col-sm-8"><img style="height: 100px;" name="setting[methods][{{random_number}}][image]" src="{{imprintImage}}"></div>' +
                    '        </div>' +
                    '    </div>' +
                    '</div></div>';

                var output = Mustache.render(methodElement, methodsJson[i]);
                $('#methods_wrapper').append(output);
            }
            var data = JSON.stringify(methodsJson);
            $("input[name='setting[methodsJson]']").val(data);
        }

        $('.add-new-item').click(function () {
            $('#slide_images li.active').removeClass('active');
            $('#slide_img_url').val('');
            $('#slide_link').val('');
            $('#order').val('');
            $('#slide_html').val('');
            $('#background_item').val('');
            $('#background_item_two').val('');
            $('#slide_status').val('1');
            $('#slide_html_animation').val('');
            $('#slide .new-slide-popup').addClass('active');
        });

        $(document).on('change', ".setting_img_checkbox", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.setting_imgname').val(imgName);
            } else {
                $(this).parent().find('.setting_imgname').val('');
            }
        });

        $(document).on('change', ".check_remove", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.remove_img').val('remove');
            } else {
                $(this).parent().find('.remove_img').val('');
            }
        });

        $('#slideCancer').click(function () {
            $('#slide .new-slide-popup').removeClass('active');
            $('#slide_images li.active').removeClass('active');
        });

        $(document).on("click", "a.item-image", function (event) {
            event.preventDefault();
        });

        $(document).on("click", "#slide_images li", function () {
            $('#slide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#slide_img_url').val($(this).find('img').attr('src'));
        });

        $(document).on("click", ".btn-edit-method", function (event) {

            if (typeof window.methodsJson === 'undefined') {
                window.methodsJson = [];
            }

            event.preventDefault();

            $('#slide_status').val(0);

            var random_number = parseInt($(this).data('random_number'));
            $('#slide_random_number').val(random_number);

            var selected = {};

            $.each(methodsJson, function (key, value) {
                if (value.random_number === random_number) {
                    selected = value;
                }
            });

            $('#slide_link').val(selected.imprintTitle);
            $('#slide_img_url').val(selected.imprintImage);
            $('#slide_html').val(selected.imprintDescription);
            $('#background_item').val(selected.backgroundItem);
            $('#background_item_two').val(selected.backgroundItemTwo);
            $('#order').val(selected.imprintOrder);
            $('#slide_images li.active').removeClass('active');
            $("#slide_images > li > img[src='" + selected.imprintImage + "']").parent().addClass('active');

            $('#slide .new-slide-popup').addClass('active');
            var data = JSON.stringify(methodsJson);
            $("input[name='setting[methodsJson]']").val(data);
        });

        $(document).on("click", ".btn-delete-method", function (event) {

            if (typeof window.methodsJson === 'undefined') {
                window.methodsJson = [];
            }

            if (confirm('Are you sure to delete?')) {
                $('#slide_status').val(0);

                var random_number = parseInt($(this).data('random_number'));
                $.each(methodsJson, function (key, value) {
                    if (value.random_number === random_number) {
                        selected = value;
                        methodsJson.splice(methodsJson.indexOf(value), 1);
                    }
                });

                RenderMethods();
            } else {
                event.preventDefault();
            }
        });

        $(document).on("click", "#sliderOk", function () {

            if (typeof window.methodsJson === 'undefined') {
                window.methodsJson = [];
            }

            if ($('#slide_img_url').val() != "") {

                var random_number = 0;

                if (parseInt($('#slide_status').val()) === 0) {
                    random_number = parseInt($('#slide_random_number').val());
                    window.methodsJson = _.filter(methodsJson, function (n) {
                        return n.random_number != random_number;
                    });
                } else {
                    random_number = Math.floor((Math.random() * 10000) + 1);
                }

                var imprintTitle = $('#slide_link').val();
                var imprintImage = $('#slide_img_url').val();
                var imprintOrder = $('#order').val();
                var imprintDescription = document.getElementById('slide_html').value;
                var backgroundItem = $('#background_item').val();
                var backgroundItemTwo = $('#background_item_two').val();

                var objMethod = {
                    imprintTitle: imprintTitle,
                    imprintDescription: imprintDescription,
                    imprintImage: imprintImage,
                    imprintOrder: imprintOrder,
                    backgroundItem: backgroundItem,
                    backgroundItemTwo: backgroundItemTwo,
                    random_number: random_number
                };

                methodsJson.push(objMethod);

                RenderMethods();

                $('#slide_status').val(0);
                $('#slide_link').val("");
                $('#slide_img_url').val("");
                $('#slide_html').val("");
                $('#background_item').val("");
                $('#background_item_two').val("");
                $('#order').val("");
                $('#slide_random_number').val("");
                $("#slide_images").removeClass('active');
                $('#slide_images li.active').removeClass('active');

                $('#slide .new-slide-popup').removeClass('active');

                var data = JSON.stringify(methodsJson);
                $("input[name='setting[methodsJson]']").val(data);
            } else {
                alert('<?php echo __('Please select an image'); ?>');
            }
        });
    });

    function setFullheight() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#fullheight').prop("checked") == true) {
                    $('#offset-input').show();
                } else {
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
    }

    function detectIE() {
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf('MSIE ');
        var trident = ua.indexOf('Trident/');
        var edge = ua.indexOf('Edge/');

        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function newImageUpload() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#file_upload').length) {
                    if ($('#upload_button').length) {
                        alert('<?php echo __('Please upload selected image first.') ?>');
                    } else {
                        alert('<?php echo __('Please choose file to upload.') ?>');
                    }
                } else {
                    html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                    $('#list-upload').html(html);
                }

            })(jQuery);
        });
    }

    function chooseFileAction(elId) {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                fileName = $('#' + elId).val();
                arrName = fileName.split(".");
                extensionName = arrName[arrName.length - 1];
                extensionName = extensionName.toLowerCase();
                if ((extensionName == 'jpg') || (extensionName == 'jpeg') || (extensionName == 'png') || (extensionName == 'gif')) {
                    html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                    $('#upload_action').html(html);
                }
            })(jQuery);
        });
    }

    function uploadImage() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                idx++;
                if ($('.alert-image-success').length) {
                    $('.alert-image-success').remove();
                }
                $('#upload-loading').show();
                $('#upload-icon').hide();
                var formData = new FormData();
                formData.append('file', $('#file_upload')[0].files[0]);
                $.ajax({
                    url: "<?php echo $this->getUrl('mpanel/post/upload', ['type' => 'imprint-methods']) ?>",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {
                        var result = jQuery.parseJSON(data);
                        if (result.result == 'success') {
                            tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('imprint-methods') ?>' + result.data + '" alt=""></li>';
                            html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                '<img class="img-fluid" src="<?php echo $this->getPanelUploadFolder('imprint-methods') ?>'+ result.data+'" alt=""/>' +
                                '<div class="remove-action">' +
                                '<label for="check-remove-'+idx+'"></label>' +
                                '<input class="check_remove" id="check-remove-'+idx+'" type="checkbox" name="remove[]" value="'+ result.data+'"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                            $('#list-images').append(html);
                            $('#slide_images').append(tbhtml);
                            $(".panel-image-list").animate({scrollTop: $('#list-images').height()}, 300);
                        } else {
                            alert(result.data);
                        }

                        $('#list-upload').html('');
                    }
                });
            })(jQuery);
        });
    }
</script>