<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $lookbooks = $this->getModel('MGS\Lookbook\Model\Lookbook')->getCollection()->addFieldToFilter('status', 1) ?>
<?php $exist = false ?>
<div class="edit-static-form">
	
	<div class="row">
		<div class="col-md-12 builder-title">
			<h2><?php echo __('Lookbook') ?></h2>
		</div>
	</div>
	<form id="section-form" enctype="multipart/form-data" method="POST" action="<?php echo $this->getUrl('mpanel/element/save') ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
		<input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
		<input id="block_type" type="hidden" name="type" value="lookbook">
		<input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">
		<?php if(isset($params['id'])): ?>
			<?php 
				$child =  $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
				$exist = true;
				$settings = json_decode($child->getSetting(), true);
				$lookbook = $this->getModel('MGS\Lookbook\Model\Lookbook')->getCollection()->addFieldToFilter('lookbook_id', $settings['lookbook_id'])->getFirstItem();
			?>
			<input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
			<input type="hidden" name="banner[lookbook_id]" value="<?php echo $lookbook->getId() ?>">
		<?php endif ?>
		
		
		<div class="form-horizontal">
			<div id="form_tabs" class="tabbable">
				<ul class="nav nav-tabs">
					<li class="nav-item">
						<a class="nav-link active show" data-toggle="tab" href="#general"><?php echo __('General') ?></a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link" id="additional-tab-nav" data-toggle="tab" href="#additional"><?php echo __('Lookbook Config') ?></a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link" id="color-tab-nav" data-toggle="tab" href="#color"><?php echo __('Color Config') ?></a>
					</li>
					
					<?php if($exist): ?>
						<li class="nav-item">
							<a class="nav-link" id="code-tab-nav" data-toggle="tab" href="#code"><?php echo __('Embed Code') ?></a>
						</li>
					<?php endif ?>
				</ul>
				<div class="tab-content">
					<div id="general" class="tab-pane active">
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="title" class="control-label"><?php echo __('Title') ?></label>
                            </div>
							<div class="col-sm-8">
								<input type="text" id="title" class="input-text" name="setting[title]"<?php if($exist): ?> value="<?php echo htmlspecialchars($settings['title']) ?>"<?php endif ?> />
							</div>
						</div>
					
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="col" class="control-label"><?php echo __('Block col (12 to full)') ?></label>
                            </div>
							<div class="col-sm-8">
								<select id="col" class="required-entry input-text" name="col">
									<?php for($i=12; $i>=1; $i--): ?>
										<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
									<?php endfor ?>
								</select>
							</div>
						</div>
                        
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="class" class="control-label"><?php echo __('Custom Class') ?></label>
                            </div>
							<div class="col-sm-8">
								<input type="text" id="class" class="input-text" name="class"<?php if($exist): ?> value="<?php echo $child->getClass() ?>"<?php endif ?> />
							</div>
						</div>
                        
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="additional_content" class="control-label"><?php echo __('Additional content') ?></label>
                            </div>
							<div class="col-sm-8">
								<textarea name="setting[additional_content]" id="content" class="input-text"><?php if($exist): ?><?php echo $settings['additional_content'] ?><?php endif ?></textarea>
							</div>
						</div>
						
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="animation" class="control-label"><?php echo __('Block Animation') ?></label>
                            </div>
							<div class="col-sm-4">
								<select onchange="changeAnimationClass(this.value)" id="animation" class="input-text" name="setting[animation]">
									<option value=""><?php echo __('Choose Animation Effect') ?></option>
									<?php foreach($helper->getAnimationEffect() as $animation=>$label): ?>
										<option value="<?php echo $animation ?>"<?php if($exist && ($settings['animation']==$animation)): ?> selected="selected"<?php endif ?>><?php echo $label ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test">Animation Preview</div>
						</div>
						
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="animation_delay" class="control-label"><?php echo __('Animation Delay') ?></label>
                            </div>
							<div class="col-sm-8">
								<input type="text" placeholder="ms" id="animation_delay" class="input-text validate-number" name="setting[animation_delay]" <?php if($exist): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>>
							</div>
						</div>
						
					</div>
					
					<div id="additional" class="tab-pane">
						<div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="banner_identifier" class="control-label"><?php echo __('Choose Lookbook') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <select class="required-entry input-text" name="setting[lookbook_id]" id="lookbook_id">
                                    <?php if(count($lookbooks)>0): ?>
                                        <?php foreach($lookbooks as $_lookbook): ?>
                                            <option value="<?php echo $_lookbook->getId() ?>"<?php if($exist && ($settings['lookbook_id']==$_lookbook->getId())): ?> selected="selected"<?php endif ?>><?php echo $_lookbook->getName()?></option>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                </select>
                            </div>
                        </div>
					</div>
					
					<div id="color" class="tab-pane">
						<div class="form-group">

							<div class="row fr-element text-color">
                                <div class="col-sm-4">
                                    <label for="text_colour" class="control-label"><?php echo __('Text colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[text_colour]" class="input-text" id="text_colour"<?php if($exist): ?> value="<?php echo $settings['text_colour'] ?>"<?php endif ?> readonly="true"/>
									
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('text_colour', this)"<?php if(isset($settings['text_colour']) && $settings['text_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#text-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="text-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['text_colour']!=''): ?>
										<?php echo $helper->getColorAccept('text_colour', $settings['text_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('text_colour'); ?>
									<?php endif ?>
									
									<a href="#" onclick="closeColorTable('#text-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element link-color">
                                <div class="col-sm-4">
                                    <label for="link_colour" class="control-label"><?php echo __('Link colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[link_colour]" class="input-text" id="link_colour"<?php if($exist): ?> value="<?php echo $settings['link_colour'] ?>"<?php endif ?> readonly="true"/>
									
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('link_colour', this)"<?php if(isset($settings['link_colour']) && $settings['link_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#link-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="link-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['link_colour']!=''): ?>
										<?php echo $helper->getColorAccept('link_colour', $settings['link_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('link_colour'); ?>
									<?php endif ?>
									
									<a href="#" onclick="closeColorTable('#link-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element link-hover-color">
                                <div class="col-sm-4">
                                    <label for="link_hover_colour" class="control-label"><?php echo __('Link hover colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[link_hover_colour]" class="input-text" id="link_hover_colour"<?php if($exist): ?> value="<?php echo $settings['link_hover_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('link_hover_colour', this)"<?php if(isset($settings['link_hover_colour']) && $settings['link_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#link-hover-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="link-hover-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['link_hover_colour']!=''): ?>
										<?php echo $helper->getColorAccept('link_hover_colour', $settings['link_hover_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('link_hover_colour'); ?>
									<?php endif ?>
									
									<a href="#" onclick="closeColorTable('#link-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-color">
                                <div class="col-sm-4">
                                    <label for="button_colour" class="control-label"><?php echo __('Button colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_colour]" class="input-text" id="button_colour"<?php if($exist): ?> value="<?php echo $settings['button_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_colour', this)"<?php if(isset($settings['button_colour']) && $settings['button_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_colour', $settings['button_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-hover-color">
                                <div class="col-sm-4">
                                    <label for="button_hover_colour" class="control-label"><?php echo __('Button hover colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_hover_colour]" class="input-text" id="button_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_hover_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_hover_colour', this)"<?php if(isset($settings['button_hover_colour']) && $settings['button_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-hover-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-hover-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_hover_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_hover_colour', $settings['button_hover_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_hover_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-text-color">
                                <div class="col-sm-4">
                                    <label for="button_text_colour" class="control-label"><?php echo __('Button text colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_text_colour]" class="input-text" id="button_text_colour"<?php if($exist): ?> value="<?php echo $settings['button_text_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_text_colour', this)"<?php if(isset($settings['button_text_colour']) && $settings['button_text_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-text-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-text-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_text_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_text_colour', $settings['button_text_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_text_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-text-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-text-hover-color">
                                <div class="col-sm-4">
                                    <label for="button_text_hover_colour" class="control-label"><?php echo __('Button text hover colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_text_hover_colour]" class="input-text" id="button_text_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_text_hover_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_text_hover_colour', this)"<?php if(isset($settings['button_text_hover_colour']) && $settings['button_text_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-text-hover-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-text-hover-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_text_hover_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_text_hover_colour', $settings['button_text_hover_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_text_hover_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-text-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-border-color">
                                <div class="col-sm-4">
                                    <label for="button_border_colour" class="control-label"><?php echo __('Button border colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_border_colour]" class="input-text" id="button_border_colour"<?php if($exist): ?> value="<?php echo $settings['button_border_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_border_colour', this)"<?php if(isset($settings['button_border_colour']) && $settings['button_border_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-border-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-border-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_border_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_border_colour', $settings['button_border_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_border_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-border-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
							
							<div class="row fr-element button-border-hover-color">
                                <div class="col-sm-4">
                                    <label for="button_border_hover_colour" class="control-label"><?php echo __('Button border hover colour') ?></label>
                                </div>
								<div class="col-sm-6 color-input">
									<input type="text" name="setting[button_border_hover_colour]" class="input-text" id="button_border_hover_colour"<?php if($exist): ?> value="<?php echo $settings['button_border_hover_colour'] ?>"<?php endif ?> readonly="true"/>
									<a class="remove-color" title="<?php echo __('Remove Colour') ?>" onclick="removeColor('button_border_hover_colour', this)"<?php if(isset($settings['button_border_hover_colour']) && $settings['button_border_hover_colour'] !=''):?> style="display:block"<?php endif ?>><em class="fa fa-close"></em></a>
								</div>
								<div class="col-sm-2">
									<label class="control-label"><a href="#" onclick="openColorTable('#button-border-hover-colour-content'); return false"><?php echo __('Change colour') ?></a></label>
								</div>
								<div id="button-border-hover-colour-content" class="color-content" style="display:none">
									<?php if($exist && $settings['button_border_hover_colour']!=''): ?>
										<?php echo $helper->getColorAccept('button_border_hover_colour', $settings['button_border_hover_colour']); ?>
									<?php else: ?>
										<?php echo $helper->getColorAccept('button_border_hover_colour'); ?>
									<?php endif ?>
									<a href="#" onclick="closeColorTable('#button-border-hover-colour-content'); return false" class="close-color"><span class="fa fa-close"></span></a>
								</div>
							</div>
						</div>

					</div>
				
					<?php if($exist): ?>
						<div id="code" class="tab-pane">
							<div class="form-group">
								<h4><?php echo __('For CMS:') ?></h4>
								<div>
									<pre><?php echo $child->getBlockContent() ?></pre>
								</div>
							</div>
						</div>
					<?php endif ?>
				</div>
			</div>
			<div class="row">
				<div class="form-group">
					<div class="col-md-12 builder-action">
						<div class="buttons">
							<?php if(!$exist): ?>
								<button type="button" class="bd-action bd-action-secondary btn-back" onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
							<?php endif ?>
							<input type="submit" value="<?php echo __('Submit') ?>" class="bd-action bd-action-success<?php if($exist): ?> bd-action-full<?php endif ?>"/>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>