<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $images = $helper->getPanelUploadImages('slider') ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('OWL Carousel Slider') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST" action="<?php echo $this->getUrl('mpanel/element/save') ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="owl_banner">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">
        <?php if(isset($params['id'])): ?>
            <?php
            $child =  $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
            $exist = true;
            $settings = json_decode($child->getSetting(), true);
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>


        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]" value="<?php if($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link showpage-header-sliders active" data-toggle="tab" href="#general"><?php echo __('General') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="images-tab-nav" data-toggle="tab" href="#images"><?php echo __('Manage Images') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slide-tab-nav" data-toggle="tab" href="#slide"><?php echo __('Manage Slide') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slider-tab-nav" data-toggle="tab" href="#slider"><?php echo __('Slider Config') ?></a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div id="general" class="tab-pane active">

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="col" class="control-label"><?php echo __('Block col (12 to full)') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <select id="col" class="required-entry input-text" name="col">
                                    <?php for($i=12; $i>=1; $i--): ?>
                                        <option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
                                    <?php endfor ?>
                                </select>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="class" class="control-label"><?php echo __('Custom Class') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" id="class" class="input-text" name="class"<?php if($exist): ?> value="<?php echo $child->getClass() ?>"<?php endif ?> />
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="animation" class="control-label"><?php echo __('Block Animation') ?></label>
                            </div>
                            <div class="col-sm-4">
                                <select onchange="changeAnimationClass(this.value)" id="animation" class="input-text" name="setting[animation]">
                                    <option value=""><?php echo __('Choose Animation Effect') ?></option>
                                    <?php foreach($helper->getAnimationEffect() as $animation=>$label): ?>
                                        <option value="<?php echo $animation ?>"<?php if($exist && ($settings['animation']==$animation)): ?> selected="selected"<?php endif ?>><?php echo $label ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                            <div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test">Animation Preview</div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="animation_delay" class="control-label"><?php echo __('Animation Delay') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" placeholder="ms" id="animation_delay" class="input-text validate-number" name="setting[animation_delay]" <?php if($exist): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>>
                            </div>
                        </div>

                    </div>
                    <div id="images" class="tab-pane">

                        <div id="list-images">
                            <?php if(count($images)>0): ?>
                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                <?php
                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                ?>
                                <?php
                                if($ext=="mp4"){ ?>
                                    <div class="image-item" style="width: 135px;height: 100px; margin-right: 10px;">
                                        <video class="thumb-video img-fluid" src="<?=$this->getPanelUploadSrc('slider',$_image)?>" type="video/mp4" controls="false">
                                            <source src="<?=$this->getPanelUploadSrc('slider',$_image)?>" type="video/mp4" />
                                            </video>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } else { ?>
                                        <div class="image-item" style="width: 135px;height: 100px; margin-right: 10px;">
                                            <img class="img-fluid" src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>" alt=""/>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } ?>

                                <?php endforeach ?>
                            <?php endif ?>
                        </div>

                        <div id="upload-container">
                            <div id="list-upload"></div>
                            <button class="btn btn-default" onclick="newImageUpload()" type="button"><span class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
                        </div>
                    </div>
                    <div id="slide" class="tab-pane">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button" title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span></button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>"><span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button" title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <div class="new-slide-popup" id="new_slide_popup">
                            <input type="hidden" class="form-control" id="slide_status" value="1" />
                            <div class="form-slide">
                                <div class="form-group">
                                    <label style="font-weight: bold; color: #000;"><?php echo __('Desktop Images'); ?>:</label>
                                    <div class="slide_images_wrapper">
                                        <ul id="slide_images" class="slide-images">
                                            <?php if(count($images)>0): ?>
                                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext != "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <img class="img-fluid" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>" alt=""/></li>
                                                    <?php } ?>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </ul>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label style="font-weight: bold; color: #000;"><?php echo __('Mobile View Images'); ?>:</label>
                                    <div class="slide_images_wrapper">
                                        <ul id="slide_images_mob" class="slide-images">
                                            <?php if(count($images)>0): ?>
                                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext != "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <img class="img-mobile" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>" alt=""/></li>
                                                    <?php } ?>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </ul>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label style="font-weight: bold; color: #000;"><?php echo __('Desktop View Video'); ?>:</label>
                                    <div class="slide_images_wrapper">
                                        <ul id="slide_images" class="slide-images slide-desktop-videos">
                                            <?php if(count($images)>0): ?>
                                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php
                                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext=="ogv" || $ext == "wmv" || $ext=="avi" || $ext == "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <video class="thumb-video img-fluid" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>" type="mp4/video">
                                                            <source src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>"  type="video/mp4">
                                                            </video>
                                                        </li>
                                                    <?php }
                                                    ?>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </ul>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label style="font-weight: bold; color: #000;"><?php echo __('Mobile View Video'); ?>:</label>
                                    <div class="slide_images_wrapper">
                                        <ul id="slide_video" class="slide-images slide-mobile-videos">
                                            <?php if(count($images)>0): ?>
                                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php $path = $_image; $ext1 = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext1=="ogv" || $ext1 == "wmv" || $ext1=="avi" || $ext1 == "mp4"){ ?>
                                                    <li style="width: 135px; height: 100px; margin-right: 10px;">
                                                        <video class="thumb-video videofluid"  title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>" type="mp4/video">
                                                            <source src="<?php echo $this->getPanelUploadSrc('slider',$_image) ?>"  type="video/mp4">
                                                            </video>
                                                        </li>
                                                    <?php } ?>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </ul>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="enable_external_videos">Enable External video links:</label>
                                    <input type="checkbox" name="enable_external_videos" id="enable_external_videos" class="form-control">
                                </div>


                                <input type="hidden" class="form-control" id="slide_desktop_img" value="" />
                                <input type="hidden" class="form-control" id="slide_mobile_img" value="" />
                                <input type="hidden" class="form-control" id="slide_desktop_video" value="" />
                                <input type="hidden" class="form-control" id="slide_mobile_video" value="" />
                                <input type="hidden" class="form-control" id="external_video_link" value="" />
                                <input type="hidden" class="form-control" id="external_mobile_video_link" value="" />
                                <input type="hidden" class="form-control" id="msg-slide-counter" value="" />
                                <input type="hidden" class="form-control" id="enable_external_video_status" value="" />

                                

                                <div class="form-group">
                                    <label for="video_link">External Video Link:</label>
                                    <input type="text" class="form-control" id="video_link" value="" />
                                </div>

                                <div class="form-group">
                                    <label for="mobile_video_link">External Mobile Video Link:</label>
                                    <input type="text" class="form-control" id="mobile_video_link" value="" />
                                </div>
                                <div class="form-group">
                                    <label for="slide_link">Link:</label>
                                    <input type="text" class="form-control" id="slide_link" value="" />
                                </div>

                                <div class="form-group">
                                    <label for="slide_link">Slider Title:</label>
                                    <input type="text" class="form-control" id="slide_title" value="" />
                                </div>

                                <div class="form-group">
                                    <label for="slide_link">Button Title:</label>
                                    <input type="text" class="form-control" id="slide_button" value="" />
                                </div>

                                


                                <div class="row">
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <label for="slide_link">Description (Html):</label>
                                            <textarea class="form-control" id="slide_html" rows="4" cols="50"></textarea>
                                        </div>
                                    </div>

                                    <div class="col-sm-2">
                                        <div class="form-group">
                                            <label for="slide_link">Text Position:</label>
                                            <ul id="slide_html_position" class="slide-html-position">
                                                <li data-position="top_left"></li>
                                                <li data-position="top_center"></li>
                                                <li data-position="top_right"></li>
                                                <li data-position="middle_left"></li>
                                                <li class="active" data-position="middle"></li>
                                                <li data-position="middle_right"></li>
                                                <li data-position="bottom_left"></li>
                                                <li data-position="bottom_center"></li>
                                                <li data-position="bottom_right"></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group" style="margin-bottom: 25px;">
                                    <label for="slide_link">Text Animation:</label>
                                    <select id="slide_html_animation">
                                        <option value="">No Effect</option>
                                        <option value="slideInDown">Slide In Down</option>
                                        <option value="slideInUp">Slide In Up</option>
                                        <option value="slideInRight">Slide In Right</option>
                                        <option value="slideInLeft">Slide In Left</option>
                                        <option value="zoomIn">Zoom In</option>
                                        <option value="zoomOut">Zoom Out</option>
                                    </select>
                                </div>
                            </div>
                            <div class="actions">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-success" style="width: 100%;" type="button" id="sliderOk" >Submit</button>
                                    </div>
                                    <div class="col-sm-6">
                                        <button class="bd-action bd-action-secondary" style="width: 100%;" type="button" id="slideCancer" >Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="slide-wrapper">
                            <div id="carousel_slider_wrapper" class="carousel_slider_wrapper"><?php if($exist && isset($settings['html_slider'])): ?><?php echo html_entity_decode($settings['html_slider']) ?><?php endif ?></div>
                            <textarea style="display: none;" name="setting[html_slider]" id="htmlSlider" maxlength="999999999999"><?php if($exist && isset($settings['html_slider'])): ?><?php echo html_entity_decode($settings['html_slider']) ?><?php endif ?></textarea>
                        </div>
                        <div class="slide-actions">
                            <button type="button" class="btn btn-primary add-new-item"><?php echo __('Add New Slide') ?></button>
                        </div>
                    </div>
                    <div id="slider" class="tab-pane">
                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="fullscreen" class="control-label"><?php echo __('Full Width') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['fullscreen']): ?> checked="checked"<?php endif ?> value="1" name="setting[fullscreen]" id="fullscreen" class="admin__actions-switch-checkbox">
                                    <label for="fullscreen" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="fullheight" class="control-label"><?php echo __('Full Height') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && isset($settings['fullheight']) && $settings['fullheight']): ?> checked="checked"<?php endif ?> value="1" name="setting[fullheight]" id="fullheight" class="admin__actions-switch-checkbox" onclick="setFullheight()">
                                    <label for="fullheight" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element" id="offset-input">
                            <div class="col-sm-4">
                                <label for="offset" class="control-label"><?php echo __('Offset Containers') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" id="offset" class="input-text" name="setting[offset]" <?php if($exist && isset($settings['offset'])): ?> value="<?php echo $settings['offset'] ?>"<?php endif ?>>
                                <p>Example: #header or .header, .footer, #somecontainer | The height of fullscreen slider will be decreased with the height of these Containers to fit perfect in the screen</p>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="effect" class="control-label"><?php echo __('Effect') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <select id="effect" class="input-text" name="setting[effect]">
                                    <option value="1"<?php if($exist && ($settings['effect']==1)): ?> selected="selected"<?php endif ?>><?php echo __('Fade') ?></option>
                                    <option value="2"<?php if($exist && ($settings['effect']==2)): ?> selected="selected"<?php endif ?>><?php echo __('Vertical') ?></option>
                                    <option value="3"<?php if($exist && ($settings['effect']==3)): ?> selected="selected"<?php endif ?>><?php echo __('In Down') ?></option>
                                    <option value="4"<?php if($exist && ($settings['effect']==4)): ?> selected="selected"<?php endif ?>><?php echo __('Left Right') ?></option>
                                </select>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="autoplay" class="control-label"><?php echo __('Auto play') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['autoplay']): ?> checked="checked"<?php endif ?> value="1" name="setting[autoplay]" id="autoplay" class="admin__actions-switch-checkbox" onclick="setAutoplay()">
                                    <label for="autoplay" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element" id="speed-input">
                            <div class="col-sm-4">
                                <label for="speed" class="control-label"><?php echo __('Auto play speed') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" placeholder="ms" id="speed" class="input-text validate-number" name="setting[speed]" <?php if($exist && isset($settings['speed'])): ?> value="<?php echo $settings['speed'] ?>"<?php endif ?>>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="stop_auto" class="control-label"><?php echo __('Stop autoplay on mouse hover') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['stop_auto']): ?> checked="checked"<?php endif ?> value="1" name="setting[stop_auto]" id="stop_auto" class="admin__actions-switch-checkbox">
                                    <label for="stop_auto" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="navigation" class="control-label"><?php echo __('Display nav') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['navigation']): ?> checked="checked"<?php endif ?> value="1" name="setting[navigation]" id="navigation" class="admin__actions-switch-checkbox">
                                    <label for="navigation" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="pagination" class="control-label"><?php echo __('Display dots') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['pagination']): ?> checked="checked"<?php endif ?> value="1" name="setting[pagination]" id="pagination" class="admin__actions-switch-checkbox">
                                    <label for="pagination" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="navtemple" class="control-label"><?php echo __('Nav & Dots Template') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <select id="navtemple" class="input-text" name="setting[navtemple]">
                                    <option value="0"<?php if($exist && ($settings['navtemple']==0)): ?> selected="selected"<?php endif ?>><?php echo __('Basic Teamplate') ?></option>
                                    <option value="1"<?php if($exist && ($settings['navtemple']==1)): ?> selected="selected"<?php endif ?>><?php echo __('Template 1') ?></option>
                                    <option value="2"<?php if($exist && ($settings['navtemple']==2)): ?> selected="selected"<?php endif ?>><?php echo __('Template 2') ?></option>
                                    <option value="3"<?php if($exist && ($settings['navtemple']==3)): ?> selected="selected"<?php endif ?>><?php echo __('Template 3') ?></option>
                                    <option value="4"<?php if($exist && ($settings['navtemple']==4)): ?> selected="selected"<?php endif ?>><?php echo __('Template 4') ?></option>
                                    <option value="5"<?php if($exist && ($settings['navtemple']==5)): ?> selected="selected"<?php endif ?>><?php echo __('Template 5') ?></option>
                                    <option value="6"<?php if($exist && ($settings['navtemple']==6)): ?> selected="selected"<?php endif ?>><?php echo __('Template 6') ?></option>
                                </select>
                            </div>
                        </div>

                        <div class="row fr-element">
                            <div class="col-sm-4">
                                <label for="loop" class="control-label"><?php echo __('Loop') ?></label>
                            </div>
                            <div class="col-sm-8">
                                <div class="admin__actions-switch" data-role="switcher">
                                    <input type="checkbox"<?php if($exist && $settings['loop']): ?> checked="checked"<?php endif ?> value="1" name="setting[loop]" id="loop" class="admin__actions-switch-checkbox">
                                    <label for="loop" class="admin__actions-switch-label">
                                        <span data-text-off="<?php echo __('No') ?>" data-text-on="<?php echo __('Yes') ?>" class="admin__actions-switch-text"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if(!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back" onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>" class="bd-action bd-action-success<?php if($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    var idx = <?php echo $i ?>;
    var AllHTMLCode = '';
    require([
        'jquery',
        ], function($){


            $(document).ready(function(){
                setAutoplay();
                setFullheight();
            });
            $(document).on('change', ".setting_img_checkbox", function () {
                var imgName = $(this).val();
                if(this.checked) {
                    $(this).parent().find('.setting_imgname').val(imgName);
                }else {
                    $(this).parent().find('.setting_imgname').val('');
                }
            });
            $(document).on('change', ".check_remove", function () {
                var imgName = $(this).val();
                if(this.checked) {
                    $(this).parent().find('.remove_img').val('remove');
                }else {
                    $(this).parent().find('.remove_img').val('');
                }
            });

            var slideCounter = parseInt(jQuery("#carousel_slider_wrapper .mgs-image.item").length);
            

            $('.slide-actions .add-new-item').click(function(){
                slideCounter = slideCounter+1;
                $("input#msg-slide-counter").val(slideCounter);
                $('#slide_images li.active').removeClass('active');
                $('#slide_images_mob li.active').removeClass('active');
                $('#slide_video li.active').removeClass('active');
                $('#slide_desktop_img').val('');
                $('#slide_mobile_img').val('');
                $('#slide_mobile_video').val('');
                $('#slide_img_url_video').val('');
                $('#slide_link').val('');
                $('#slide_title').val('');
                $('#slide_button').val('');
                $('#external_video_link').val('');
                $('#external_mobile_video_link').val('');
                $('#video_link').val('');
                $('#slide_html').val('');
                $('#slide_status').val('1');
                $('#slide_html_animation').val('');
                $('#slide .new-slide-popup').addClass('active');
            });

            $('#slideCancer').click(function(){
                $('#slide .new-slide-popup').removeClass('active');
            });

            $('#slide_html_position li').click(function(){
                $('#slide_html_position li.active').removeClass('active');
                $(this).addClass('active');
            });

            $(document).on("click","a.item-image",function( event ) {
                event.preventDefault();
            });


            $(document).on("click","#slide_images:not(.slide-desktop-videos) li",function() {
                $('#slide_images li.active').removeClass('active');
                $('.slide-images.slide-desktop-videos li.active').removeClass('active');
                $(this).addClass('active');
                $('#slide_desktop_img').val($(this).find('.img-fluid').attr('src'));
                $('#slide_desktop_video').val('');
            });

            $(document).on("click","#slide_images_mob li",function() {
                $('#slide_images_mob li.active').removeClass('active');
                $('.slide-images.slide-mobile-videos li.active').removeClass('active');
                $(this).addClass('active');
                $('#slide_mobile_img').val($(this).find('.img-mobile').attr('src'));
                $('#slide_mobile_video').val('');                
            });

            $(document).on("click",".slide-desktop-videos li",function() {
                $('.slide-desktop-videos li.active').removeClass('active');
                $("#slide_images:not(.slide-desktop-videos) li").removeClass('active');
                $(this).addClass('active');
                $('#slide_desktop_video').val($(this).find('.img-fluid').attr('src'));
                $('#slide_desktop_img').val('');
            });

            $(document).on("click",".slide-mobile-videos li",function() {
                $('.slide-mobile-videos li.active').removeClass('active');
                $('#slide_images_mob li.active').removeClass('active');
                $(this).addClass('active');
                // console.log($(this).find('.thumb-video').attr('src'), $('#slide_mobile_video'))
                $('#slide_mobile_video').val($(this).find('.thumb-video').attr('src'));
                $('#slide_mobile_img').val('');
            });

            $(document).on("change","#enable_external_videos",function() {
                var status = jQuery('#enable_external_videos').prop('checked');
                $('#enable_external_video_status').val((status==true?1:0));
            });

            $(document).on("change","#video_link",function() {
                $("input#external_video_link").val($(this).val());
            });

            $(document).on("change","#mobile_video_link",function() {
                $("input#external_mobile_video_link").val($(this).val());
            });


            $(document).on("click","#sliderOk",function() {
                    var enable_external_videos = jQuery("input#enable_external_videos").prop('checked');
                    var $slide_desktop_img = $('#slide_desktop_img').val();
                    var $slide_mobile_img = $('#slide_mobile_img').val();
                    var $slide_desktop_video = $('#slide_desktop_video').val();
                    var $slide_mobile_video = $('#slide_mobile_video').val();
                    var $external_video_link = $('#external_video_link').val();
                    var $external_mobile_video_link = $('#external_mobile_video_link').val();
                    var msg_slide_counter = $('input#msg-slide-counter').val();
                    var $videolink = $("#video_link").val();

                    // console.log("enable_external_videos: "+enable_external_videos,"slide_desktop_img:"+$slide_desktop_img,"slide_mobile_img: "+$slide_mobile_img,"slide_desktop_video: "+$slide_desktop_video,"slide_mobile_video: "+$slide_mobile_video, "external_video_link:" +$external_video_link );
                    var $html = $("#slide_html").val();
                    var $link = $("#slide_link").val();
                    var $title = $("#slide_title").val();
                    var $button = $("#slide_button").val();
                    
                    var $textAnimation = $("#slide_html_animation").val();
                    var $position = $("#slide_html_position li.active").attr('data-position');

                    var $newElement = '<div data-text-position="'+$position+'" data-anchor-link="'+$link+'" data-text-animate="'+$textAnimation+'" class="mgs-image item '+$textAnimation+'" data-msg-slide="'+slideCounter+'" data-external-video="'+enable_external_videos+'"  data-external-desktop-video="'+$external_video_link+'"  data-external-mobile-video="'+$external_mobile_video_link+'" data-mobile-img="'+$slide_mobile_img+'" data-desktop-img="'+$slide_desktop_img+'" data-mp4-desktop="'+$slide_desktop_video+'" data-mp4-mobile="'+$slide_mobile_video+'"  >';


                    if($button == "") {
                        $newElement += '<a  class="item-image" href="'+$link+'" >';
                    } else {
                        $newElement += '<a  class="item-image" href="'+$link+'">';
                    }
                    var mobileData='';
                    var deskopData='';

                    if(enable_external_videos==true){
                        /* else flow */
                        // console.log('complete ELSE case')
                        $newElement += '<video id="external_video" class="external_video img-fluid desktop-only lazy" width="100%" loop="true" playsinline webkit-playsinline muted="true" autoplay="autoplay" poster="">';
                        $newElement += '<source src="'+$external_video_link+'" type="video/mp4"/><source src="'+$external_video_link+'" type="video/webm"/></video>';
                        $newElement += '<video id="external_video_mobile" class="external_video img-fluid mobile-only lazy" width="100%" loop="true" playsinline webkit-playsinline muted="true" autoplay="autoplay" poster="">';
                        $newElement += '<source src="'+$external_mobile_video_link+'" type="video/mp4"/><source src="'+$external_mobile_video_link+'" type="video/webm"/></video>';
                    }
                    else{
                        // console.log($newElement);
                        if($slide_desktop_img !=''){
                            //desktop image
                            // console.log('desktop image')
                            deskopData += '<img class="img-fluid desktop-only lazy" src="'+$slide_desktop_img+'" alt="image" data-src="'+$slide_desktop_img+'"/>';
                        }
                        else{
                            //desktop video                            
                            deskopData += '<video id="myVideoTag" class="img-fluid desktop-only lazy" width="100%" loop="true" playsinline webkit-playsinline muted="true" autoplay="autoplay" poster="">';
                            deskopData += '<source src="'+$slide_desktop_video+'" type="video/mp4"/> <source src="'+$slide_desktop_video+'" type="video/webm"/></video>';
                        }
                        if($slide_mobile_img !=''){
                            //mobile image
                            // console.log('mobile img')
                            mobileData += '<img class="img-mobile mobile-only lazy" src="'+$slide_mobile_img+'" alt="image" data-src="'+$slide_mobile_img+'"/>';     
                        }
                        else{
                            //mobile video
                            // console.log('mobile video')
                            mobileData += '<video id="myVideoTag-mobile" class="img-fluid mobile-only lazy" width="100%" loop="true" playsinline webkit-playsinline muted="true" autoplay="autoplay" poster="">';
                            mobileData += '<source src="'+$slide_mobile_video+'" type="video/mp4"/> <source src="'+$slide_mobile_video+'" type="video/webm"/></video>';
                        }
                    }

                    // console.log('desktop video: ', deskopData)
                    // console.log('Mobile data: ', mobileData)

                    $newElement += deskopData;
                    $newElement += mobileData;                    
                    if($button == "") {
                        $newElement +='</a><div class="contai$videoSlidener"><div class="slide-text '+$position+'"><div class="banner-text"><h2>'+$title+'</h2></div> <div class="inner-text">'+$html+'</div></div></div></div>';
                    } else {
                        $newElement +='</a><div class="contai$videoSlidener"><div class="slide-text '+$position+'"><div class="banner-text"><h2>'+$title+'</h2></div> <div class="inner-text">'+$html+'</div><div class="banner-btn"><a class="textbutt" href="'+$link+'">'+$button+'</a></die></div></div></div>';
                    }

                    
                    // console.log('Status: ', $('#slide_status').val())
                    $(".mgs-image.item[data-msg-slide='"+msg_slide_counter+"']").remove();
                    var cloneSlide = $(".mgs-image.item[data-msg-slide='"+msg_slide_counter+"']").clone();
                    // console.log($('#carousel_slider_wrapper'))
                    $('#carousel_slider_wrapper').append($newElement);
                    // $('#htmlSlider').val($('#carousel_slider_wrapper').html());
                    AllHTMLCode += $('#carousel_slider_wrapper').html();
                    $('#htmlSlider').html('');
                    $('#htmlSlider').html($('#carousel_slider_wrapper').html());
                    // $('#htmlSlider').append($('#carousel_slider_wrapper').html());
                    // console.log($('#htmlSlider'),'Final element: ', $('#htmlSlider').val());
                    
                    $("#slide_actions .btn-info").unbind('click');
                    $("#slide_actions .btn-info").bind('click', function (e) {
                        var index= $editSlide.index();
                        $editSlide.insertAfter($editSlide.next());
                        // $('#htmlSlider').val($('#carousel_slider_wrapper').html());
                    });

                    // console.log($('#carousel_slider_wrapper').html())
                    if($('#slide_status').val() == '1'){
                        /* Create New Slide */

                        $('#carousel_slider_wrapper').find(".item").unbind('hover');
                        $('#carousel_slider_wrapper').find(".item").hover(function (e) {
                            var position = $(this).position()
                            var _top = position.top + 20;
                            var _left = position.left;

                            $("#slide_actions").css("top", _top + "px");
                            $("#slide_actions").css("left", _left + "px");


                            $("#slide_actions").stop(true, true).css({ display: 'none' }).fadeIn(20);

                            var $editSlide = $(this);

                            $("#slide_actions .btn-danger").unbind('click');
                            $("#slide_actions .btn-danger").bind('click', function (e) {
                                if (window.confirm("<?php echo __('Are you sure?'); ?>")) {
                                    $editSlide.remove();
                                    $('#htmlSlider').val($('#carousel_slider_wrapper').html());
                                }
                            });

                            

                            $("#slide_actions .btn-primary").unbind('click');
                            $("#slide_actions .btn-primary").bind('click', function (e) {

                                var $imgSl = $editSlide.find('.img-fluid').attr('src');
                                var $desktop_img = $editSlide.find('.img-fluid.desktop-only').attr('src');
                                var $mobile_img = $editSlide.find('.img-fluid.mobile-only').attr('src');

                                var $imgMo = $editSlide.find('.img-mobile').attr('src');

                                var $viMo = $editSlide.find('.videofluid').attr('src');
                                
                                var $destop_video = $editSlide.find('video.desktop-only').attr('src');
                                var $mobile_video = $editSlide.find('video.mobile-only').attr('src');

                                // console.log("desktop_img: "+$desktop_img,"mobile img: "+$mobile_img)
                                // console.log("desktop_vide: "+$desktop_video,"mobile video: "+$mobile_video)

                                var $linkSl = $editSlide.find('.item-image').attr('href');
                                var $textSl = $editSlide.find('.slide-text .inner-text').html();
                                var $titleSl = $editSlide.find('.slide-text .banner-text h2').html();
                                var $buttonSl = $editSlide.find('.slide-text .banner-btn .textbutt').html();                            
                                var $positionSl = $editSlide.attr('data-text-position');
                                var $aniSl = $editSlide.attr('data-text-animate');


                                var $slide_desktop_img = $('#slide_desktop_img').val();
                                var $slide_mobile_img = $('#slide_mobile_img').val();
                                var $slide_desktop_video = $('#slide_desktop_video').val();
                                var $slide_mobile_video = $('#slide_mobile_video').val();
                                var $external_video_link = $('#external_video_link').val();
                                var $external_mobile_video_link = $('#external_mobile_video_link').val();

                                var $videolinkSl = "";
                                if($editSlide.find('#myVideolink').length>0){
                                 $videolinkSl = $editSlide.find('#myVideolink > source').attr('src');
                             }
                             if($editSlide.find('video#external_video').length>0){
                                 $videolinkSl = $editSlide.find('video#external_video > source').attr('src');
                             }

                             var msg_slide_counter = $editSlide.attr('data-msg-slide');
                                // console.log(msg_slide_counter);
                                $("input#msg-slide-counter").val(msg_slide_counter);

                                $('#slide_images').find('.img-fluid[src$="'+$imgSl+'"]').parent().addClass('active');
                                $('#slide_desktop_img').val($imgSl);
                                $('#slide_images_mob').find('.img-mobile[src$="'+$imgMo+'"]').parent().addClass('active');
                                $('#slide_mobile_video').val($imgMo);
                                $('#slide_video').find('.videofluid[src$="'+$viMo+'"]').parent().addClass('active');
                                $('#slide_img_url_video').val($viMo);

                                $('#slide_link').val($linkSl);
                                $('#slide_title').val($titleSl);
                                $('#slide_button').val($buttonSl);
                                $('#video_link').val($videolinkSl);
                                $('#slide_html').val($textSl);
                                $('#slide_status').val('2');
                                $('#slide_html_position li.active').removeClass('active');
                                $('#slide_html_position').find('li[data-position="'+$positionSl+'"]').addClass('active');
                                $('#slide_html_animation').val($aniSl);
                                $('#slide .new-slide-popup').addClass('active');

                                $("#sliderOk").unbind('click');
                            });

$("#slide_actions").hover(function (e) {
    $(this).stop(true, true).css("display", "block");
}, function () {
    $(this).stop(true, true).fadeOut(0);
});
}, function (e) {
    $("#slide_actions").stop(true, true).fadeOut(0);
});
$('#htmlSlider').val($('#carousel_slider_wrapper').html());
}
$('#slide .new-slide-popup').removeClass('active');

                // }else {
                //     alert('<?php echo __('Please select an image'); ?>');
                // }
            });

$('#carousel_slider_wrapper').find(".item").unbind('hover');
$('#carousel_slider_wrapper').find(".item").hover(function (e) {
    var position = $(this).position()
    var _top = position.top + 20;
    var _left = position.left;

    $("#slide_actions").css("top", _top + "px");
    $("#slide_actions").css("left", _left + "px");


    $("#slide_actions").stop(true, true).css({ display: 'none' }).fadeIn(20);

    var $editSlide = $(this);

    $("#slide_actions .bd-action-danger").unbind('click');
    $("#slide_actions .bd-action-danger").bind('click', function (e) {
        if (window.confirm("<?php echo __('Are you sure?'); ?>")) {
            $editSlide.remove();
            $('#htmlSlider').val($('#carousel_slider_wrapper').html());
        }
    });

    $("#slide_actions .bd-action-info").unbind('click');
    $("#slide_actions .bd-action-info").bind('click', function (e) {
        var index= $editSlide.index();
        $editSlide.insertAfter($editSlide.next());
        console.log($('#htmlSlider'),'#slide_actions .bd-action-info')
        $('#htmlSlider').val($('#carousel_slider_wrapper').html());
    });


    //Action for Edit slide click on blue pencil icon btn
    $("#slide_actions .bd-action-primary").unbind('click');
    $("#slide_actions .bd-action-primary").bind('click', function (e) {

        var $imgSl = $editSlide.find('.img-fluid').attr('src');
        var $imgMo = $editSlide.find('.img-mobile').attr('src');

        var $viMo = $editSlide.find('.videofluid').attr('src');
        // console.log($editSlide.find('video.mobile-only > source'));
        // var $desktop_img = ($editSlide.find('img.img-fluid.desktop-only').attr('src')?$editSlide.find('img.img-fluid.desktop-only').attr('src'):$editSlide.find('img.img-fluid.desktop-only').attr('data-src'));
        // var $mobile_img = ($editSlide.find('img.img-mobile.mobile-only').attr('src')?$editSlide.find('img.img-mobile.mobile-only').attr('src'):$editSlide.find('img.img-mobile.mobile-only').attr('data-src'));

        var $desktop_img = ($editSlide.attr('data-desktop-img'));
        var $mobile_img = ($editSlide.attr('data-mobile-img'));

        // var $desktop_video = $editSlide.find('video.desktop-only:not(.external_video) > source').attr('src');
        // var $mobile_video = $editSlide.find('video.mobile-only:not(.external_video) > source').attr('src');

        var $desktop_video = $editSlide.attr('data-mp4-desktop');
        var $mobile_video = $editSlide.attr('data-mp4-mobile')

        var $external_desktop_video = $editSlide.attr('data-external-desktop-video');
        var $external_mobile_video = $editSlide.attr('data-external-mobile-video');

        var $enable_external_video_status = $editSlide.attr('data-external-video');

        // console.log("desktop_img: "+$desktop_img,"mobile img: "+$mobile_img)
        // console.log("desktop_vide: "+$desktop_video,"mobile video: "+$mobile_video);
        var msg_slide_counter = $editSlide.attr('data-msg-slide');
        // console.log(msg_slide_counter)
        $("input#msg-slide-counter").val(msg_slide_counter);

        var $linkSl = $editSlide.attr('data-anchor-link');
        var $textSl = $editSlide.find('.slide-text .inner-text').html();
        var $titleSl = $editSlide.find('.slide-text .banner-text h2').html();
        var $buttonSl = $editSlide.find('.banner-btn .textbutt').html();
        var $videolinkSl = $editSlide.find('#myVideolink > source').attr('src');
        var $positionSl = $editSlide.attr('data-text-position');
        var $aniSl = $editSlide.attr('data-text-animate');

        $('#slide_images li.active').removeClass('active');
        $('#slide_images').find('img[src$="'+$desktop_img+'"]').parent().addClass('active');

        $('#slide_images_mob li.active').removeClass('active');
        $('#slide_images_mob').find('img[src$="'+$mobile_img+'"]').parent().addClass('active');

        $('.slide-desktop-videos li.active').removeClass('active');
        $('.slide-desktop-videos').find('.thumb-video[src$="'+$desktop_video+'"]').parent().addClass('active');

        $('.slide-mobile-videos li.active').removeClass('active');
        $('.slide-mobile-videos').find('.thumb-video[src$="'+$mobile_video+'"]').parent().addClass('active');

        $('#slide_desktop_img').val($desktop_img);
        $('#slide_mobile_img').val($mobile_img);
        // console.log($mobile_img,$('#slide_images_mob').find('li img.img-mobile[src$="'+$mobile_img+'"]'));
        $('#slide_desktop_video').val($desktop_video);
        $('#slide_mobile_video').val($mobile_video);


        $('#enable_external_video_status').val($enable_external_video_status);
                // console.log($enable_external_video_status)
                if($enable_external_video_status==true || $enable_external_video_status=="true"){
                    // console.log(jQuery('#video_link'),$external_desktop_video)
                    jQuery('#video_link').attr('value',$external_desktop_video);
                    jQuery('#external_video_link').val($external_desktop_video);

                    jQuery('#mobile_video_link').attr('value',$external_mobile_video);
                    jQuery('#external_mobile_video_link').val($external_mobile_video);
                    jQuery('#enable_external_videos').trigger('click');
                    jQuery('#enable_external_videos').attr("checked",'checked');
                }else{

                    jQuery('#video_link').attr('value',$external_desktop_video);
                    jQuery('#external_video_link').val($external_desktop_video);

                    jQuery('#mobile_video_link').attr('value',$external_mobile_video);
                    jQuery('#external_mobile_video_link').val($external_mobile_video);
                    jQuery('#enable_external_videos').attr("checked",false);
                }

                $('#slide_img_url_video').val($viMo);
                $('#slide_link').val($linkSl);
                $('#slide_title').val($titleSl);
                $('#slide_button').val($buttonSl);
                
                $('#slide_html').val($textSl);
                $('#slide_status').val('2');
                $('#slide_html_position li.active').removeClass('active');
                $('#slide_html_position').find('li[data-position="'+$positionSl+'"]').addClass('active');
                $('#slide_html_animation').val($aniSl);
                $('#slide .new-slide-popup').addClass('active');

                $("#sliderOk").unbind('click');

                $("#sliderOk").bind('click', function (e) {
                    var $imgSlide = $('#slide_desktop_img').val();
                    var $imgMobile = $('#slide_mobile_img').val();
                    var $viMobile = $('#slide_img_url_video').val();

                    var $html = $("#slide_html").val();
                    var $link = $("#slide_link").val();
                    var $title = $("#slide_title").val();
                    var $button = $("#slide_button").val();
                    var $videolink = $("#video_link").val();
                    var $textAnimation = $("#slide_html_animation").val();
                    var $position = $("#slide_html_position li.active").attr('data-position');
                    var $oldAnimation = $editSlide.attr('data-text-animate');
                    var $oldPosition = $editSlide.attr('data-text-position');
                    $editSlide.removeClass($oldAnimation);
                    $editSlide.addClass($textAnimation);
                    $editSlide.attr({
                        'data-text-position' : $position,
                        'data-text-animate' : $textAnimation
                    });
                    $editSlide.find('.item-image').removeAttr('style');
                    // $editSlide.find('.item-image').attr('style', 'background-image:url('+$imgSlide+')');

                    // $editSlide.find('.item-image').attr('style', 'background-image:url('+$imgMobile+')');
                    // $editSlide.find('.videofluid').attr('style', 'background-image:url('+$viMobile+')');

                    $editSlide.find('.item-image').attr('href', $link);

                    $editSlide.find('.img-fluid').attr('src', $imgSlide);
                    $editSlide.find('.img-mobile').attr('src', $imgMobile);
                    $editSlide.find('.videofluid').attr('src', $viMobile);

                    $editSlide.find('.slide-text .inner-text').html($html);
                    $editSlide.find('.slide-text .banner-text h2').html($title);
                    $editSlide.find('.slide-text .banner-btn .textbutt').html($button);
                    //$editSlide.find('.videourl').html($videolink);
                    $editSlide.find('#myVideolink > source').attr('src', $videolink);
                    $editSlide.find('.slide-text').removeClass($oldPosition);
                    $editSlide.find('.slide-text').addClass($position);

                    // console.log("SliderOk 2",$('#carousel_slider_wrapper').html());
                    // $('#htmlSlider').val($('#carousel_slider_wrapper').html());
                    $('#slide .new-slide-popup').removeClass('active');
                });
            });

$("#slide_actions").hover(function (e) {
                $(this).stop(true, true).css("display", "block"); // Spy tdk flickr
            }, function () {
                $(this).stop(true, true).fadeOut(0);
            });
}, function (e) {
    $("#slide_actions").stop(true, true).fadeOut(0);
});

});


function setFullheight(){
    require([
        'jquery',
        ], function(jQuery){
            (function($) {
                if($('#fullheight').prop("checked") == true){
                    $('#offset-input').show();
                }else{
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
}

function detectIE() {
    var ua = window.navigator.userAgent;
    var msie = ua.indexOf('MSIE ');
    var trident = ua.indexOf('Trident/');
    var edge = ua.indexOf('Edge/');

    if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function setAutoplay(){
        require([
            'jquery',
            ], function(jQuery){
                (function($) {
                    if($('#autoplay').prop("checked") == true){
                        $('#speed-input').show();
                    }else{
                        $('#speed-input').hide();
                    }
                })(jQuery);
            });
    }

    var currentAnimate = '';
    <?php if($exist): ?>
        currentAnimate = '<?php echo $settings['animation'] ?>';
    <?php endif ?>

    function changeAnimationClass(animate){
        require([
            'jquery',
            ], function(jQuery){
                (function($) {
                    if(currentAnimate!=''){
                        $('#animation-test').removeClass(currentAnimate);
                    }
                    $('#animation-test').addClass(animate);
                    currentAnimate = animate;
                })(jQuery);
            });
    }

    function newImageUpload(){
        require([
            'jquery',
            ], function(jQuery){
                (function($) {
                    if($('#file_upload').length){
                        if($('#upload_button').length){
                            alert('<?php echo __('Please upload selected image first.') ?>');
                        }else{
                            alert('<?php echo __('Please choose file to upload.') ?>');
                        }
                    }else{
                        html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                        $('#list-upload').html(html);
                    }

                })(jQuery);
            });
    }

    function chooseFileAction(elId){
        require([
            'jquery',
            ], function(jQuery){
                (function($) {
                    fileName = $('#'+elId).val();
                    arrName = fileName.split(".");
                    extensionName = arrName[arrName.length - 1];
                    extensionName = extensionName.toLowerCase();
                    if((extensionName=='jpg') || (extensionName=='jpeg') || (extensionName=='png') || (extensionName=='gif') || (extensionName=='mp4') || (extensionName=='ogv') || (extensionName=='wmv') || (extensionName=='avi')){
                        html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                        $('#upload_action').html(html);
                    }
                })(jQuery);
            });
    }

    function uploadImage(){
        require([
            'jquery',
            ], function(jQuery){
                (function($) {
                    idx++;
                    if($('.alert-image-success').length){
                        $('.alert-image-success').remove();
                    }
                    $('#upload-loading').show();
                    $('#upload-icon').hide();
                    var formData = new FormData();
                    formData.append('file', $('#file_upload')[0].files[0]);
                    $.ajax({
                        url: "<?php echo $this->getUrl('mpanel/post/upload', ['type'=>'slider']) ?>",
                        type: "POST",
                        data: formData,
                        contentType: false,
                        cache: false,
                        processData:false,
                        success: function(data){
                            var result = jQuery.parseJSON(data);
                            if(result.result=='success'){
                                var ext = result.data.replace(/^.*\./, '');
                                console.log(ext,(ext=="mp4"));
                                if(ext=="mp4"){
                                    tbhtml = '<li><video class="thumb-video img-fluid" type="video/mp4" controls src="<?php echo $this->getPanelUploadFolder('slider') ?>'+result.data+'" alt="">';
                                    tbhtml += '<source src="<?php echo $this->getPanelUploadFolder('slider') ?>'+result.data+'" type="video/mp4"/></video></li>';
                                }else{
                                    tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('slider') ?>'+result.data+'" alt=""></li>';
                                }


                                html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                tbhtml+
                                '<div class="remove-action">' +
                                '<label for="check-remove-'+idx+'"></label>' +
                                '<input class="check_remove" id="check-remove-'+idx+'" type="checkbox" name="remove[]" value="'+result.data+'"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                                $('#list-images').append(html);
                                $('#slide_images').append(tbhtml);
                                $('#slide_images_mob').append(tbhtml);
                                $('#slide_video').append(tbhtml);
                                $(".panel-image-list").animate({ scrollTop: $('#list-images').height()}, 300);
                            }else{
                                alert(result.data);
                            }

                            $('#list-upload').html('');
                        }
                    });
                })(jQuery);
            });
    }
</script>
<style>
    video.thumb-video{
        width: 135px;
        height: auto;
    }
    video.thumb-video::-webkit-media-controls {
        display: none;
    }

    /* Could Use thise as well for Individual Controls */
    video.thumb-video::-webkit-media-controls-play-button {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-volume-slider {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-mute-button {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-timeline {
        display: none;
    }

    video.thumb-video::-webkit-media-controls-current-time-display {
        display: none;
    }
    .mfp-iframe-holder .mfp-content{
        height: 500px;
    }
</style>


