<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<?php $images = $helper->getPanelUploadImages('pet_products_k9s_for_warriors') ?>
<?php $i = 0; ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2><?php echo __('Pet Products + K9s For Warriors') ?></h2>
        </div>
    </div>
    <form id="section-form" enctype="multipart/form-data" method="POST"
          action="<?php echo $this->getUrl('mpanel/element/save') ?>"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
        <input id="block_type" type="hidden" name="type" value="pet_products_k9s_for_warriors">
        <input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">

        <?php if (isset($params['id'])): ?>
            <?php
            try {
                $child = $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
                $exist = true;
                $settings = json_decode($child->getSetting(), true);
            } catch (Exception $e) {
                echo $e->getMessage();
            }
            ?>
            <input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
        <?php endif ?>


        <div class="form-horizontal">
            <input id="block_html" type="hidden" name="setting[block_link]" value="<?php if ($exist && isset($settings['block_html']) && $settings['block_html']): ?><?php echo $settings['block_html'] ?><?php endif ?>">
            <div id="form_tabs" class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active show" id="images-tab-nav" data-toggle="tab" href="#images"><?php echo __('Manage Images') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="slide-tab-nav" data-toggle="tab" href="#slide"><?php echo __('Settings') ?></a>
                    </li>
                </ul>
                <div class="tab-content">

                    <div id="images" class="tab-pane active">
                        <div id="list-images">
                            <?php if(count($images)>0): ?>
                                <?php $i = 0; foreach($images as $_image): $i++ ?>
                                    <?php
                                    $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                    ?>
                                    <?php
                                    if($ext=="mp4"){ ?>
                                        <div class="image-item" style="width: 120px;height: 70px; margin-right: 10px; margin-bottom: 5px;">
                                            <video class="thumb-video img-fluid" title="<?php echo $_image; ?>" src="<?=$this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image)?>" type="video/mp4" controls="false">
                                                <source src="<?=$this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image)?>" type="video/mp4" />
                                            </video>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } else { ?>
                                        <div class="image-item" style="width: 120px;height: 70px; margin-right: 10px; margin-bottom: 5px;">
                                            <img class="img-fluid" src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image) ?>" alt=""/>
                                            <div class="remove-action">
                                                <label for="check-remove-<?php echo $i ?>"></label>
                                                <input class="check_remove" id="check-remove-<?php echo $i ?>" type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
                                                <input class="remove_img" type="hidden" name="setting[removeimg][]" value="">
                                            </div>
                                        </div>
                                    <?php } ?>

                                <?php endforeach ?>
                            <?php endif ?>
                        </div>
                        <div id="upload-container">
                            <div id="list-upload"></div>
                            <button class="btn btn-default" onclick="newImageUpload()" type="button"><span class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
                        </div>
                    </div>

                    <div id="slide" class="tab-pane">
                        <div id="slide_actions">
                            <button class="bd-action bd-action-info" type="button" title="<?php echo __('Move Down'); ?>"><span class="fa fa-arrow-down"></span>
                            </button>
                            <button class="bd-action bd-action-primary" type="button" title="<?php echo __('Edit'); ?>">
                                <span class="fa fa-pencil"></span></button>
                            <button class="bd-action bd-action-danger" type="button" title="<?php echo __('Remove'); ?>"><span class="fa fa-trash"></span></button>
                        </div>
                        <input type="hidden" class="form-control" id="slide_status" value="1"/>
                        <input type="hidden" class="form-control" id="slide_random_number" value="0"/>

                        <!----------- Section 1 ----------->
                        <div class="form-slide">
                            <div class="form-group">
                                <label style="font-weight: bold; color: #000;">Section Top</label>
                                <label for="slide_link">Title</label>
                                 <input type="text" class="form-control" id="imptitle_one" name="setting[imptitle_one]" <?php if ($exist): ?> value="<?php echo $settings['imptitle_one'] ?>"<?php endif ?>/>
                            </div>

                            <div class="form-group">
                                <label style="font-weight: bold; color: #000;"><?php echo __('Images'); ?></label>
                                <div class="slide_images_wrapper">
                                    <ul id="impslide_images" class="slide-images">
                                        <?php if (count($images) > 0): ?>
                                            <?php $i = 0;
                                            foreach ($images as $_image): $i++ ?>
                                                <?php
                                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext=="png" || $ext == "jpeg" || $ext=="gif"){ ?>
                                                <li style="width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
                                                    <img class="img-fluid" title="<?php echo $_image;?>"
                                                         src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors', $_image) ?>"
                                                         alt=""/></li>
                                                <?php } ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </ul>
                                </div>
                                <input type="hidden" class="form-control" id="impslide_img_url" name="setting[impbackgroundImage]" <?php if ($exist): ?> value="<?php echo $settings['impbackgroundImage'] ?>"<?php endif ?> />
                            </div>

                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                
                                <textarea id="impdesctiption_one"
                                          name="setting[impdesctiption_one]"><?php if ($exist): ?><?php echo $settings['impdesctiption_one'] ?><?php endif ?></textarea>
                            </div>
                            <?php /*
                            <div class="form-group">
                                <label style="font-weight: bold; color: #000;"><?php echo __('Full Video'); ?>:</label>
                                <div class="slide_images_wrapper">
                                    <ul id="impslide_video" class="slide-images">
                                        <?php if(count($images)>0): ?>
                                            <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php
                                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext=="ogv" || $ext == "wmv" || $ext=="avi" || $ext == "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <video class="thumb-video  impvideofluid" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image) ?>" type="mp4/video">
                                                            <source src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image) ?>"  type="video/mp4">
                                                        </video>
                                                    </li>
                                                <?php }
                                                ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </ul>
                                </div>
                                <input type="hidden" class="form-control" id="impslide_img_url_video" name="setting[impbackgroundImagevideo]" <?php if ($exist): ?> value="<?php echo $settings['impbackgroundImagevideo'] ?>"<?php endif ?> />
                            </div>
                            */ ?>

                            <?php /* <div class="form-group">
                                <label style="font-weight: bold; color: #000;"><?php echo __('Preview Video'); ?>:</label>
                                <div class="slide_images_wrapper">
                                    <ul id="impslide_videopriv" class="slide-images">
                                        <?php if(count($images)>0): ?>
                                            <?php $i = 0; foreach($images as $_image): $i++ ?>
                                                <?php
                                                $path = $_image; $ext = pathinfo($path, PATHINFO_EXTENSION);
                                                if($ext=="ogv" || $ext == "wmv" || $ext=="avi" || $ext == "mp4"){ ?>
                                                    <li style="width: 135px;height: 100px; margin-right: 10px;">
                                                        <video class="thumb-video  impvideofluidpriv" title="<?php echo $_image; ?>" src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image) ?>" type="mp4/video">
                                                            <source src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors',$_image) ?>"  type="video/mp4">
                                                        </video>
                                                    </li>
                                                <?php }
                                                ?>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </ul>
                                </div>
                                <input type="hidden" class="form-control" id="impslide_img_url_videopriv" name="setting[impbackgroundImagevideopriv]" <?php if ($exist): ?> value="<?php echo $settings['impbackgroundImagevideopriv'] ?>"<?php endif ?> />
                            </div> 


                            <div class="form-group">
                                <label style="font-weight: bold; color: #000;">Section Bottom</label>
                                <label for="slide_link">Title:</label>
                                <input type="text" class="form-control" id="imptitle_two" name="setting[imptitle_two]" <?php if ($exist): ?> value="<?php echo $settings['imptitle_two'] ?>"<?php endif ?>/>
                            </div>
                            <div class="form-group">
                                <label for="slide_link">Description</label>
                                <input type="text" class="form-control" id="impdesctiption_two" name="setting[impdesctiption_two]" <?php if ($exist): ?> value="<?php echo $settings['impdesctiption_two'] ?>"<?php endif ?>/>
                            </div>

                            */ ?>

                            <div class="form-group">
                                <label style="font-weight: bold; color: #000;"><?php echo __('Bottom Images'); ?></label>
                                <div class="slide_images_wrapper">
                                    <ul id="logoslide_images" class="slide-images">
                                        <?php if (count($images) > 0): ?>
                                            <?php $i = 0;
                                            foreach ($images as $_image): $i++ ?>
                                                <li style="width: 100px;height: 70px;margin-right: 13px;margin-bottom: 5px;">
                                                    <img class="img-fluid" title="<?php echo $_image;?>"
                                                         src="<?php echo $this->getPanelUploadSrc('pet_products_k9s_for_warriors', $_image) ?>"
                                                         alt=""/></li>
                                            <?php endforeach ?>
                                        <?php endif ?>
                                    </ul>
                                </div>
                                <input type="hidden" class="form-control" id="logoslide_img_url" name="setting[logobackgroundImage]" <?php if ($exist): ?> value="<?php echo $settings['logobackgroundImage'] ?>"<?php endif ?> />
                            </div>

                        </div>
                        <!----------- & Section 1 ----------->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 builder-action">
                    <div class="buttons">
                        <?php if (!$exist): ?>
                            <button type="button" class="bd-action bd-action-secondary btn-back"
                                    onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
                        <?php endif ?>
                        <input type="submit" value="<?php echo __('Submit') ?>"
                               class="bd-action bd-action-success<?php if ($exist): ?> bd-action-full<?php endif ?>"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    var idx = <?php echo $i ?>;

    var impselectedImage = <?php  echo($exist ? "'" . $settings['impbackgroundImage'] . "'" : "''")  ?>;
    var logoselectedImage = <?php  echo($exist ? "'" . $settings['logobackgroundImage'] . "'" : "''")  ?>;
    //var impbackgroundImagevideo = <?php  //echo($exist ? "'" . $settings['impbackgroundImagevideo'] . "'" : "''")  ?>;
    //var impbackgroundImagevideopriv = <?php  //echo($exist ? "'" . $settings['impbackgroundImagevideopriv'] . "'" : "''")  ?>;


    require([
        'jquery',
        'mustache',
        'lodash',
        "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function ($, Mustache, _) {

    
        $(document).ready(function () {
            setFullheight();

        wysiwygcompany_impdesctiption_one = new wysiwygSetup("impdesctiption_one", {
            "height": "200px",
            "forced_root_block" : "",
            "force_br_newlines" : true,
            "force_p_newlines" : false,
            "tinymce4": {
                "toolbar": "code | formatselect | sizeselect | bold italic underline | fontselect |  fontsizeselect | alignleft aligncenter alignright | link",
                "plugins": "advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
            }
        });
        wysiwygcompany_impdesctiption_one.setup("exact");


            if (impselectedImage != "") {
                $("#impslide_images > li > img[src='" + impselectedImage + "']").parent().addClass('active');
            }
            if (logoselectedImage != "") {
                $("#logoslide_images > li > img[src='" + logoselectedImage + "']").parent().addClass('active');
            }
            // if (impbackgroundImagevideo != "") {
            //     $("#impslide_video > li >  .impvideofluid[src='" + impbackgroundImagevideo + "']").parent().addClass('active');
            // }
            // if (impbackgroundImagevideopriv != "") {
            //     $("#impslide_videopriv > li >  .impvideofluidpriv[src='" + impbackgroundImagevideopriv + "']").parent().addClass('active');
            // }
        });

        $(document).on('change', ".setting_img_checkbox", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.setting_imgname').val(imgName);
            } else {
                $(this).parent().find('.setting_imgname').val('');
            }
        });
        $(document).on('change', ".check_remove", function () {
            var imgName = $(this).val();
            if (this.checked) {
                $(this).parent().find('.remove_img').val('remove');
            } else {
                $(this).parent().find('.remove_img').val('');
            }
        });
        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#impslide_images li.active').removeClass('active');
        });

        $('#slideCancer').click(function () {
            ClearFormValues();
            $('#slide .new-slide-popup').removeClass('active');
            $('#logoslide_images li.active').removeClass('active');
        });

        // $('#slideCancer').click(function () {
        //     ClearFormValues();
        //     $('#slide .new-slide-popup').removeClass('active');
        //     $('#impslide_video li.active').removeClass('active');
        // });

        // $('#slideCancer').click(function () {
        //     ClearFormValues();
        //     $('#slide .new-slide-popup').removeClass('active');
        //     $('#impslide_videopriv li.active').removeClass('active');
        // });

        $(document).on("click", "a.item-image", function (event) {
            event.preventDefault();
        });
        $(document).on("click", "#impslide_images li", function () {
            $('#impslide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#impslide_img_url').val($(this).find('img').attr('src'));
        });
        $(document).on("click", "#logoslide_images li", function () {
            $('#logoslide_images li.active').removeClass('active');
            $(this).addClass('active');
            $('#logoslide_img_url').val($(this).find('img').attr('src'));
        });
        // $(document).on("click", "#impslide_video li", function () {
        //     $('#impslide_video li.active').removeClass('active');
        //     $(this).addClass('active');
        //     $('#impslide_img_url_video').val($(this).find('.impvideofluid').attr('src'));
        // });

        // $(document).on("click", "#impslide_videopriv li", function () {
        //     $('#impslide_videopriv li.active').removeClass('active');
        //     $(this).addClass('active');
        //     $('#impslide_img_url_videopriv').val($(this).find('.impvideofluidpriv').attr('src'));
        // });

    });
    function setFullheight() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#fullheight').prop("checked") == true) {
                    $('#offset-input').show();
                } else {
                    $('#offset-input').hide();
                }
            })(jQuery);
        });
    }
    function detectIE() {
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf('MSIE ');
        var trident = ua.indexOf('Trident/');
        var edge = ua.indexOf('Edge/');

        if (msie > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
        }

        if (edge > 0) {
            // IE 10 or older => return version number
            return parseInt(ua.substring(edge + 5, ua.indexOf('.', edge)), 10);
        }

        if (trident > 0) {
            // IE 11 (or newer) => return version number
            var rv = ua.indexOf('rv:');
            return parseInt(ua.substring(rv + 3, ua.indexOf('.', rv)), 10);
        }

        // other browser
        return false;
    }

    function newImageUpload() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                if ($('#file_upload').length) {
                    if ($('#upload_button').length) {
                        alert('<?php echo __('Please upload selected image first.') ?>');
                    } else {
                        alert('<?php echo __('Please choose file to upload.') ?>');
                    }
                } else {
                    html = '<div class="row">' +
                        '<div class="col-sm-4 choose-file-upload">' +
                        '<input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)">' +
                        '<span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span>' +
                        '</div>' +
                        '<div class="col-sm-8" id="upload_action"></div>' +
                        '</div>';
                    $('#list-upload').html(html);
                }

            })(jQuery);
        });
    }

    function chooseFileAction(elId) {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                fileName = $('#' + elId).val();
                arrName = fileName.split(".");
                extensionName = arrName[arrName.length - 1];
                extensionName = extensionName.toLowerCase();
                if((extensionName=='jpg') || (extensionName=='jpeg') || (extensionName=='png') || (extensionName=='gif') || (extensionName=='mp4') || (extensionName=='ogv') || (extensionName=='wmv') || (extensionName=='avi')){
                    html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
                    $('#upload_action').html(html);
                }
            })(jQuery);
        });
    }

    function uploadImage() {
        require([
            'jquery',
        ], function (jQuery) {
            (function ($) {
                idx++;
                if ($('.alert-image-success').length) {
                    $('.alert-image-success').remove();
                }
                $('#upload-loading').show();
                $('#upload-icon').hide();
                var formData = new FormData();
                formData.append('file', $('#file_upload')[0].files[0]);
                $.ajax({
                    url: "<?php echo $this->getUrl('mpanel/post/upload', ['type' => 'pet_products_k9s_for_warriors']) ?>",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function (data) {
                        var result = jQuery.parseJSON(data);
                        if (result.result == 'success') {
                            tbhtml = '<li><img src="<?php echo $this->getPanelUploadFolder('pet_products_k9s_for_warriors') ?>' + result.data + '" alt=""></li>';
                            html = '<div class="col-xs-3">' +
                                '<div class="image-item">' +
                                '<img class="img-fluid" src="<?php echo $this->getPanelUploadFolder('pet_products_k9s_for_warriors') ?>' + result.data + '" alt=""/>' +
                                '<div class="remove-action">' +
                                '<label for="check-remove-' + idx + '"></label>' +
                                '<input class="check_remove" id="check-remove-' + idx + '" type="checkbox" name="remove[]" value="' + result.data + '"/>' +
                                '<input class="remove_img" type="hidden" name="setting[removeimg][]" value="">' +
                                '</div>' +
                                '</div>' +
                                '</div>';
                            $('#list-images').append(html);
                            $('#slide_images').append(tbhtml);
                            $('#impslide_images').append(tbhtml);
                            $('#logoslide_images').append(tbhtml);
                            $(".panel-image-list").animate({scrollTop: $('#list-images').height()}, 300);
                        } else {
                            alert(result.data);
                        }

                        $('#list-upload').html('');
                    }
                });
            })(jQuery);
        });
    }
</script>