<?php

/**
 * @category   Biztech
 * @package    Biztech_Tooltip
 * @author     employee@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Biztech\DesignTemplates\Ui\Component\Listing\Column;

class TemplateCategory extends \Magento\Ui\Component\Listing\Columns\Column {

    const URL_PATH_EDIT = 'designtemplates/designtemplates/edit';
    protected $_urlBuilder;
    protected $_designtemplateCategory;
    protected $_product;
    public function __construct(
    \Magento\Framework\UrlInterface $urlBuilder, \Magento\Framework\View\Element\UiComponent\ContextInterface $context, \Magento\Framework\View\Element\UiComponentFactory $uiComponentFactory, \Biztech\DesignTemplates\Model\Mysql4\Designtemplatecategory\Collection $designtemplateCategory, \Magento\Catalog\Model\Product $product, array $components = [], array $data = []
    ) {
        $this->_urlBuilder = $urlBuilder;
        $this->_designtemplateCategory = $designtemplateCategory;
        $this->_product = $product;
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }
    /*
     * * For get category name in design templates grid
     */
    public function prepareDataSource(array $dataSource) {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                $templates_data = [];
                foreach ($this->_designtemplateCategory as $templateCat) {
                    if ($templateCat != '' || $templateCat != null) {
                        $templates = explode(",", $templateCat->getDesigns());
                        if (in_array($item['designtemplates_id'], $templates)) {
                            $templates_data[] = $templateCat->getCategoryTitle();
                        }
                    }
                }
                $item[$this->getData('name')] = implode(", ", $templates_data);
            }
        }
        return $dataSource;
    }

}
