<?php
$helper = $this->helper('MGS\Guestwishlist\Helper\Data');
$items = $helper->getWishlistItemCollection();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$image = 'wishlist_thumbnail';
$padding = $themeHelper->getImagePadding();
$size = $themeHelper->getImageSize();
?>

<div class="products wrapper wishlist grid products-grid">
    <?php $iterator = 1; ?>
    <?php if (count($items)): ?>
            <ol class="product-items row row-wrapper row-4">
                <?php foreach ($items as $item): ?>
                    <?php
                    $_product = $item['product'];
                    $productUrl = $_product->getUrlModel()->getUrl($_product, []);
                    ?>
                    <li class="product-wishlist-items item product product-item  col">
						<div class="product-item-info" data-container="product-grid">
							<div class="product-item-image">
								<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
								<a href="<?php echo $block->escapeUrl($productUrl) ?>" style="padding-bottom: <?php echo $padding; ?>" class="product photo product-item-photo" tabindex="-1">
									<img src="<?php echo $productImage ?>" alt="<?php echo $block->stripTags($_product->getName(), null, true); ?>" class="img-fluid product-image-photo"/>
									<span class="product-image-photo"></span>
								</a>
								<?php echo $themeHelper->getProductLabel($_product) ?>
								
								<button class="action remove" href="javascript:void(0);" data-post='<?php echo $helper->getDeleteItemParams($item, $_product) ?>'><span class="ti-close"></span></button>
								
							</div>
							<div class="text-center padding-top20">
								<h5 class="product name product-item-name">
									<a class="h6 product-item-link" href="<?php echo $block->escapeUrl($productUrl) ?>"><?php echo $block->stripTags($_product->getName(), null, true); ?></a>
								</h5>	
								<div class="product-buy_info">
									<div class="price-box price-configured_price">
										<p class="price-as-configured">
											<span class="price-container price-configured_price tax weee">
												<span data-price-type="finalPrice" class="price-wrapper ">
													<span class="price"><?php echo $helper->formatPrice($_product->getFinalPrice()) ?></span>
												</span>
											</span>
										</p>
									</div>
								</div>
							    <?php if ($_product->isSaleable()): ?>
                                        <div class="actions-primary margin-top10">
                                            <button type="button" data-role="tocart" data-post='<?php echo $item['data_post'] ?>' title="<?php echo __('Add to Cart') ?>" data-item-id="<?php echo $item['item_id'] ?>" class="action tocart primary">
                                                <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </div>
								<?php endif ?>
                                <?php if (isset($item['wishlist_options'])): ?>
                                    <div class="product-item-tooltip">
                                        <?php echo $item['wishlist_options']; ?>
                                    </div>
                                <?php endif; ?>
						    </div>
						</div>
                    </li>
                <?php endforeach; ?>
            </ol>
			<div class="actions-toolbar">
				<div class="primary">
					<button type="button" data-role="tocart" data-post='<?php echo $helper->getAddAllCartParams() ?>' title="<?php echo __('Add All to Cart') ?>" class="btn btn-secondary action tocart">
						<span><?php echo __('Add All to Cart') ?></span>
					</button>
				</div>
			</div>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>
