<?php
/**
 * Copyright © 2017-2018 AppJetty. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \Biztech\Productdesigner\Block\System\Config\Collect */ ?>
<script type="text/javascript">
    //<![CDATA[
    function changelocale() {

        new Ajax.Request('<?php echo $this->getUrl('productdesigner/system_config/locale/'); ?>', {
            method: 'get',
            onSuccess: function (transport) {
                alert('Locale changed successfully.');
            }
        });
    }
</script>
<?php echo $block->getButtonHtml() ?>
