<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script src='<?= $block->escapeUrl($block->getUrl('media/mgs/js/')) ?>simpleParallax.min.js'></script>
<script src='<?= $block->escapeUrl($block->getUrl('media/mgs/js/')) ?>instafeed.min.js'></script>
<script>
	var BASE_URL = WEB_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
	var RTL = false;
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
