<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baurl = $storeManager->getStore()->getBaseUrl();
?>
<?php echo $this->getLayout()->createBlock("Godogi\Faq\Block\Faq")->setTemplate("Godogi_Faq::search_form.phtml")->toHtml();?>
<div class="container">
    <div class="breadcrumb-section">
     <h1></h1>
     <ol class="breadcrumb">
       <li><a href="<?php echo $baurl; ?>">Home</a></li>
       <li><a href="<?php echo $baurl; ?>customer-service">Help Center</a></li>
       <li>Return Policy</li>
     </ol>  
   </div>
 </div>
<div class="container">
    <div class="account-overview-title">
        <h2>Return Policy</h2>
        <div class="row">
            <div class="col-sm-3">
                <nav class="nav-sidebar">
                    <ul class="nav tabs">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('helpcenter_left_nav')->toHtml(); ?>
                    </ul>
                </nav>
            </div>
            <div class="col-md-9">
                <div class="artwork-right-part">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('return_policy')->toHtml(); ?>
                </div>
                <div class="return-policy-account-table" id="tag">
                    <div class="return-policy-account-table">
                        <p>Fill out the form below to start a return </p>

                        <form action="<?php echo $block->getBaseUrl().'returnpolicy/index/post';?>" enctype='multipart/form-data'  name="customemaildata" method="post" id="my_captcha_form" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>

                        <div class="rtn-account-info">
                            <div class="account-information">
                                <h2 class="account-overview-name">1. Account information</h2>
                                <div class="account-overview-tabing">
                                    <div class="row">

                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>ASI # / Account #</label>
                                                <input class="" type="text" id=""  name="asi_account" placeholder="" >
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>PO #</label>
                                                <input class="" type="text" id=""  name="rtn_po" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>SO #</label>
                                                <input class="" type="text" id=""  name="rtn_so" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="artwork-form">
                                                <label>Tax ID Number</label>
                                                <input class="" type="text" id="" name="tax_id_number" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="artwork-form">
                                                <label>Business Name</label>
                                                <input class="" type="text" id="" name="rtn_businessname" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="artwork-form">
                                                <label>Customer Name</label>
                                                <input class="" type="text" id="" required="" name="rtn_customername" placeholder="">
                                            </div>
                                        </div>
                                        <!-- <div class="account-info-button">
                                            <div class="next-button">
                                                <a href="#">Next</a>
                                            </div>
                                        </div> -->
                                    </div>
                                </div>
                            </div>
                            
                            <div class="account-information">
                                <h2 class="Account-overview-name">2. CONTACT INFORMATION</h2>
                                <div class="account-overview-tabing">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="artwork-form">
                                                <label>Email Address</label>
                                                <input class="" type="email" id="email" name="email_address" placeholder="" data-validate="{required:true, 'validate-email':true}">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="artwork-form">
                                                <label>Phone Number:</label>
                                                <input type="text" name="phone" class="phone_us" required="" maxlength="14">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="artwork-form">
                                                <label>Street Address:</label>
                                                <input class="" type="text" id="" name="company_address" placeholder="" >
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>City:</label>
                                                <input class="" type="text" id=""  name="city" required="" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>State:</label>
                                                <!-- <input class="" type="text" id="" name="state" placeholder=""> -->
                                                <select name="state" >
                                                    <option value="">---</option>
                                                    <option value="Alabama">Alabama</option>
                                                    <option value="Alaska">Alaska</option>
                                                    <option value="Arizona">Arizona</option>
                                                    <option value="Arkansas">Arkansas</option>
                                                    <option value="California">California</option>
                                                    <option value="Colorado">Colorado</option>
                                                    <option value="Connecticut">Connecticut</option>
                                                    <option value="Delaware">Delaware</option>
                                                    <option value="District of Columbia">District of Columbia</option>
                                                    <option value="Florida">Florida</option>
                                                    <option value="Georgia">Georgia</option>
                                                    <option value="Guam">Guam</option>
                                                    <option value="Hawaii">Hawaii</option>
                                                    <option value="Idaho">Idaho</option>
                                                    <option value="Illinois">Illinois</option>
                                                    <option value="Indiana">Indiana</option>
                                                    <option value="Iowa">Iowa</option>
                                                    <option value="Kansas">Kansas</option>
                                                    <option value="Kentucky">Kentucky</option>
                                                    <option value="Louisiana">Louisiana</option>
                                                    <option value="Maine">Maine</option>
                                                    <option value="Maryland">Maryland</option>
                                                    <option value="Massachusetts">Massachusetts</option>
                                                    <option value="Michigan">Michigan</option>
                                                    <option value="Minnesota">Minnesota</option>
                                                    <option value="Mississippi">Mississippi</option>
                                                    <option value="Missouri">Missouri</option>
                                                    <option value="Montana">Montana</option>
                                                    <option value="Nebraska">Nebraska</option>
                                                    <option value="Nevada">Nevada</option>
                                                    <option value="New Hampshire">New Hampshire</option>
                                                    <option value="New Jersey">New Jersey</option>
                                                    <option value="New Mexico">New Mexico</option>
                                                    <option value="New York">New York</option>
                                                    <option value="North Carolina">North Carolina</option>
                                                    <option value="North Dakota">North Dakota</option>
                                                    <option value="Northern Marianas Islands">Northern Marianas Islands</option>
                                                    <option value="Ohio">Ohio</option>
                                                    <option value="Oklahoma">Oklahoma</option>
                                                    <option value="Oregon">Oregon</option>
                                                    <option value="Pennsylvania">Pennsylvania</option>
                                                    <option value="Puerto Rico">Puerto Rico</option>
                                                    <option value="Rhode Island">Rhode Island</option>
                                                    <option value="South Carolina">South Carolina</option>
                                                    <option value="South Dakota">South Dakota</option>
                                                    <option value="Tennessee">Tennessee</option>
                                                    <option value="Texas">Texas</option>
                                                    <option value="Utah">Utah</option>
                                                    <option value="Vermont">Vermont</option>
                                                    <option value="Virginia">Virginia</option>
                                                    <option value="Virgin Islands">Virgin Islands</option>
                                                    <option value="Washington">Washington</option>
                                                    <option value="West Virginia">West Virginia</option>
                                                    <option value="Wisconsin">Wisconsin</option>
                                                    <option value="Wyoming">Wyoming</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>Zip Code:</label>
                                                <input class="" type="number" id="" required="" name="zip_code" placeholder="" maxlength="6">
                                            </div>
                                        </div>

                                       <!--  <div class="account-info-button">
                                            <div class="previous-button">
                                                <a href="#">Previous</a>
                                            </div>
                                            <div class="next-button">
                                                <a href="#">Next</a>
                                            </div>
                                        </div> -->

                                    </div>
                                </div>
                            </div>

                            <div class="account-information">
                                <h2 class="account-overview-name">3. PRODUCT INFORMATION</h2>
                                <div class="account-overview-tabing">
                                        <div class="wrapper wrapper-add-fields">
                                            <div class="row">
                                                <div class="col-lg-3">
                                                    <div class="artwork-form">
                                                        <label>Product Number#:</label>
                                                        <input class="" type="text" id=""  required="" name="item_1" placeholder="">
                                                    </div>
                                                </div>
                                                <div class="col-lg-9">
                                                    <div class="artwork-form des-main-title">
                                                        <label>Item Description:</label>
                                                        <textarea class="textarea-return"  required="" name="item_description_1" ></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <div class="row">

                                        <div class="col-lg-12">
                                            <button class="add_fields">Add Another item</button>
                                        </div>
                                        <!-- <div class="col-lg-12">
                                            <div class="artwork-form">
                                                <label>Reason For Return:</label>
                                                <textarea class="textarea-return" name="reason_return"></textarea>
                                            </div>
                                        </div> -->
                                        <div class="col-lg-12">
                                            <div class="artwork-form return-checkbox">
                                                <p>Do we need to issue a DM:</p>
                                                <div class="needtodm">
                                                    <div class="select-section-radio">
                                                    <input id="RdYes" type="radio" name="yesno" value="Yes"> 
                                                    <label for="RdYes">Yes</label>
                                                    </div>
                                                    <div class="select-section-radio">
                                                    <input id="RdNo" type="radio" name="yesno" value="No">
                                                    <label for="RdNo">No</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>Debit Memo #:</label>
                                                <input class="" type="text" id=""  name="debit_memo" placeholder="" >
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>Printer Po #:</label>
                                                <input class="" type="text" id=""  name="printer_po" placeholder="">
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="artwork-form">
                                                <label>Printer:</label>
                                                <input class="" type="text" id=""  name="printer" placeholder="">
                                            </div>
                                        </div>
                                        <div class="introduction-return">
                                            <p>*Note:Your Replacement Order will be shipped upon receiving returned merchandise.</p>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="artwork-form">
                                                <label>Additional Details / Notes:</label>
                                                <textarea class="textarea-return" name="additional_notes"></textarea>
                                            </div>
                                        </div>
                                        <div class="account-info-button">
                                           <!--  <div class="previous-button">
                                                <a href="#">Previous</a>
                                            </div> -->

                                            <div class="nextt-button last-button">
                                                <input type="button" class="review-btn" name="submit" value="Review Summary">
                                                <!-- <a href="#">Review Summary</a> -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="btm-title-section account-information" style="display: none;">
                                <h2 class="account-overview-name">4. Summary</h2>
                                <div class="account-overview-tabing">
                                    <div class="row">
                                <div class="col-lg-12 summary-text">
                                    <div class="summery-content">
                                        <label>Please riview the following information and click submit to start your return process with Sweda</label>
                                        <p class="asi_account"><strong>ASI # / Account # :  </strong><span class="val"></span></p>
                                        <p class="rtn_po"><strong>PO # :  </strong><span class="val"></span></p>
                                        <p class="rtn_so"><strong>SO # :  </strong><span class="val"></span></p>
                                        <p class="rtn_businessname"><strong>Business Name :  </strong><span class="val"></span></p>
                                        <p class="rtn_customername"><strong>Customer Name :  </strong><span class="val"></span></p>
                                        <p class="email_address"><strong>Email Address : </strong><span class="val"></span></p>
                                        <p class="phone"><strong>Phone :  </strong><span class="val"></span></p>
                                        <p class="company_address"><strong>Company Address :  </strong><span class="val"></span></p>
                                        <p class="city"><strong>City :  </strong><span class="val"></span></p>
                                        <p class="state"><strong>State :  </strong><span class="val"></span></p>
                                        <p class="zip_code"><strong>Zip Code :  </strong><span class="val"></span></p>
                                        <p class="item_1"><strong>Product Number # :  </strong><span class="val"></span></p>
                                        <p class="item_description_1"><strong>Description :  </strong><span class="val"></span></p>
                                        <!-- <p class="reason_return"><strong>Reason For Return :  </strong><span class="val"></span></p> -->
                                        <p class="yesno"><strong>Do we need to issue a DM :  </strong><span class="val"></span></p>
                                        <p class="debit_memo"><strong>Debit Memo # :  </strong><span class="val"></span></p>
                                        <p class="printer_po"><strong>Printer Po # :  </strong><span class="val"></span></p>
                                        <p class="printer"><strong>Printer :  </strong><span class="val"></span></p>
                                        <p class="additional_notes"><strong>Additional Details / Notes :  </strong><span class="val"></span></p>
                                        <div class="bottom-edits">
                                           <a href="#tag">Edit</a>
                                        </div>
                                    </div>
                                    
                                            <div class="return-policy-bottom">
                                                <input type="checkbox" id="btn-chk" name="yes" required="" value="I hereby certify that all the information above is correct"> 
                                                <label id="btn-chk">I hereby certify that all the information above is correct</label>
                                            </div>
                                        
                                    <div class="submit-wrapper">
                                        <button class="secondary-submit" type="submit" value="Submit">Submit</button>
                                    </div>
                                </div>
<!-- 
                                        <div class="account-info-button">
                                            <div class="previous-button">
                                                <a href="#">Previous</a>
                                            </div>
                                        </div> -->
                                    </div>
                                </div>

                            </div>
                        </div>

                    </form>
                    </div>
                </div>
            </div>
       </div>
    </div>       
</div>
<!------ Account-overview-section --------->

<script type="text/javascript">
require([
    'jquery',
    'mask',
], function($){

    $(document).ready(function(){


        //// Add Multipal Field    
        var max_fields = 50; 
        var wrapper    = $(".wrapper");
        var add_button = $(".add_fields");
        var x = 1;
        $(add_button).click(function(e){
            e.preventDefault();
            if(x < max_fields){ 
                x++; 
                $(wrapper).append('<div class="row"><div class="col-lg-3"><label>Item#:</label><input class="policy-information" type="text" id="" name="item[]" placeholder=""></div><div class="col-lg-9"><label>Item Description:</label><textarea class="textarea-return  policy-information" name="item_description[]" ></textarea></div><a href="javascript:void(0);" class="remove_field col-lg-12">Remove</a></div>');
            }
        });
        $(wrapper).on("click",".remove_field", function(e){ 
            e.preventDefault();
            $(this).parent('div').remove();
        x--;
        })

        //// Masking Field 
        $('.date').mask('00/00/0000',{placeholder: "dd/mm/yyyy"});
        $('.time').mask('00:00:00');
        $('.phone').mask('0000-0000');
        $('.phone_us').mask('(000) 000-0000',{placeholder: "(000) 000-0000"});

        $('.placeholder').mask("00/00/0000", {placeholder: "__/__/____"});
        $('.fallback').mask("00r00r0000", {
          translation: {
            'r': {
              pattern: /[\/]/,
              fallback: '/'
            },
            placeholder: "__/__/____"
          }
        });
        $('.selectonfocus').mask("00/00/0000", {selectOnFocus: true});
        var SPMaskBehavior = function (val) {
          return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
          onKeyPress: function(val, e, field, options) {
              field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };
        $('.sp_celphones').mask(SPMaskBehavior,{placeholder: "(00) 00000-0000"});

        var FaxMaskBehavior = function (val) {
          return val.replace(/\D/g, '').length === 11 ? '0-000-0000000' : '0-000-0000000';
        },
        spOptions = {
          onKeyPress: function(val, e, field, options) {
              field.mask(FaxMaskBehavior.apply({}, arguments), options);
            }
        };
        $(".fax").mask(FaxMaskBehavior,{placeholder: "_-___-_______"});
    });


    $(document).ready(function() {
        $('.return').addClass('active');
    });

     $(document).ready(function() {   
      
        var SummeryContent = $('.summery-content');
        var eleP = '';

      // $('.next-button a').on('click',function(e){
      //   e.preventDefault();        

      //   var currentTab = $(this).parents('.account-information');
      //   currentTab.find('.account-overview-tabing').slideUp('slow');
      //   var nextTab = currentTab.next();
      //   nextTab.find('.account-overview-tabing').slideDown('slow');

      // })
      $('button.secondary-submit').on('click',function(e){
        $("form[name='customemaildata']").submit();
      });

      $('.last-button .review-btn').on('click',function(e){

        var validator = $("form[name='customemaildata']").validate();
        if(validator.form()){



        // console.log('this is last bitton')
        $('.account-information').show();
        e.preventDefault();

        var accNoVal = $("input[name='asi_account']").val();
        SummeryContent.find('p.asi_account span.val').text(accNoVal);

        var SoNOVal = $("input[name='rtn_so']").val();
        SummeryContent.find('p.rtn_so span.val').text(SoNOVal);

        var PoNoVal = $("input[name='rtn_po']").val();
        SummeryContent.find('p.rtn_po span.val').text(PoNoVal);

        var EmailAddressVal = $("input[name='email_address']").val();
        SummeryContent.find('p.email_address span.val').text(EmailAddressVal);
        
        var PhoneVal = $("input[name='phone']").val();
        SummeryContent.find('p.phone span.val').text(PhoneVal);

        var ComaddVal = $("input[name='company_address']").val();
        SummeryContent.find('p.company_address span.val').text(ComaddVal);

        var CityVal = $("input[name='city']").val();
        SummeryContent.find('p.city span.val').text(CityVal);

        var StateVal = $("select[name='state']").val();
        SummeryContent.find('p.state span.val').text(StateVal);

        var StateVal = $("input[name='state']").val();
        SummeryContent.find('p.state span.val').text(StateVal);

        var ZipcodeVal = $("input[name='zip_code']").val();
        SummeryContent.find('p.zip_code span.val').text(ZipcodeVal);

        var Item_1Val = $("input[name='item_1']").val();
        SummeryContent.find('p.item_1 span.val').text(Item_1Val);

        var ItemDescVal = $("textarea[name='item_description_1']").val();
        SummeryContent.find('p.item_description_1 span.val').text(ItemDescVal);

        // var ReasonVal = $("textarea[name='reason_return']").val();
        // SummeryContent.find('p.reason_return span.val').text(ReasonVal);

        var YesVal = $("input[name='yesno']:checked").val();
        SummeryContent.find('p.yesno span.val').text(YesVal);

        var DebitVal = $("input[name='debit_memo']").val();
        SummeryContent.find('p.debit_memo span.val').text(DebitVal);

        var PrinterpoVal = $("input[name='printer_po']").val();
        SummeryContent.find('p.printer_po span.val').text(PrinterpoVal);

        var PrinterVal = $("input[name='printer']").val();
        SummeryContent.find('p.printer span.val').text(PrinterVal);

        var AdditiNotesVal = $("textarea[name='additional_notes']").val();
        SummeryContent.find('p.additional_notes span.val').text(AdditiNotesVal);

        var BusinessVal = $("input[name='rtn_businessname']").val();
        SummeryContent.find('p.rtn_businessname span.val').text(BusinessVal);

        var CustomerNameVal = $("input[name='rtn_customername']").val();
        SummeryContent.find('p.rtn_customername span.val').text(CustomerNameVal);

}else{
            
        }
      })

      // $('.previous-button a').on('click',function(e){
      //   e.preventDefault();
      //   var currentTab = $(this).parents('.account-information');
      //   currentTab.find('.account-overview-tabing').slideUp('slow');
      //   var nextTab = currentTab.prev();
      //   nextTab.find('.account-overview-tabing').slideDown('slow')
      // })

    });

});
</script>
<style type="text/css">
    .rtn-account-info .account-information .account-overview-tabing {
    display: block;
}
.wrapperaddfields{width: 100%;}

.textarea-return{
    min-height: 35px !important;
    height: 35px;
    border-radius: 0px;
}

</style>