<?php $images = $this->getWidgetInstagramData() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>

<?php 
	ini_set('default_socket_timeout', 900);
	$helper = $this->helper('MGS\Social\Helper\Data');
	$access_token = $helper->getConfig('instagram_setting/access_token');  
	$result = file_get_contents("https://api.instagram.com/v1/users/self?access_token={$access_token}");
	$data = json_decode($result, true);
?>
<div class="content-block instagram-block">

	<?php // Block title ?>
    <?php $title = $this->getData('mgs_panel_title'); ?>
    <?php $subTitle = $this->getData('mgs_panel_note'); ?>
    <?php if($title != "" || $subTitle != ""): ?>
		<div class="content-heading">
			<?php if($title && $title != ""): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($title) ?></h3>
			<?php endif ?>
			<?php if($subTitle && $subTitle != ""): ?>
				<div class="subtitle hashtag"><?php echo $themeHelper->decodeHtmlTag($subTitle) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
    
	<?php // Block Content ?>
	<?php if(count($images)>0): ?>
    <?php $padding = $this->getPadding(); ?>
	<?php 
		$blockId = rand() . time();
		$useSlider = $this->getUseSlider();
		$perRow = $this->getPerrow(); 
		if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
			$columnCount = $perRow * $this->getNumberRow();
		}
		$col = $themeHelper->convertPerRowtoCol($perRow);
		$autoPlay = $this->getAutoplay() ? 'true' : 'false';
		$stopAuto = $this->getStopAuto() ? 'true' : 'false';
		$nav = $this->getNavigation() ? 'true' : 'false';
		$dot = $this->getPagination() ? 'true' : 'false';
	?>
    <div class="instagram-widget-wrapper <?php if($this->getPagination()): ?> has-dot<?php endif ?><?php if($useSlider): ?> instagram-widget-slider<?php endif ?>">
		<?php if($useSlider): ?>
			<div class="row">
				<div id="instagram-widget<?php echo $blockId ?>" class="owl-carousel<?php if($padding): ?> disable-padding<?php endif ?>">
					<?php $i=0; $j=0; foreach($images as $image): $i++; ?>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							<?php if ($j++ % $columnCount == 0): ?>
								<div class="item row">
							<?php endif ?>
							<div class="multiple-row instagram-item-col <?php echo $themeHelper->convertColClass($col, 'col') ?>">
						<?php endif ?>
							<div class="instagram-item-col instagram-item<?php if(!$this->getLike() && !$this->getComment()): ?> hover-effect<?php endif ?><?php if($this->getLink()): ?> enable-link<?php endif ?>">
								<?php if($this->getLink()): ?>
									<a href="<?php echo $image['link'] ?>" target="_blank">
								<?php endif ?>
									<?php if(!$lazyLoad): ?>
										<?php $baseImage = $image['src']; ?>
									<?php endif ?>
									<img class="img-fluid<?php if($lazyLoad): ?> owl-lazy<?php endif ?>" src="<?php echo $baseImage ?>" data-src="<?php echo $image['src'] ?>" alt=""/>
								
								<?php if($this->getLink()): ?>
									</a>
								<?php endif ?>
								
								<?php if($this->getLike() || $this->getComment()): ?>
									<span class="social-count">
										<?php if($this->getLike()): ?>
											<span class="like-count"><span class="ti-heart"></span><span class="number"><?php echo $image['like'] ?></span></span>
										<?php endif ?>
										
										<?php if($this->getComment()): ?>
											<span class="comment-count"><span class="ti-comment-alt"></span><span class="number"><?php echo $image['comment'] ?></span></span>
										<?php endif ?>
									</span>
								<?php endif ?>
							</div>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							</div>
							<?php if ($j % $columnCount == 0 || $j == count($images)): ?>
								</div>
							<?php endif ?>
						<?php endif ?>
					<?php endforeach ?>
				</div>
			</div>
			<?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
				<?php $perRow = 1; ?>
			<?php endif ?>
			<script type="text/javascript">
				require([
					'jquery',
					'mgs/owlcarousel'
				], function ($) {
					var owlinstagram<?php echo $blockId ?> = $('#instagram-widget<?php echo $blockId ?>').owlCarousel({
						items: <?php echo $perRow; ?>,
						autoplay: <?php echo $autoPlay ?>,
						autoplayHoverPause: <?php echo $stopAuto ?>,
						nav: <?php echo $nav ?>,
						dots: <?php echo $dot ?>,
						<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
						loop: true,
						autoHeight: true,
                        rtl: RTL,
						navText: ["<i class='ti-angle-left'></i>","<i class='ti-angle-right'></i>"],
						<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
							responsive:{
								0:{
									items:2,
                                    <?php if($dot != 'false' || $nav != 'false'): ?>
                                    dots: true,
                                    nav: false
                                    <?php endif ?>
								},
								500: {
									items:3,
                                    <?php if($dot != 'false' || $nav != 'false'): ?>
                                    dots: true,
                                    nav: false
                                    <?php endif ?>
								},
                                768: {
									items:4,
                                    <?php if($dot != 'false' || $nav != 'false'): ?>
                                    dots: true,
                                    nav: false
                                    <?php endif ?>
								},
								992:{
									items:5,
                                    <?php if($dot != 'false' || $nav != 'false'): ?>
                                    dots: true,
                                    nav: false
                                    <?php endif ?>
								},
                                1200: {
                                    items:<?php echo $perRow; ?>,
                                    dots: <?php echo $dot ?>,
                                    nav: <?php echo $nav ?>
                                }
							}
						<?php endif ?>
					});
				});
			</script>
		<?php else: ?>
			<div class="block-content<?php if($padding): ?> disable-padding<?php endif ?>">
				<ul class="row instagram-item-row">
					<?php foreach($images as $image): ?>
						<li class="col-md-<?php echo $col ?> col-sm-3 col-xs-6 instagram-item-col">
							<div class="instagram-item<?php if(!$this->getLike() && !$this->getComment()): ?> hover-effect<?php endif ?><?php if($this->getLink()): ?> enable-link<?php endif ?>">
								<?php if($this->getLink()): ?>
									<a href="<?php echo $image['link'] ?>" target="_blank">
								<?php endif ?>
								
									<?php if(!$lazyLoad): ?>
										<?php $baseImage = $image['src']; ?>
									<?php endif ?>
									<img class="img-fluid<?php if($lazyLoad): ?> lazy<?php endif ?>" src="<?php echo $baseImage ?>" data-src="<?php echo $image['src'] ?>" alt=""/>
								
								<?php if($this->getLink()): ?>
									</a>
								<?php endif ?>
								
								<?php if($this->getLike() || $this->getComment()): ?>
									<span class="social-count">
										<?php if($this->getLike()): ?>
											<span class="like-count"><span class="ti-heart"> </span> <span class="number"><?php echo $image['like'] ?></span></span>
										<?php endif ?>
										
										<?php if($this->getComment()): ?>
											<span class="comment-count"><span class="ti-comment-alt"> </span> <span class="number"><?php echo $image['comment'] ?></span></span>
										<?php endif ?>
									</span>
								<?php endif ?>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
			</div>
		<?php endif ?>
    </div>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('Can not get Instagram data or your instagram account have not any images.') ?></div>
	<?php endif ?>
</div>