<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$size = $themeHelper->getImageSize();


?>
<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>">
<?php
	$productImage = $_imagehelper->init($product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
	$imgAlt = $block->stripTags($product->getName(), null, true);
?>
    <img src="<?php echo $productImage ?>" alt="<?php echo $imgAlt; ?>" class="img-fluid product-image-photo"/>
</a>
