<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>


<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$settings = $themeHelper->getThemeSettings();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>

<?php $ratio = $this->getRatio(); ?>
<?php $size = $themeHelper->getImageSize($ratio); ?>
<?php $padding = $themeHelper->getImagePadding($ratio); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png'); ?>
<?php $fk = $block->getBlockHtml('formkey'); ?>

<?php
// Backend Config
$relatedSidebar = $themeHelper->getStoreConfig('mpanel/product_details/related_sidebar');
$showWishlist = $themeHelper->getStoreConfig('mpanel/product_details/wishlist_button');
$showCompare = $themeHelper->getStoreConfig('mpanel/product_details/compare_button');
$perRow = $themeHelper->getStoreConfig('mpanel/product_details/product_per_row_list');
$cf_Upsell = $themeHelper->getStoreConfig('mpanel/product_details/upsell_products');
$mbItem = $themeHelper->getStoreConfig('mpanel/catalog/product_per_row_mb');
?>

<?php
$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$hoverChange = $settings['catalog']['hover_change'] ? true : false;
$showCompare = $settings['catalog']['compare_button'] ? false : true;
$showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
			$image_hover = 'product_thumbnail_image';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
			$position = $block->getPosition();

            $image = 'related_products_list';
			$image_hover = 'product_thumbnail_image';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

            $showCart = false;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
			$image_hover = 'product_thumbnail_image';
            $title = __('Upsell Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $templateType = null;
            $showCart = false;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
			if(!$cf_Upsell){
				$exist = false;
			}
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
			$image_hover = 'product_thumbnail_image';
            $title = __('Upsell products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
			$image_hover = 'product_thumbnail_image';
            $title = __('More Choices');
            $items = $block->getItemCollection();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
			$image_hover = 'product_thumbnail_image';
            $title = __('More Choices');
            $items = $block->getItems();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
			$image_hover = 'product_thumbnail_image';
            $title = __('New Products');
            $items = $exist;
			
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>
<?php if ($exist):?>

	<?php $size = $themeHelper->getImageSize($this->getRatio()); ?>
	<?php $padding = $themeHelper->getImagePadding($this->getRatio()); ?>
	
	<?php if($type == 'related'): ?>
		<?php $_product = $block->getProduct() ?>
        
		<?php $pageLayout = $themeHelper->getProductLayout($_product) ?>
		<?php if($relatedSidebar && $position == 'sidebar' && $pageLayout != '1column'): ?>
			<div class=" block list-products list-products_relared <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
				<div class="block-title">
					<strong class="title" id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
				</div>
					<?php  $blockId = rand() . time(); ?>
					<?php $_collectionSize = count($items); ?>
					<div class="owl-carousel list-products mgs-carousel-<?php echo $blockId; ?>">
						<?php $i=0; foreach ($items as $_item): ?>

							<?php $review = $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
							<?php $postParams = $themeHelper->getAddToCartPostParams($_item); ?>
							<?php $prdPrice = $block->getProductPrice($_item) ?>
							<?php $wlDataPost = $block->getAddToWishlistParams($_item); ?>
							<?php if ($i++ % $perRow == 0): ?>
								<div class="item">
							<?php endif ?>
								<div class="item product product-item">
									<?php echo $this->getLayout()
												->createBlock('Magento\Framework\View\Element\Template')
												->setProduct($_item)
												->setThemeHelper($themeHelper)
												->setImageHelper($_imagehelper)
												->setCatalogHelperOutput($_helper)
												->setQuickViewHelper($quickViewHelper)
												->setRatio($ratio)
												->setSize($size)
												->setPadding($padding)
												->setLazyLoadBaseImage($baseImage)
												->setCompare($showCompare)
												->setFk($fk)
												->setPostParams($postParams)
												->setReview($review)
												->setPrdPrice($prdPrice)
												->setWishList($showWishList)
												->setWishListPost($wlDataPost)
												->setTemplate('MGS_Mpanel::products/product_item/list/widget_item.phtml')
												->setSwatches('')
												->toHtml(); ?>
								</div>
							<?php if ($i % $perRow == 0 || $i == $_collectionSize): ?>
								</div>
							<?php endif ?>
						<?php endforeach ?>
					</div>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('.mgs-carousel-<?php echo $blockId ?>').owlCarousel({
							items: 1,
							autoplay: false,
							autoplayHoverPause: false,
							nav: false,
							<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
							dots: true,
							autoHeight: true,
                            rtl: true
						});
					});
				</script>
			</div>
		<?php elseif((!$relatedSidebar && $position == 'maincontent') || $pageLayout == '1column'): ?>
			<div class=" detail-page-grid-products block related-product-main <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
				<div class="content-heading">
					<h3 class="title"><span id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span></h3>
				</div>
				
				<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
					<div class="products wrapper grid products-grid slider-1-row row products-<?php /* @escapeNotVerified */ echo $type; ?>">
						<div id="product-carousel-related" class="owl-carousel products items product-items items row-<?php echo $perRow; ?>">
							<?php foreach ($items as $_item): ?>
                            
                            <?php $review = $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
                            <?php $postParams = $themeHelper->getAddToCartPostParams($_item); ?>
                            <?php $prdPrice = $block->getProductPrice($_item) ?>
                            <?php $wlDataPost = $block->getAddToWishlistParams($_item); ?>
                            
								<div class="item product product-item">
                                    <?php echo $this->getLayout()
												->createBlock('Magento\Framework\View\Element\Template')
												->setProduct($_item)
												->setThemeHelper($themeHelper)
												->setImageHelper($_imagehelper)
												->setCatalogHelperOutput($_helper)
												->setQuickViewHelper($quickViewHelper)
												->setRatio($ratio)
												->setSize($size)
												->setPadding($padding)
												->setLazyLoadBaseImage($baseImage)
												->setCompare($showCompare)
												->setFk($fk)
												->setPostParams($postParams)
												->setReview($review)
												->setPrdPrice($prdPrice)
												->setWishList($showWishList)
												->setWishListPost($wlDataPost)
												->setTemplate('MGS_Mpanel::products/product_item/grid/default.phtml')
												->setSwatches('')
												->setHoverChange($hoverChange)
												->toHtml(); ?>
								</div>
							<?php endforeach ?>
						</div>
						<script type="text/javascript">
							require([
								'jquery',
								'mgs/owlcarousel'
							], function ($) {
								var owlcarousellrelated = $('#product-carousel-related').owlCarousel({
									items: <?php echo $perRow; ?>,
									autoplay: false,
									autoplayHoverPause: false,
									<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
									nav: false,
									dots: true,
                                    rtl: RTL,
									responsive:{
										0:{
											items: <?php echo $mbItem; ?>
										},
										768:{
											items: 3
										},
										1200:{
											items:<?php echo $perRow; ?>
										}
									}
								});
							});
						</script>
					</div>
				</div>
			</div>
		<?php endif ?>
	<?php else: ?>
		<div class=" detail-page-grid-products block <?php echo $class; ?><?php if($type == 'upsell'): ?> upsell-products-list<?php endif ?>" <?php if($type == 'upsell'): ?>  data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>"<?php endif ?>>
		
			<div class="content-heading">
				<h3 class="title">
					<span id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></span>
				</h3>
			</div>
			<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
					<div class="products wrapper grid row products-grid slider-1-row products-<?php /* @escapeNotVerified */ echo $type; ?>">
						<div id="<?php /* @escapeNotVerified */ echo $type; ?>-owl-carousel" class="products items product-items owl-carousel row-<?php echo $perRow; ?>">
							<?php $iterator = 1; ?>
							<?php foreach ($items as $_item): ?>
                            
                            <?php $review = $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
                            <?php $postParams = $themeHelper->getAddToCartPostParams($_item); ?>
                            <?php $prdPrice = $block->getProductPrice($_item) ?>
                            <?php $wlDataPost = $block->getAddToWishlistParams($_item); ?>
                            
							<div class="item product product-item"<?php if ($type == 'upsell'): ?> style="display: none;"<?php endif ?>>
                                <?php echo $this->getLayout()
												->createBlock('Magento\Framework\View\Element\Template')
												->setProduct($_item)
												->setThemeHelper($themeHelper)
												->setImageHelper($_imagehelper)
												->setCatalogHelperOutput($_helper)
												->setQuickViewHelper($quickViewHelper)
												->setRatio($ratio)
												->setSize($size)
												->setPadding($padding)
												->setLazyLoadBaseImage($baseImage)
												->setCompare($showCompare)
												->setFk($fk)
												->setPostParams($postParams)
												->setReview($review)
												->setPrdPrice($prdPrice)
												->setWishList($showWishList)
												->setWishListPost($wlDataPost)
												->setTemplate('MGS_Mpanel::products/product_item/grid/default.phtml')
												->setSwatches('')
												->setHoverChange($hoverChange)
												->toHtml(); ?>
							</div>
						<?php endforeach ?>
					</div>
					<script type="text/javascript">
						require([
							'jquery',
							'mgs/owlcarousel'
						], function ($) {
							var owlcarousell<?php echo $type; ?> = $('#<?php echo $type; ?>-owl-carousel').owlCarousel({
								items: <?php echo $perRow; ?>,
								autoplay: false,
								autoplayHoverPause: false,
								nav: false,
								<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
								dots: true,
                                rtl: RTL,
								responsive:{
                                    0:{
                                        items: <?php echo $mbItem; ?>
                                    },
                                    768:{
                                        items: 3
                                    },
                                    1200:{
                                        items:<?php echo $perRow; ?>
                                    }
                                }
							});
						});
					</script>
				</div>
			</div>
		</div>
    <?php endif; ?>
<?php endif;?>
