<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \MGS\Landing\Block\Landing
 */
?>

<?php $_categories = $block->getChildCategory(); ?>

<?php //Block Config ?>
<?php $per_row = $block->getConfig('mgs_landing/general/per_row'); ?>
<?php $shortdes = $block->getConfig('mgs_landing/general/show_shortdes'); ?>
<?php $character = $block->getConfig('mgs_landing/general/character'); ?>
<?php $newproduct = $block->getConfig('mgs_landing/general/show_newproduct'); ?>
<?php $crId = ""; ?>
<?php $crId .= $this->getCurrentId(); ?>
<?php $perrow = $this->getPerrow(); ?>
<?php if($perrow == ""): ?>
    <?php $perrow = $block->getConfig('mpanel/catalog/product_per_row'); ?>
<?php endif ?>
<?php // Block Content ?>

<?php

$om = \Magento\Framework\App\ObjectManager::getInstance();

$urlInterface = $om->get('Magento\Framework\UrlInterface');
$currentUrl = $urlInterface->getCurrentUrl();

$storeManager = $om->get('\Magento\Store\Model\StoreManagerInterface');
$pubMediaDir = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$currentCategory = $om->create('Magento\Catalog\Model\Category')->load($block->getSelectedCategoryId());
?>
<?php if (false) : ?>
<div class="container-fluide">
    <div class="category-banner-banner">
      <img src="<?php echo $currentCategory->getPromoBannerMainImage() ? $pubMediaDir.'catalog/category/'.$currentCategory->getPromoBannerMainImage() : ''; ?>">
      <div class="category-landing-text">
          <p><?php echo $currentCategory->getPromoBannerTagLine() ? $currentCategory->getPromoBannerTagLine() : ''; ?></p>
          <h2><?php echo $currentCategory->getPromoBannerMainHeading() ? $currentCategory->getPromoBannerMainHeading() : ''; ?></h2>
          <span><?php echo $currentCategory->getPromoBannerContent() ? $currentCategory->getPromoBannerContent() : ''; ?></span>
          <a href="<?php echo $currentCategory->getPromoBannerLink() ? $currentCategory->getPromoBannerLink() : ''; ?>">SHOP NOW</a>
      </div>
    </div>
</div>
<?php endif; ?>
<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $title = $objectManager->get('Magento\Framework\View\Page\Title');
?>
<?php if (false) : ?>
<div class="category-alnding-main-title">
    <h2><?php echo $title->getShort() ?></h2>
</div>
<div class="input-group category-search-part">
    <form action="<?php echo $currentUrl; ?>" class="search-form" method="post" autocomplete="off">
        <input id="search_input" name="search_cat" value="<?php echo $block->getSearchQuery() ?>" placeholder="Search For Categorys & More" autocomplete="off" type="text">
        <span class="input-group-btn">
          <button type="submit" id="search_submit">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </span>
    </form>
</div>
<?php endif; ?>
<div class="container">
<div class="landing-categories--grid">
    <div class="row">
        <?php $i =0; foreach ($_categories as $_category): ?>
            <?php if ($_category->getIsActive()): ?>
                <?php $i++; ?>
                <div class="col-sm-3 <?php echo $block->getColClass($i,'grid'); ?>">
                    <?php $crId .= ','. $_category->getId(); ?>

                    <div class="category-img-text">
                         <div class="category-img">
                            <a href="<?php echo $block->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>">
                                <img src="<?php echo $block->getImageUrl($_category->getId()); ?>" alt="<?php echo $block->escapeHtml($_category->getName()) ?>" class="img-fluid" />
                            </a>
                         </div>
                         <div class="category-text">
                             <a href="<?php echo $block->getCategoryUrl($_category) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a>
                         </div>
                     </div>
                </div>
            <?php endif; ?>
        <?php endforeach ?>
    </div>
</div>
</div>

<?php if($newproduct): ?>
    <?php $ratio = $block->getConfig('mpanel/catalog/picture_ratio'); ?>
    <?php $limit = $block->getConfig('mgs_landing/general/number_show'); ?>
    <?php $new_product_title = $block->getConfig('mgs_landing/general/new_product_title'); ?>
    <?php $new_product_subtitle = $block->getConfig('mgs_landing/general/new_product_subtitle'); ?>
    
    <div class="collection-new-product">
        <?php echo $block->getLayout()
                        ->createBlock('MGS\Mpanel\Block\Products\NewProducts')
                        ->setCategoryIds($crId)
                        ->setPerrow($perrow)
                        ->setUseSlider(0)
                        ->setMgsPanelTitle($new_product_title ? $new_product_title : __('NEW ARRIVALS'))
                        ->setMgsPanelNote($new_product_subtitle ? $new_product_subtitle : __('FRESH AIR'))
                        ->setRatio($ratio)
                        ->setLoadmore(0)
                        ->setLimit($limit ? $limit : 12)
                        ->setTemplate('MGS_Mpanel::products/new/grid.phtml')
                        ->toHtml();
                        ?>
    </div>
<?php endif ?>