<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \MGS\Landing\Block\Landing
 */
?>

<?php $_categories = $block->getChildCategory(); ?>

<?php //Block Config ?>
<?php $per_row = $block->getConfig('mgs_landing/general/per_row'); ?>
<?php $shortdes = $block->getConfig('mgs_landing/general/show_shortdes'); ?>
<?php $character = $block->getConfig('mgs_landing/general/character'); ?>
<?php $newproduct = $block->getConfig('mgs_landing/general/show_newproduct'); ?>
<?php $crId = ""; ?>
<?php $crId .= $this->getCurrentId(); ?>
<?php $perrow = $this->getPerrow(); ?>
<?php if($perrow == ""): ?>
    <?php $perrow = $block->getConfig('mpanel/catalog/product_per_row'); ?>
<?php endif ?>

<?php // Block Content ?>
<div class="landing-categories--grid landing-categories--masonry row">
    <?php $i =0; foreach ($_categories as $_category): ?>
        <?php if ($_category->getIsActive()): ?>
            <?php $i++; ?>
            <?php $crId .= ','. $_category->getId(); ?>
            <div class="landing-masonry-item <?php echo $block->getColClass($i,'masonry'); ?>">
                <div class="landing-categories--item">
                    <div class="landing-categories--thumb">
                        <a href="<?php echo $block->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>">
                            <img src="<?php echo $block->getImageUrl($_category->getId()); ?>" alt="<?php echo $block->escapeHtml($_category->getName()) ?>" class="img-fluid" />
                        </a>
                    </div>
                        
                    <h2 class="title"><?php echo $block->escapeHtml($_category->getName()) ?></h2>
                    
                    <div class="landing-categories-detail">
                        <?php if($shortdes): ?>
                            <?php $_description = $block->getCateDescription($_category->getId()); ?>
                            <?php if ($_description): ?>
                                <div class="landing-categories--shortdes">
                                    <div class="category-description">
                                        <?= strip_tags($this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description')); ?>
                                    </div>
                                </div>
                            <?php endif ?>
                        <?php endif ?>
                        <a class="btn  btn-primary  btn-product " href="<?= $block->getCategoryUrl($_category) ?>"><?= __('%1 Product(s)', $_category->getProductCount()) ?></a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php endforeach ?>
</div>
<script type="text/javascript">
    requirejs([ 
        'require', 
        'jquery', 
        'mgs/isotope' 
    ], function( require, $, Isotope ) {
        require( [ 'bridget' ], function( jQueryBridget ) {
            jQueryBridget( 'isotope', Isotope, $ );
            $(document).ready(function() {
                var container = $('.landing-categories--grid').isotope({
                    itemSelector: '.landing-masonry-item',
                    percentPosition: true,
                    masonry: {
                        columnWidth: '.landing-masonry-item'
                    }
                });
            });     
        });
    });
</script>

<?php if($newproduct): ?>
    <?php $ratio = $block->getConfig('mpanel/catalog/picture_ratio'); ?>
    <?php $limit = $block->getConfig('mgs_landing/general/number_show'); ?>
    <?php $new_product_title = $block->getConfig('mgs_landing/general/new_product_title'); ?>
    <?php $new_product_subtitle = $block->getConfig('mgs_landing/general/new_product_subtitle'); ?>
    
    <div class="collection-new-product">
        <?php echo $block->getLayout()
                        ->createBlock('MGS\Mpanel\Block\Products\NewProducts')
                        ->setCategoryIds($crId)
                        ->setPerrow($perrow)
                        ->setUseSlider(0)
                        ->setMgsPanelTitle($new_product_title ? $new_product_title : __('NEW ARRIVALS'))
                        ->setMgsPanelNote($new_product_subtitle ? $new_product_subtitle : __('FRESH AIR'))
                        ->setRatio($ratio)
                        ->setLoadmore(0)
                        ->setLimit($limit ? $limit : 12)
                        ->setTemplate('MGS_Mpanel::products/new/grid.phtml')
                        ->toHtml();
                        ?>
    </div>
<?php endif ?>