<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Mostviewed
 */
?>
<?php
/**
 * @var \Amasty\Mostviewed\Block\Widget\Related $block
 * @codingStandardsIgnoreFile
 */

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
//$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');

?>
<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'related_products_content';
    $items = $block->getProductCollection()->getItems();

    $isSlider = $block->getBlockLayout();
    $tagWrap = $isSlider ? 'div' : 'ol';
    $tag = $isSlider ? 'div' : 'li';

    $showWishlist = true;
    $showCompare = true;
    $showCart = $block->getAddToCart();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>

    <div class="block <?= /* @noEscape */ $block->getCssClass() ?> amrelated-grid-wrapper block-products-list <?= /* @noEscape */ $mode ?>"
         id="amrelated-block-<?= (int)$block->getGroupId();?>"
    >
        <?php if ($block->getTitle()) : ?>
            <div class="block-title pdp-related-top-title">
                <h3><?= $block->escapeHtml(__($block->getTitle())) ?></h3>
            </div>
        <?php endif; ?>
        <div class="block-content related-slider-title">
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <<?= /* @noEscape */ $tagWrap?> class="product-items <?= /* @noEscape */ $type ?>" <?= /* @noEscape */ $isSlider ? 'data-amrelated-js="slider"' : ''?>>
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item) : ?>
                        <?php  $product = $productRepository->getById($item->getId()); ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '' : '</' . $tag . '>' ?><<?= /* @noEscape */ $tag?> class="product product-item pdp-bottom-product">

                        <div class="product-item-info product-section">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" class="product-item-photo">
                                <?= /* @noEscape */ $block->getImage($item, $image)->toHtml() ?>
                            </a>
                            <div class="plus-icon actions-quickview" id="product-<?php echo $product->getId(); ?>">
                                <?php echo $quickViewHelper->aroundQuickViewHtml($product); ?>
                            </div>
                            <div class="share-icon">
                                <div class="share-social-part">
                                    <a href="javascript:void(0);" tabindex="0"> </a>
                                </div>
                                <div class="social-section product-share-icon">
                                    <ul>
                                        <li>
                                            <!-- Facebook -->
                                            <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($product->getProductUrl());?>&t=
                            <?php echo urlencode($product->getName())?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on facebook">
                                                <i class="fa fa-facebook" aria-hidden="true"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <!-- TWITTER -->
                                            <a href="http://twitter.com/home/?status=<?php echo urlencode($product->getProductUrl());?>
                            (<?php echo urlencode($product->getName())?>)" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Twitter">
                                                <i class="fa fa-twitter" aria-hidden="true"></i>
                                            </a>
                                        </li>                                        
                                    </ul>
                                </div>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType) : ?>
                                    <?= /* @noEscape */ $block->getReviewsSummaryHtml($item, $templateType) ?>
                                <?php endif; ?>
                                                              
                                <?= /* @noEscape */ $block->getProductPriceHtml($item, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE) ?>
                               
                                <?= $block->getBrandLogoHtml($item) ?>
                                <?php if ($showCart) : ?>
                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($item->isSaleable()) : ?>
                                                    <?php if ($item->getTypeInstance()->hasRequiredOptions($item)) : ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($item)) ?>"}}' type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <?php
                                                        $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($item), ['product' => $item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary" data-post='<?= /* @noEscape */ $postData ?>' type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else : ?>
                                                    <?php if ($item->getIsSalable()) : ?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item) ?>'
                                                       class="action towishlist"
                                                       data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtml(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($item) ?>'
                                                       title="<?= $block->escapeHtml(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>

                        <?= /* @noEscape */ ($iterator == count($items)+1) ? '</' . $tag . '>' : '' ?>

                    <?php endforeach ?>
                </<?= /* @noEscape */ $tagWrap?>>
            </div>
        </div>
    </div>
    <?php if ($isSlider) : ?>
        <script type="text/javascript">
            require([
                "jquery",
                "Amasty_Base/vendor/slick/slick.min"
            ], function ($) {
                $('#amrelated-block-<?= /* @noEscape */ (int)$block->getGroupId();?> [data-amrelated-js="slider"]').slick(
                    {
                        dots:false,
                        infinite: true,
                        slidesToShow: 4,
                        slidesToScroll: 1,
                        responsive: [
                            {
                                breakpoint: 1280,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 3
                                }
                            },
                            {
                                breakpoint: 992,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 2
                                }
                            },
                            {
                                breakpoint: 425,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1
                                }
                            }
                        ]
                    }
                );
            });
        </script>
    <?php endif; ?>
<?php endif;?>
