<?php if ($block->getConfig('general_settings/enabled') && $block->getConfig('product_page_settings/show_related_products_by_brand')): ?>

    <?php
        $brand = $block->getBrand();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
        $settings = $themeHelper->getThemeSettings();
        $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
        $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
    ?>
    
    <?php
        // Backend Config
        $ratio = $themeHelper->getStoreConfig('mpanel/catalog/picture_ratio');
        $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
        $mbItem = $themeHelper->getStoreConfig('mpanel/catalog/product_per_row_mb');
    ?>
    
    <?php $size = $themeHelper->getImageSize($ratio); ?>
    <?php $padding = $themeHelper->getImagePadding($ratio); ?>
    <?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png'); ?>
    <?php $fk = $block->getBlockHtml('formkey'); ?>

    <?php
        $showCompare = $settings['catalog']['compare_button'] ? false : true;
        $showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
		$hoverChange = $settings['catalog']['hover_change'] ? true : false;
    ?>
    <?php $perRow = $block->getConfig('product_page_settings/perrow_related_products'); ?>
	<?php if ($brand): ?>
		<?php if($block->getConfig('product_page_settings/title_related_products')): ?>
			<?php $blockTitle = $block->getConfig('product_page_settings/title_related_products'); ?>
		<?php else: ?>
			<?php $blockTitle = __('Related Products By Brand') ?>
		<?php endif ?>
		
		<?php $_productCollection = $block->getProductCollection(); ?>
		
		<?php if (count($_productCollection)): ?>
			<div class="brand-related-products detail-page-grid-products">
				<div class="content-heading">
					<h3 class="title"><?php echo $blockTitle; ?></h3>
				</div>
				
				<div class="block-content content" aria-labelledby="block-heading">
					<div class="products wrapper grid products-grid slider-1-row products-related row">
						<div id="brand-related-products" class="items product-items owl-carousel row-<?php echo $perRow; ?>">
							<?php foreach ($_productCollection as $_product): ?>
                                <?php $wlDataPost = $block->getAddToWishlistParams($_product); ?>
                                <?php $fk = $block->getBlockHtml('formkey')?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <?php $review = $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
                                <?php $prdPrice = $block->getProductPrice($_product) ?>
                                
								<div class="item product product-item">
                                   <?php echo $this->getLayout()
													->createBlock('Magento\Framework\View\Element\Template')
													->setProduct($_product)
													->setThemeHelper($themeHelper)
													->setImageHelper($_imagehelper)
													->setCatalogHelperOutput($_helper)
													->setQuickViewHelper($quickViewHelper)
													->setRatio($ratio)
													->setSize($size)
													->setPadding($padding)
													->setLazyLoadBaseImage($baseImage)
													->setCompare($showCompare)
													->setFk($fk)
													->setPostParams($postParams)
													->setReview($review)
													->setPrdPrice($prdPrice)
													->setWishList($showWishList)
													->setWishListPost($wlDataPost)
													->setTemplate('MGS_Mpanel::products/product_item/grid/default.phtml')
													->setSwatches('')
													->setHoverChange($hoverChange)
													->toHtml(); ?>
								</div>
							<?php endforeach ?>
						</div>
						<script type="text/javascript">
							require([
								'jquery',
								'mgs/owlcarousel'
							], function ($) {
								var brandrelatedproducts = $('#brand-related-products').owlCarousel({
									items: <?php echo $perRow; ?>,
									autoplay: false,
									autoplayHoverPause: false,
									<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
									nav: false,
									dots: true,
                                    rtl: true,
									responsive:{
										0:{
											items: <?php echo $mbItem ?>
										},
										768:{
											items: 3
										},
										1200:{
											items:<?php echo $perRow; ?>
										}
									}
								});
							});
						</script>
					</div>
				</div>
			</div>
		<?php endif; ?>
		
	<?php endif; ?>
	
<?php endif; ?>
