<div class="container-fluide">
    <div class="banner-img">
        <img src="<?php echo $block->getViewFileUrl('images/sweda-banner.png'); ?>">
    </div>
</div>

<div class="container-fluide back-img">
    <div class="container">
        <div class="smart-project-section">
            <div class="row">
                <div class="col-md-12">
                    <div class="project-title">
                        <h2>READY. SET. GO!</h2>
                        <p>Start your project today!</p>
                    </div>
                </div>
            </div>
            <div class="option-section">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>Type Of Product</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                        <!--   <div class="arrow-icon">
                          </div> -->
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>What’s Your Budget?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>How Many Do You Need?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12  project-option">
                        <select class="form-control search-slt" id="exampleFormControlSelect1">
                            <option>When Do You Need It?</option>
                            <option>option-1</option>
                            <option>option-2</option>
                            <option>option-3</option>
                            <option>option-4</option>
                        </select>
                    </div>


                    <div class="project-btn">
                        <a href="#">Show Me What’s Available!</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!------ use-full-section --------->
<div class="container">
    <div class="usefull-section desktop-only">
        <h2 class="main-title">Useful Tools</h2>
        <div class="row">
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/usefull-img-1.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/usefull-img-2.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/usefull-img-3.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 center">
                <a href="#">
                    <div class="section-content">
                        <img src="<?php echo $block->getViewFileUrl('images/usefull-img-4.png'); ?>">
                        <h3>Add Your logo</h3>
                        <p>Get a Preview of your <br>final Product</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="bottom-section">
            <div class="row">
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/usefull-img-5.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/usefull-img-6.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/usefull-img-7.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
                <div class="col-sm-3 center">
                    <a href="#">
                        <div class="section-content">
                            <img src="<?php echo $block->getViewFileUrl('images/usefull-img-8.png'); ?>">
                            <h3>Add Your logo</h3>
                            <p>Get a Preview of your <br>final Product</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>

    </div>
</div>
<!------ over-full-section --------->

<!------ feacture-section --------->
<div class="container">
    <div class="feacture-section">
        <h2 class="main-title">FEATURED IMPRINT METHODS</h2>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/feacture-1.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>CHISEL IT</h3>
                <p>Digital chisel method for drinkware items; Chiseled logo reveals brilliant stainless steel
                    underneath.</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/feacture-2.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>IT’S A WRAP</h3>
                <p>It’s A Wrap can be matched to your brand! Add your logo to any It’s A Wrap design for a truly custom
                    product </p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="feacture-img">
                <img src="<?php echo $block->getViewFileUrl('images/feacture-3.png'); ?>">
            </div>
            <div class="feacture-text">
                <h3>SPECTRUM </h3>
                <p>Full color digital printing directly onto your product. Add your brand to drinkwear, writing
                    instruments and more! </p>
            </div>
        </div>
    </div>
    <div class="feacture-view-all">
        <a href="#">VIEW ALL OUR IMPRINT METHODS</a>
    </div>
</div>
<!------ over-feacture-section --------->

<!------ solution-section --------->
<div class="container">
    <div class="solution-section solution-banner">
        <div class="row">
            <div class="col-sm-8">
                <div class="solution-content">
                    <h3>THE<strong> SHIP SAVER </strong>SOLUTION </h3>
                    <p><strong>Ship and Save with SWEDA!</strong>Experience ground shipping at FOB Memphis <br> rates
                        for orders shipping to FedEx zones 7 & 8</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="solution-btn">
                    <a href="#">Learn More</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!------ over-solution-section --------->

<!------ news-letter-section --------->
<div class="container-fluide news-letter-banner">
    <div class="news-letter-text">
        <h3>SIGN UP FOR OUR NEWSLETTER</h3>
        <p>Subscribe to the SWEDA mailing list to recieve <br>the latest news and special offers</p>
        <div class="Subscribe-section">
            <input type="text" class="search-query form-control" placeholder="Enter Your Email Address">
            <span class="news-section-btn">
                  <button type="button" disabled="">
                     <p>subscriber</p>
                  </button>
               </span>
        </div>
    </div>
</div>
<!------ over-news-letter-section --------->