<?php $helper = $this->helper('MGS\Gallery\Helper\Data'); ?>

<?php $current_page =  $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>

<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('sidebar_settings/enabled')): ?>
		<?php if ($block->getConfig('sidebar_settings/show_categories')): ?>
            <?php $categories = $block->getCategories(); ?>
            <?php if (count($categories)): ?>
                <nav class="nav-sidebar">
                    <ul class="nav tabs">
                        <?php foreach ($categories as $category): ?>
                            <li class="<?php echo ($current_page == $category->getCategoryUrl())?'active':'' ; ?>">
                                <div class="form_chkbx">
                                    <a  title="<?php echo $category->getTitle(); ?>"
                                       href="<?php echo $category->getCategoryUrl(); ?>">
                                        <?php echo $category->getTitle(); ?>
                                    </a>
                                </div>
                            </li>
                        <?php endforeach; ?>
                        <li class="">
                            <div class="form_chkbx">
                                <a title="Customize Your Own Catalog" href="https://sweda.zoomcustom.com" target="_blank">
                                Customize Your Own Catalog</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

