<?php $_helper = $this->helper('MGS\Ajaxlayernavigation\Helper\Config');?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter mgs-filter" id="layered-filter-block">
		<div class="block-title filter-title">
			<div class="container">
				<strong><?php /* @escapeNotVerified */ //echo __('Shop By') ?></strong>
				
				<div class="block-actions filter-actions">
					<button id="btn_view_result" class="btn btn-primary btn-xs btn-result"><?php echo __('View Result') ?></button>
				</div>
				<?php if ($block->getLayer()->getState()->getFilters()): ?>
				<a class="filter-active-item-clear-all action clear filter-clear"
				title="<?php /* @escapeNotVerified */ echo __('Clear All') ?>"
				href="<?php /* @escapeNotVerified */ echo $_helper->getClearAllUrl() ?>">
					<span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span>
				</a>
				<?php endif ?>
			</div>
		</div>

        <div class="block-content filter-content">
			<div class="container">
				<?php echo $block->getChildHtml('state') ?>
				<div class="block-filter-content filter-wrapper">
					<?php $wrapOptions = false; ?>
					<?php foreach ($block->getFilters() as $filter): ?>
						<?php if (!$wrapOptions): ?>
							<div class="filter-options" id="narrow-by-list">
								<?php $wrapOptions = true; endif; ?>
								<?php if ($filter->getItemsCount()): ?>
									<?php
										if ($filter->getFilterItemsCount()) {
											$itemIds = $filter->getFilterItemsCount();
											$attributteId = $filter->getAttributeModel()->getAttributeId();
											$itemProductIds[$attributteId] = $itemIds[$attributteId];
										}
									?>
								<div class="filter-options-item filter-item">
									<div role="heading" aria-level="3" class="filter-options-title">
										<?php echo $block->escapeHtml(__($filter->getName())) ?>
									</div>
									<div class="filter-options-content"> 
										<?php 
										$isPrice = false;
										if($_helper->usePriceSlide()){ 
											$maxPrice = 0;
											$minPrice = 0;

											if ($filter->hasAttributeModel()) {
												$attributeModel = $filter->getAttributeModel();
												if ($attributeModel->getAttributeCode() == 'price') { 
													$isPrice = true;
													$minPrice = $filter->getMinPrice();
													$maxPrice = $filter->getMaxPrice();
												}
											}
										}
									?>
									<?php if ($isPrice) : ?>
										<div>
											<input type="text" id="price-range-slider" data-from="<?php echo $minPrice ?>" data-to="<?php echo $maxPrice ?>" name="price-range-slider" />
										</div>
									<?php else : ?>
										<?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
									<?php endif; ?> 
									</div>
								</div>
							<?php endif; ?>
					<?php endforeach; ?>
							<?php if ($wrapOptions): ?>
							</div>
							<?php endif; ?>
					
				</div>
			</div>
        </div>
    </div>
<?php endif; ?>
