<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= $block->escapeHtml($_item->getId()) ?>_title"
         class="product-title">
             <?= $block->escapeHtml($_item->getName()) ?>
    </div>
    <div class="product-sku-block">
        <span><?= $block->escapeHtml(__('SKU')) ?>:</span> <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($block->getSku()))) ?>
    </div>

    <dl class="item-options">
        <?php
        foreach ($block->getOrderOptions() as $_option):
            $allOption = $_option;
            ?>
            <dt><?= $block->escapeHtml($_option['label']) ?>:</dt>
            <dd>
                <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                    <?= /* @escapeNotVerified */ $block->getCustomizedOptionValue($_option) ?>
                <?php else: ?>
                    <?php $_option = $block->getFormattedOption($_option['value']); ?>
                    <?= $block->escapeHtml($_option['value']) ?>
                    <?php
                    if (isset($allOption['code']) && ($allOption['code'] == 'product_design')) {
                        $design_id = $allOption['design_id'];
                        $order_id = $this->getRequest()->getParam('order_id');
                        ?>
                        <a target="_blank" href="<?php echo $this->getUrl('productdesigner/productdesigner/viewDesign') ?>design_id/<?php echo $design_id; ?>/order_id/<?php echo $order_id; ?>/item_id/<?php echo $_item->getId(); ?> ">
                            <span>View Design</span></a>
                        <?php
                    }
                    ?>
                    <?php if (isset($_option['remainder']) && $_option['remainder']): ?>
                        <?php $dots = 'dots' . uniqid(); ?>
                        <span id="<?= /* @noEscape */ $dots; ?>"> ...</span>
                        <?php $id = 'id' . uniqid(); ?>
                        <span id="<?= /* @noEscape */ $id; ?>"><?= $block->escapeHtml($_option['remainder']) ?></span>
                        <script>
                            require(['prototype'], function () {
                                $('<?= /* @noEscape */ $id; ?>').hide();
                                $('<?= /* @noEscape */ $id; ?>').up().observe('mouseover', function () {
                                    $('<?= /* @noEscape */ $id; ?>').show();
                                });
                                $('<?= /* @noEscape */ $id; ?>').up().observe('mouseover', function () {
                                    $('<?= /* @noEscape */ $dots; ?>').hide();
                                });
                                $('<?= /* @noEscape */ $id; ?>').up().observe('mouseout', function () {
                                    $('<?= /* @noEscape */ $id; ?>').hide();
                                });
                                $('<?= /* @noEscape */ $id; ?>').up().observe('mouseout', function () {
                                    $('<?= /* @noEscape */ $dots; ?>').show();
                                });
                            });
                        </script>
                    <?php endif; ?>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
    <?= $block->escapeHtml($_item->getDescription()) ?>
<?php endif; ?>
