<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();



$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$instagram = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('socialmedia/general/instagram');
$facebook = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('socialmedia/general/facebook');
$twitter = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('socialmedia/general/twitter');
$google = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('socialmedia/general/google');
$promo = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('promomess/general/promomessage');
$promolink = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('promomess/general/promolink');


?>

<!------ desktop-navbar-top-section --------->
<div class="desktop-only">
    <div class="container-fluide border-bottom">
        <div class="container">
            <div class="row">
                <div class="top-bar">
                    <div class="col-sm-4">
                        <div class="social-section">
                            <ul>
                                <li><a href="<?php echo $instagram ;?>" target="_blank">
                                    <i class="fa fa-instagram" aria-hidden="true"></i>
                                    <!-- <img src="<?php echo $this->getViewFileUrl('images/sweda/instagram.png'); ?>"/> -->
                                </a>
                                </li>
                                <li><a href="<?php echo $facebook; ?>" target="_blank">
                                    <!-- <img src="<?php echo $this->getViewFileUrl('images/sweda/facebook.png'); ?>"> -->
                                    <i class="fa fa-facebook" aria-hidden="true"></i>
                                </a>
                                </li>
                                <li><a href="<?php echo $twitter; ?>" target="_blank">
                                    <i class="fa fa-twitter" aria-hidden="true"></i>
                                    <!-- <img src="<?php echo $this->getViewFileUrl('images/sweda/twitter.png'); ?>"/> -->
                                </a>
                                </li>
                                <p><a href="<?php echo $promolink; ?>"><?php echo $promo; ?></a></p>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="login-right-section">
                            <ul>
                                <li>
                                    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/sweda/add-your-logo.png'); ?>"/><?php echo __('Add Your Logo') ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $store->getBaseUrl().'startProject'; ?>"><img src="<?php echo $this->getViewFileUrl('images/sweda/start-project.png'); ?>"/><?php echo __('Start a Project') ?></a>
                                </li>

                                <li>
                                    <?php
                                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
                                    if ($customerSession->isLoggedIn()) { ?>
                                    <div class="my-account-link customer-login">
                                        <div class="actions toggle-toplinks">
                                            <a href="<?php echo $this->getUrl("customer/account");?>">
                                                <img src="<?php echo $this->getViewFileUrl('images/sweda/Log-in.png'); ?>"/><?php echo __('Hi,') ?>
                                                <?php echo $customerSession->getCustomer()->getFirstname();?>
                                            </a>
                                        </div>
                                        <div class="toplinks-content">
                                            <ul class="links">
                                                <li><a href="<?php echo $this->getUrl("customer/account");?>">VIEW ACCOUNT</a></li>
                                                <li><a href="<?php echo $this->getUrl("customer/account/logout"); ?>">LOG OUT</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->getUrl("customer/account/login"); ?>">
                                            <img src="<?php echo $this->getViewFileUrl('images/sweda/Log-in.png'); ?>"/><?php echo __('Log in') ?>
                                        </a>   
                                    <?php } ?>
                                </li>

                                <li>
                                    <a href="<?php echo $store->getBaseUrl(); ?>customer-service"><?php echo __('Need Help?') ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!------over-navbar-top-section --------->